### ISSUE TITLE
Tables and data not reflecting immediately 

### ISSUE THREAD

**Issue by vigneshmunisamy** [ujjwalguptaofficial/JsStore#1]
Hi,

When am adding new data or Table, It's not Showing immediately .

**Comment by ujjwalguptaofficial** [comment]
Hey Thanks for the letting us know.

Can you please share your code ? 
And you have mentioned its not showing immediately, can you tell me where it is not showing?

**Comment by vigneshmunisamy** [comment]
Thanks for sharing knowledge .. Can i have perform OR condition in Select Query.

Example.. Select * from customer where name='xyz' or email="xyz@gmail.com"

**Comment by vigneshmunisamy** [comment]
Browser Inspect element, Application ->Index DB ,Not showing data immediately.

**Comment by ujjwalguptaofficial** [comment]
Yes the browser does not refresh data when you do any operations. It retrieve data only on page load. So in order to see the new data, you can refresh the IndexedDB tab.

**Comment by ujjwalguptaofficial** [comment]
Example.. 
`Select * from customer where name='xyz' or email="xyz@gmail.com"
`

yes we can do that too. But currently this feature is not available in JsStore. This is a top priority for us and It will be available in few days. I will let you know.

If you don't mind, please add new issue for "or operation" . We are going to close the current issue.

**Comment by vigneshmunisamy** [comment]
Sure ...thanks for quick response

**Comment by ujjwalguptaofficial** [comment]
@vigneshmunisamy - I have added the support for or query.

 Example - 

Query in sql - 

`Select * from customer where name='xyz' or email="xyz@gmail.com`

Query in JsStore

`var Connection = new JsStore.Instance("Demo");
Connection.select({
    From: "customer",
    Where:{
        name:'xyz',
        Or:{
            email:'xyz@gmail.com'
        }
    },
    OnSuccess:function (results){
        log(results);
    },
    OnError:function (error) {
        log(error);
    }
});`

For more please check the tutorial - [](http://jsstore.net/tutorial/or)
