### ISSUE TITLE
Distinct

### ISSUE THREAD

**Issue by neomicho85** [ujjwalguptaofficial/JsStore#10]
Right now the possibility to use SELECT DISTINCT(field) is implemented?

**Comment by ujjwalguptaofficial** [comment]
no its not there. We will add it .

Thanks

**Comment by neomicho85** [comment]
It would be great, the performance is very good. It'll sound crazy but distinct will save a lot of work. Right now I'm playing with lovefield, but JsStore is like more friendly! Good Job!

**Comment by ujjwalguptaofficial** [comment]
yeah good to hear. We are working on optimization and adding new features. It was great help from you to finding these case and issues. Thanks for your contribution.

**Comment by ujjwalguptaofficial** [comment]
We have added the feature of distinct . check out here - http://jsstore.net/tutorial/distinct.

**Comment by ujjwalguptaofficial** [comment]
closing
