### ISSUE TITLE
JsStore framework breakdown when query key is undefined

### ISSUE THREAD

**Issue by f5cs** [ujjwalguptaofficial/JsStore#100]
Hi ujjwalguptaofficial :
when i execute the jsstore:
connection.select({
	from:'Trans',
	where:{
		tid:undefined
	}
});

Causing serious errors：
jsstore.worker.js:231 ：DOMException: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key.
jsstore.worker.js:1967： Uncaught (in promise) TypeError: Cannot read property '!=' of undefined

__proto__: Promise[[PromiseStatus]]: "**pending**"[[PromiseValue]]: undefined

All operations are blocked by PromiseStatus pending.
the jsstore can't work again util to reload page again.

can u  do some exception handling to avoid this？

**Comment by ujjwalguptaofficial** [comment]
Hi - undefined & null are not valid keys. Check this for more info  - https://stackoverflow.com/questions/52749199/jsstore-search-for-a-null-value

**Comment by f5cs** [comment]
I think this is a particularly serious problem with JsStore. Bug is almost impossible to eliminate completely. In the case of bugs, query key maby null causes JsStore to crash, and when JsStore crashes, the entire application is paralyzed.

It is painful to check each parameter (including null, undeinfed, type) before performing the JsStore operation.

I share my experience.
Define a global variable promiseHanlder = {};

function parent(params){
  return new Promise(function(rl,rj){
     var uuid = UUID.generate();
    promiseHanlder[uuid] = {rl,rj}
     try{
        sub(params)
     }catch(err){
         ...
     }finally{
        ...
    }
});
}

function sub(params,parentPromiseId){
  return new Promise(function(rl,rj){
     var uuid = UUID.generate();
    promiseHanlder[uuid] = {rl,rj,timeout:new Date().getTime()+10000}
     var rs;
     try{
       rs = ...
     }catch(err){
       if(parentPromiseId){
          promiseHanlder[parentPromiseId].rj(rs);
       }
     }finally{
       if(parentPromiseId){
          delete promiseHanlder[parentPromiseId];
       }
    }
});
}

**Comment by ujjwalguptaofficial** [comment]
ok got it, I think adding null check in framework itself will solve the issue.

**Comment by ujjwalguptaofficial** [comment]
Fixed the issue. Please download the new version - 2.10.3 .

**Comment by f5cs** [comment]
thks.
