### ISSUE TITLE
idbCon.createDb not a function

### ISSUE THREAD

**Issue by jaymehtasa** [ujjwalguptaofficial/JsStore#107]
ERROR: *Property 'createDb' does not exist on type 'Instance'.*

```ts
    const isDbCreated = await idbCon.isDbExist(dbname);
    if (isDbCreated) {
      idbCon.openDb(dbname);
    } else {
      const tableDataBase = getTableDatabase();
      idbCon.createDb(tableDataBase);
    }
```

**Comment by jaymehtasa** [comment]
using v3.0.0

**Comment by ujjwalguptaofficial** [comment]
Hi Jay

createDb has been repalced with initDb with some other major changes in v3.0. You can take a look at for more info - https://medium.com/@ujjwalgupta_57939/whats-new-in-jsstore-v3-2c3501b3ae3f
