### ISSUE TITLE
Last Insert ID after insert operation

### ISSUE THREAD

**Issue by jaymehtasa** [ujjwalguptaofficial/JsStore#108]
Is there any way we can get `lastInsertId` after insert operation, currently it is returning number of rows inserted, but instead I am expecting `lastInsertId`.

**Comment by ujjwalguptaofficial** [comment]
Yeah there is :). You need to use return:true in your select query. 

```
connection.select({
    from: "Table_Name",
    return :true // this will return the all inserted data along with autoincrement values
})
```

**Comment by ujjwalguptaofficial** [comment]
Oho i see, its not there in docs :(. The whole time i was sure its there lol. I will add it asap.
