### ISSUE TITLE
Where not working for boolean values

### ISSUE THREAD

**Issue by usb248** [ujjwalguptaofficial/JsStore#11]
Hi,

I develop a web application with your library.
I have a bug. I can't do a where on a Boolean column.
![buggy](https://user-images.githubusercontent.com/7659927/32784286-ac7217d2-c94e-11e7-9603-ce21c449091c.png)

My code 
`c.select({
	From: "projets",
	Where: {
		pending:true
	}
});`

Table structure : 
```
...
{
	Name: "pending",
	DataType: 'boolean',
	Default : false,
	NotNull: false
}
...
```

Why ?
(I use v1.2.5, your lastest version (1.2.6) crash my application ... I get result on OnError callback instead Onsuccess ...)

**Comment by ujjwalguptaofficial** [comment]
Hey there - thanks for letting us know.

The issue is that data of type Boolean is not a valid key in indexeddb. please take a look for more - 

https://stackoverflow.com/questions/17676401/why-idbkeyrange-only-does-not-allow-boolean

https://stackoverflow.com/questions/13672906/indexeddb-boolean-index

so what you can do , you can store values in string and later parse it using Boolean function like this - `Boolean('true')`

**Comment by ujjwalguptaofficial** [comment]
You can save the Boolean data but querying data based on the value will create the problem.

About the v1.6 - thanks for letting us know about this problem.

**Comment by usb248** [comment]
Thanks for your report.
I have chosen number type for my colomn. I put 0 (for equivalent of false value) and 1 for inversely.
I think, it's a good compromise

**Comment by ujjwalguptaofficial** [comment]
yeah that should work too. 

I will fixed the issue with the latest version. This was the change for adding promise, something broke.

btw - now JsStore also support promise. so now you can write code like this.

```
var Connection = new JsStore.Instance("Demo");
Connection.select({
    From: "Customers",
    Where:{
        Country:'Mexico'
    }
}).
then(function(results){
   console.log(results)
}).
catch(function(err){
   console.error(err)
})
```

When you don't mention OnSuccess then a promise will be returned.

**Comment by usb248** [comment]
Nice ! I will change the syntax in the futur in order to work with promise :) Thx
