### ISSUE TITLE
type: table_not_exist

### ISSUE THREAD

**Issue by ersaurabh101** [ujjwalguptaofficial/JsStore#113]
Hello,

We are using jsstore with typescript [ionic]. I am using it in 3 to 4 of my apps, problem i am facing is -

**A and B are 2 users**

Please note, i have 2 pages in ionic, **where condition works fine in Page1  in case of both A and B**, **whereas in page 2**, where condition works fine for user "A" but **gives error for user "B"**

Why is it working fine in both pages of B and only 1 page for A.

Please help us, we are in a fix.

**Comment by ujjwalguptaofficial** [comment]
Hi Saurabh

let's talk on gitter.

**Comment by ujjwalguptaofficial** [comment]
After talking on gitter, i found  these issues- 

* jsstore api was being called from every side of the application. 
* application architecure is not good. 
* multiple instance of connection.
