### ISSUE TITLE
Please add a multi column order by option

### ISSUE THREAD

**Issue by Efke** [ujjwalguptaofficial/JsStore#114]

**Comment by ujjwalguptaofficial** [comment]
Added in new version - 3.2.0.

Here is an example - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Customers%22%2C%0A%20%20%20%20order%3A%20%7B%0A%20%20%20%20%20%20%20%20by%3A%20%27country%27%2C%0A%20%20%20%20%20%20%20%20type%3A%20%22desc%22%0A%20%20%20%20%7D%0A%7D)%3B%0A
