### ISSUE TITLE
SqlWeb Extension not available in service worker

### ISSUE THREAD

**Issue by jeffbradham** [ujjwalguptaofficial/JsStore#116]
I'm attempting to implement a client-side intercept of php calls in a pwa offline-enabled web site.  I am able to use JsStore in the service-worker's scope but when I try to call runSql so I can re-use as much of my sql-syntax as possible I get errors.  When enabling SqlWeb it references the "window" object, which is not visible in a service-worker.

Can you recommend a way to include the SqlWeb extension?

current code:
return Util.sqlWeb_ == null ? window['SqlWeb'] : Util.sqlWeb_;

Thank You
Jeff

**Comment by ujjwalguptaofficial** [comment]
fixed in v - 3.3.1 . It was due to the window object being used, i changed it to self.

**Comment by jeffbradham** [comment]
well, I can't tell for sure if it works or not because I'm having other issues with this update.  I had started this project with JsStore v3.0.0.  Jumping to v3.3.1 I'm not falling into situations where the db requests just pile up in the requestQueue without being processed.  In looking at some of the more recent changes it does look like there were changes related to this queue going into v3.3.1.  Do you know anything specific about this which might help me debug my situation?

Thanks
Jeff

**Comment by ujjwalguptaofficial** [comment]
Hi Jeff

Could you tell me - when its pilling up the queues like certain situations
or steps that would help me to debug. I didn't knew this was happening. If
you can create a small demo projects, where you can show me the issue
that would be great.

It is very strange, it passes all the test scenarios. Anyway, let me know.

Thanks,
Ujjwal

**Comment by jeffbradham** [comment]
Hi Ujjwal,

I'm working to try to isolate the scenario now.  I have proven that it has nothing to do with v3.3.1.  It fails with v3.0.0 for me as well.  I suspect that it has to do with the fact that I'm not creating an additional database in my scenario and attempting to switch between databases.

I'm very new to javascript and web design.  Can you explain the best approach to managing connections to multiple IndexedDb db's?  Should I be re-using the same JsStore instance and terminating/re-connecting?  Do you recommend a different instance for each db connection?

Thanks
Jeff

**Comment by ujjwalguptaofficial** [comment]
ok, i m relieved to know that there is no problem :). 

You can use two variable for multiple db's or one variable too - there is no hard rule. The difference is that - 
* you will have to open/close db manually when using one variable for connection while in muliple variable you wont have to
* more memory consuming in case of two variable but less in case of one variable.

So choice is yours.

Also if you are using service worker - make sure you open/close db manually always when doing something because service worker codes are not always active, they become active for some events only & for very less time.

**Comment by jeffbradham** [comment]
Thank you very very much for the help.  I believe that you hit the nail on the head with the service worker being the cause.  

So for db activity being done in the service worker would it be best if I made every action a closed loop?  In that I create a new JsStore.Instance / do stuff / and then terminate?

**Comment by ujjwalguptaofficial** [comment]
Yes, so to make sure - 
* create a jsstore instance
* initiate db
* do some stuffs (make sure you are not doing something which is taking very long, this might be headache to maintain cause in the mean time when something is in process, service worker might go to sleep)
* terminate

**Comment by jeffbradham** [comment]
Hi Ujjwal, I really want to express how thankful I am for your quick and effective responses.  I'm new to this world but I would be happy to help make a splash here so hopefully I will be able to help you push this technology forward.  I wanted to catch you up on my situation and also ask that if we should take this conversation to another medium please let me know.  Because we are obviously beyond this bug now but I want to keep your ear.  Here is what I think I have learned along the way that should be beneficial to you.

1. You cannot have table names with underscores or numbers in the name if you want to issue runSql queries to them.  The basic JsStore API commands for select, insert, update work, but it seems that the parsing for the sql-like interface breaks.
2. If you are going to attempt to open connections to more than one IndexedDb database, even if you use two different JsStore.Intance's they will collide if you do not create them with a WebWorker.  Which is what leaves me stuck at item 3
3. If you are going to use JsStore from a service worker listener you have to have a polyfill subworker solution in place....that I'm still working on now and is still very new to me.  So if this is something you know about I would appreciate the help.

I'm attempting to intercept a php call in the fetch event listener and instead call a local javascript function when I determine that I'm in offline mode.  So it would send the "sql" to the local IndexedDb instead of the server-side mysql.  This seems like the first and most natural use for these PWA apps....that is what lead us to this technology...but I have yet to see any basic example that exhibits that structure.

I hope this finds you well and I hope that my struggles can pay dividends for us both.

Jeff

**Comment by ujjwalguptaofficial** [comment]
Hi Jeff

It's all my pleasure & thanks to you buddy for listing out all the things you found so far. This would really help the people coming to this thread.

Let's take our conversation to gitter - https://gitter.im/JsStore/Lobby
