### ISSUE TITLE
BulkInsert not doing anything with large data sets

### ISSUE THREAD

**Issue by j0hnwhyte** [ujjwalguptaofficial/JsStore#117]
I upgraded from v2 to v3.3.1, and the bulk insert doesn't work properly. If I add all the ~8k records with 30 fields each in a single run, it finishes without giving any error, but the database is empty, while if I make smaller batches it works fine.

This is reproducible, but I can't share the example data unfortunately.

```
       await this._conn.bulkInsert({
         into: this._tableName,
         values: records,//.slice(9000),
       });

      // Batch insertion, bug in jsstore?
      for (let i = 0; i < records.length; i += 1000) {
        log.debug("Loading batch " + i / 1000 + "...");
        await this._conn.bulkInsert({
          into: this._tableName,
          values: records.slice(i, 1000),
        });
      }
```

**Comment by ujjwalguptaofficial** [comment]
ok john, i will try to reproduce this.

For the time please use insert api with skipDataCheck:true, it will give you similar performance.

**Comment by ujjwalguptaofficial** [comment]
@j0hnwhyte - bulkInsert does not check for errors when inserting data. I am feeling - its not good for real time application, so i am going to remove this.

**Comment by ujjwalguptaofficial** [comment]
removed bulk insert in v - 3.4.0. Please use insert api with skipDataCheck : true for faster insert operation.

**Comment by kunalbathla** [comment]
Hi I am using 3.4.0 version and I am trying with 15k data with around 30fields and it's taking more than 20 seconds to insert.
I am already using skipDataCheck.
Is there any other to optimise this.
Thanks

**Comment by ujjwalguptaofficial** [comment]
Nope, there is no other option. I think - for client side inserting 15k data within 20 second is not much time.
