### ISSUE TITLE
Unable to use transaction in angular code

### ISSUE THREAD

**Issue by harsh1it** [ujjwalguptaofficial/JsStore#118]
When we try to use transaction within angular code, it throws following error. This gets thrown even before anything within logic() gets executed. We are using Angular 5.
`Error ReferenceError: __awaiter is not defined
    at Instance.txLogic (eval at Instance.startExecution_ (scripts.bundle.js:85578), <anonymous>:2:17)
    at Instance.startExecution_ (scripts.bundle.js:85578)
    at scripts.bundle.js:85578
    at ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:4015)
    at ZoneDelegate.invoke (zone.js:390)
    at Zone.run (zone.js:150)
    at eval (zone.js:889)
    at ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:4006)`

**Comment by ujjwalguptaofficial** [comment]
Hi @harsh1it 

The issue is there because your code is being converted into es5 & when it is converted - async code is wrapped with awaiter but when its being sent to web worker its not there.

So the solution is to remove async & use promise.

**Comment by ujjwalguptaofficial** [comment]
If you don't want to change anything, then you will have to execute jsstore without web worker when using transaction.

transaction api contains logic which is passed to web worker for execution but passing of function is not allowed in web worker & that's why we need to convert it into string & then it is passed. But in the process you loose all your local scoping.

Check out the latest doc - https://jsstore.net/tutorial/transaction/

**Comment by harsh1it** [comment]
@ujjwalguptaofficial Thanks for your help.
We tried to remove async as you have suggested, but that doesn't allow us to use `start()` function - might be related to current scope. If you have any code sample, that will be helpful.

**Comment by ujjwalguptaofficial** [comment]
Here is one of example from our test case - https://github.com/ujjwalguptaofficial/JsStore/blob/e807eb6f00ad6c40f735112f5b63a8e61e88b010/test/cases/transaction/main.js#L2

**Comment by The-MAZZTer** [comment]
I have run into a related issue using jsstore in a Chrome extension. By default Chrome will not allow the use of eval() and it is strongly discouraged to enable it as it is considered unsafe.

A workaround is to use jsstore without web workers.

I would recommend an alternative solution be considered: allow the user to create a separate JS file with the transaction function in it. The path to this file could be passed to the web worker instead, which would load it with `importScripts()` and then call a specified (or hardcoded) function name to run the transaction logic.

**Comment by ujjwalguptaofficial** [comment]
@The-MAZZTer good suggestion :), thanks. It will give more control to users and help us get rid of eval.

**Comment by ujjwalguptaofficial** [comment]
as suggested by @The-MAZZTer , in order to use  transaction api -  you first need to importScript and then call transaction api with the method name. Take a look at - https://jsstore.net/tutorial/transaction/
