### ISSUE TITLE
access security control

### ISSUE THREAD

**Issue by f5cs** [ujjwalguptaofficial/JsStore#119]
store data in indexeddb,very easy to cause XSS attacks。
Can we consider some security controls?

I have some ideas:
Step 1: Using module to define an indexeddb that can only be accessed internally
Step 2: Delete window. indexeddb to prevent external scripts from accessing indexeddb
Step 3: Initialize a white list of SQL maps with const, only allow jsstore to execute SQL + params of these white lists;

eg:
step1:
    <script type="module">
        import dbcon from "var%20dbapi%20=%20window.indexedDB;%0Aconst%20sqlWhiteList=%7B%0A%20%20%20%20storeQuery:%7B...%7D,%0A%20%20%20%20storeAdd:%7B...%7D,%0A%20%20%20%20storeUpdate:%7B...%7D,%0A%20%20%20%20storeDelete:%7B...%7D%0A%7D;%0Afunction%20genSql(sqlName,params)%7B%0A%20%20%20%20...%0A%7D%0Aexport%20default%20function%20async%20exeSql(sqlName,params)%7B%0A%20%20%20%20if(!sqlWhiteList%5BsqlName%5D)%7B%0A%20%20%20%20%20%20%20%20return;%0A%20%20%20%20%7D%0A%20%20%20%20var%20sql%20=%20genSql(sqlName,params);%0A%20%20%20%20await%20rs%20=%20connection%5Bsql%5D;%0A%7D";
        **### delete window.indexedDB;**
        var rs = dbcon.exe(sqlName,params);
    </script>

After such processing, the external script can not access indexeddb, and can not arbitrarily exceptional SQL statements. We can ensure the security of indexeddb to a large extent by ensuring that params do not have problems.

The original code for the first step is,In the import above, I encoded it.
var dbapi = window.indexedDB;
const sqlWhiteList={
    storeQuery:{...},
    storeAdd:{...},
    storeUpdate:{...},
    storeDelete:{...}
};
function genSql(sqlName,params){
    ...
}
export default function async exeSql(sqlName,params){
    if(!sqlWhiteList[sqlName]){
        return;
    }
    var sql = genSql(sqlName,params);
    var rs = await connection[sql];
    return rs;
}

**Comment by ujjwalguptaofficial** [comment]
Hi

JsStore is client side library. So if someone has access to your client through a script or whatever they can write indexeddb native code to do something.

> it's like if someone has injected a script to to your application - they can access localStorage, cookie(if allowed) etc. So as per my understanding - you need to do server side validation for saiving yourself from xss attacks or sql injection.

Let me know what you think.

**Comment by f5cs** [comment]
1、delete window.indexedDB, then can't use indexeddb native api directly.

2、before the step 1, do the follow:
      write a  js file   enclosure.js,the content:
      `var indexdbApi = window.indexedDB;export default function async exeSql(sqlName,params){
              indexdbApi.open('')
      }`

     in the jsstore file,
  `   <script type="module">
         var indexedDbHandler = window.indexedDB;
         delete window.indexedDB;
   </script>`

**Comment by ujjwalguptaofficial** [comment]
Even though you are blocking native apis and restricting someone, you need to actualy save yourself from xss attacks at server side, because anyone can call your apis with bad data which means writing xss validation code in server side. 

So there is no use of doing this. But you have a valid point though.

So i will suggest to do these things - 

* Use different type of technique to make sure no script can be injected in your website.
* Do xss validation in your server side.
