### ISSUE TITLE
Where Clause Not Working

### ISSUE THREAD

**Issue by chagamama** [ujjwalguptaofficial/JsStore#12]
I have tried everything, and am getting no errors but whenever I try to execute a select with a where clause it returns an empty array. Here is the code I have:
`initJsStore();
JSConn.select({
From: 'reports',
Where: {
report_id : '130'
},
OnSuccess:function (results){
//results will be array of objects.
alert('res' + results);
console.log(results);
showit(results);
},
OnError:function (error) {
alert(error.value);
}
`});``

it returns in console
[]length: 0__proto__: Array(0)

remove the where to this: 
`			initJsStore();
JSConn.select({
From: 'reports',
OnSuccess:function (results){
//results will be array of objects.
alert('res ' + results);
console.log(results);
showit(results);
},
OnError:function (error) {
alert(error.value);
}
});

`

 and it returns 
["{"report_id":"130","device_id":"","show_report":"y…"","street2":null,"city":"","state":"","zip":""} "]
0
:
"{"report_id":"130","device_id":"","show_report":"yes","published":"no","published_date":null,"user_id":"30","client_id":"128","template_id":"19","template_name":"Default Template","employee_id":"29","inspection_date":"2017-11-18","end_date":null,"access_key":"d3ea87ea15de478eab26901d800f1587490eb2a4","creation_date":"2017-11-15 14:52:54","updated":"November 15&comma; 2017 at 8&colon;40&colon;09 PM ","report_name":"bjjh","last_name":"cc","first_name":"mark","street":"","street2":null,"city":"","state":"","zip":""} "
length
:
1
__proto__
:
Array(0)

this is currently the only entry but obviously it returns all the rows from the table reports in the database when all i want is that one, ie. a Where clause. But for some reason it's not working.  
I have tried everything, and am getting no errors but whenever I try to execute a select with a where clause it returns an empty array, every time, *note this is running on phonegap.

**Comment by ujjwalguptaofficial** [comment]
Hi there - I think report_id is stored as a number and you are giving string value in where clause. Use datatype for the columns to get rid of these type of situations.

You are doing -

`
Where: {
  report_id: '130'
}
`

It should be -

`
Where:{
  report_id:130
}
`
Let me know if issue is not solved.

**Comment by ujjwalguptaofficial** [comment]
I am just guessing that - this may be the situation. Let me know if issue is something else.

**Comment by chagamama** [comment]
Hi I figured it out it was actually an issue while inserting the data, I had it incorrectly formatted. I had to JSON.parse() on my xhr results first, I had it applied to all other tables, which were working, but overlooked it on that request.

**Comment by ujjwalguptaofficial** [comment]
ok cool. closing the issue.
