### ISSUE TITLE
Many-Single join error

### ISSUE THREAD

**Issue by olintononthemovesw** [ujjwalguptaofficial/JsStore#121]
When performing a join, where many records in the primary table are linked to a single secondary table, there is an error with the returned data when the 'as' control is applied.
Example (https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo)

```
select({
    from: "Orders",
    join: {
        with: "Shippers",
        on: "Shippers.shipperId = Orders.shipperId"
    }
});
```

will successfully return all of the records.

```
select({
    from: "Orders",
    join: {
        with: "Shippers",
        on: "Shippers.shipperId = Orders.shipperId",
        as: {
            shipperId: "Shippers.shipperId",
            shipperName: "Shippers.shipperName",
            phone: "Shippers.phone"
        }
    }
});
```

will return the same records, **however, the joined columns are returned as undefined** (except for the first record of each join)

![image](https://user-images.githubusercontent.com/54812461/64190323-0826dd80-ce6e-11e9-9db1-4f8d96f78e05.png)

**Comment by olintononthemovesw** [comment]
Thank you in advanced.

**Comment by ujjwalguptaofficial** [comment]
@olintononthemovesw  - thank you very much for finding this issue. This was a tricky one.

I have fixed this issue in v - 3.3.4 . Please test and let me know.

**Comment by ujjwalguptaofficial** [comment]
BTW - this was happening due to object reference.

**Comment by ujjwalguptaofficial** [comment]
Here is idbstudio link - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Orders%22%2C%0A%20%20%20%20join%3A%20%7B%0A%20%20%20%20%20%20%20%20with%3A%20%22Shippers%22%2C%0A%20%20%20%20%20%20%20%20on%3A%20%22Shippers.shipperId%20%3D%20Orders.shipperId%22%2C%0A%20%20%20%20%20%20%20%20as%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20shipperId%3A%20%22Shippers.shipperId%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20shipperName%3A%20%22Shippers.shipperName%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20phone%3A%20%22Shippers.phone%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)%3B

**Comment by olintononthemovesw** [comment]
It's passing our tests now also.
Thank you for the speedy fix, especially since it wasn't a simple little bug!
