### ISSUE TITLE
OrderBy & Join

### ISSUE THREAD

**Issue by olintononthemovesw** [ujjwalguptaofficial/JsStore#129]
When applying the 'orderBy' control and a 'join' control at the same time JsStore throws errors...
Steps to reproduce: (https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo)
```
select({
    from: "Orders",
    order: {
        by: 'customerId',
        type: "desc"
    }
});
```
Successfully returns 196 records, with the correct ordering
![image](https://user-images.githubusercontent.com/54812461/64694033-9d3e5d80-d490-11e9-80b6-e26029b7df0a.png)
```
select({
    from: "Orders",
    join: [{
        with: "Shippers",
        on: "Shippers.shipperId = Orders.shipperId"
    }]
});
```
Successfully returns 196 records, with the correct join
![image](https://user-images.githubusercontent.com/54812461/64694078-bc3cef80-d490-11e9-9298-4d75030a719e.png)
```
select({
    from: "Orders",
    order: {
        by: 'customerId',
        type: "desc"
    },
    join: [{
        with: "Shippers",
        on: "Shippers.shipperId = Orders.shipperId"
    }]
});
```
Throws an error
![image](https://user-images.githubusercontent.com/54812461/64694100-cced6580-d490-11e9-97ab-86333459dfd6.png)

**Comment by ujjwalguptaofficial** [comment]
You need to specify tableName for the order column when doing join. Check out the below query - 
https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Orders%22%2C%0A%20%20%20%20order%3A%20%7B%0A%20%20%20%20%20%20%20%20by%3A%20'Shippers.shipperId'%2C%0A%20%20%20%20%20%20%20%20type%3A%20%22desc%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20join%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20with%3A%20%22Shippers%22%2C%0A%20%20%20%20%20%20%20%20on%3A%20%22Shippers.shipperId%20%3D%20Orders.shipperId%22%0A%20%20%20%20%7D%5D%0A%7D)%3B

**Comment by olintononthemovesw** [comment]
Good spot. Thank you
