### ISSUE TITLE
need example for syncing offline data with server

### ISSUE THREAD

**Issue by sachin0606** [ujjwalguptaofficial/JsStore#13]
Please provide any example to use api sync for offline sync data.

**Comment by ujjwalguptaofficial** [comment]
apis are by default synchronous in JsStore.

Here is a example to test this - you call two apis - insert first and after that select. So first insert will be executed and after that select . Baiscally call to apis will be executed in the same order as they are called one after one.

**Comment by sachin0606** [comment]
how to get the offline mofied data [changed data] from jsstroe. and send to server to update the data.

**Comment by ujjwalguptaofficial** [comment]
You can use jsstore select api to get the data. 

Are you asking something else ? it will be better if you will tell the situation.

**Comment by ujjwalguptaofficial** [comment]
About sending data to server - you can send it when you are online.  So you need to check it whether user is online or offline. So if user is online then sync with server and if offline save the data in jsstore.

here is doc for checking online and offline - https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events

**Comment by ujjwalguptaofficial** [comment]
I will create a demo for this.

**Comment by sachin0606** [comment]
My Scenario is to get the changed data while offline and send it to server and get the data from server which is updated while the device is offline. 

indirect offline sync.

**Comment by mjgr0013** [comment]
This requirement is for something like a chat?

**Comment by ujjwalguptaofficial** [comment]
User logged in, some data is downloaded and saved into indexeddb. The process continues and when the user goes offline , the data is saved or updated into indexeddb. Now this data needs to be sent to server or sync data with server when user comes online.

This will be a use case of above scenario.

**Comment by sachin0606** [comment]
yes. exactly.

**Comment by udaychy** [comment]
Hi @sachin0606, Here is a [Chat room demo](https://github.com/udaychy/ChatRoomDemo) made using Jsstore.
Have a look and i guess you will the get the idea for your query and the code as well.

**Comment by ujjwalguptaofficial** [comment]
@sachin0606 - Are we good here. Please let me know.

Thanks

**Comment by ujjwalguptaofficial** [comment]
Hope above solutions is working for you , if not let me know. Closing the issue for now, feel free to reopen.

Thanks
