### ISSUE TITLE
Like is not working as spected

### ISSUE THREAD

**Issue by leandro2219** [ujjwalguptaofficial/JsStore#133]
Like is not working as spected

Hi,
I am trying to use the operator Like but is not working, I don't know if there is anything missing on my side or the query i wrong. 

**Table:**
var tblCatalog = {
        name: 'Catalog',
        columns: {
            type :  {notNull : true, dataType : "number"},
            type_id :  {notNull : true, dataType : "string"},
            type_name :  {notNull : true, dataType : "string"},
            extra : {dataType : "number"},
            idType : {keyPath : ['type']}
        }
    };

I have about 50.000 rows on this table. Some tested values:

**Some Rows (only the type_name column):**
BULK/DRY
MARKETING SVCS
DAIRY

**This is my query:**
var results = await connection.select({
        from : "Catalog",
        ignoreCase: true, 
        where : {
            type : cId, 
            type_name : {like : '%'+q+'%'}
        }, 
        limit : 200
    });
Where q is a variable get from an input. Some output example:

q = B: return BULK/DRY (this is ok)
q = Y: return BULK/DRY (is ok but not returns DAIRY)
q = D: return BULK/DRY (is ok but not returns DAIRY)
q = D: return nothing (the MARKETING SVCS has S)

It seems that only check the first one and no more. Any clue about this?

Thanks.

**Comment by ujjwalguptaofficial** [comment]
Hi

It might be that your type value does not contains that value. You are runing and query on two columns : type & type_name.

The sql query will be - select * from Catalog where type="Cid" && type_name like 'some_value'

So type_name will be only filtered after the first option type satisfies. You might be looking for [or](http://jsstore.net/tutorial/or/) query.

Let me know, if that's the case otherwise please share a small demo with data. You can talk to me on gitter & share the demo if you don't want your data to make public.

**Comment by leandro2219** [comment]
Hi, all that data has the same type (type = 1). 

This is a set of that rows (filtering by type = 1):
0: {type: 1, type_id: "1", type_name: "BULK/DRY"}
1: {type: 1, type_id: "10", type_name: "MARKETING SVCS"}
2: {type: 1, type_id: "126", type_name: "LOGISTIC SVCS"}
3: {type: 1, type_id: "2", type_name: "CANNED"}
4: {type: 1, type_id: "24", type_name: "PREPARED FOODS"}
5: {type: 1, type_id: "3", type_name: "DAIRY"}
6: {type: 1, type_id: "4", type_name: "FRUIT & VEG"}
7: {type: 1, type_id: "5", type_name: "MEAT"}
8: {type: 1, type_id: "6", type_name: "NON FOOD"}
9: {type: 1, type_id: "7", type_name: "POULTRY"}
10: {type: 1, type_id: "8", type_name: "PORK"}
11: {type: 1, type_id: "9", type_name: "SEAFOOD"}

Any clue about this? Thanks.

**Comment by ujjwalguptaofficial** [comment]
then it should work, what version you are using @leandro2219 ?

**Comment by leandro2219** [comment]
I am using the latest one, https://cdn.jsdelivr.net/npm/jsstore/dist/jsstore.min.js, (V3.4.1). I will test again but with less data and let you know.

**Comment by ujjwalguptaofficial** [comment]
Ok, i am able to reproduce the issue with your data. Will fix the issue soon.

**Comment by leandro2219** [comment]
Perfect. I tested with some mera data and the problem is when I filter by type and type_name. If I only filter using type or type_name works ok, but together is not working. Let me know If you need anything else from my side so I can help. Thanks.

**Comment by ujjwalguptaofficial** [comment]
Issue fixed in v- 3.4.2. Please check and let me know.

**Comment by leandro2219** [comment]
Perfect!! Now is working, thanks for all.
