### ISSUE TITLE
Tasks overhead

### ISSUE THREAD

**Issue by olintononthemovesw** [ujjwalguptaofficial/JsStore#135]
Tasks Overhead

We have been running performance testing on our JsStore queries recently. We've notices that there is quite a significant overhead wasted on creating and destroying Tasks.

![image](https://user-images.githubusercontent.com/54812461/67396188-0c829380-f59f-11e9-8fd4-ead0912a57c3.png)
![image](https://user-images.githubusercontent.com/54812461/67394596-6170da80-f59c-11e9-87a7-19d9e82d353e.png)
![image](https://user-images.githubusercontent.com/54812461/67396106-eeb52e80-f59e-11e9-99ce-96fb2282d3c9.png)

You can see that the actual function call time is reasonably small. Generally it is not a good practice creating an entire Task/Threat for a single functional operation.

I like that JsStore implements Tasks. However, for performance reasons, function calls should be grouped together into a single Task (rather than a Task per function).

Regards,

Osian

**Comment by olintononthemovesw** [comment]
This data can be found by opening the developer tools (we used google chrome) and selecting the Performance tab. Start recording, then execute some data retrieval using JsStore (the more complicated the better), and stop recording once the result has arrived.

![image](https://user-images.githubusercontent.com/54812461/67395019-23c08180-f59d-11e9-8aad-601026f39263.png)

**Comment by ujjwalguptaofficial** [comment]
We dont use Task api but promise only. Not sure how you are getting task :thinking: 

I will look into the performance thing & will share the screenshot here

**Comment by ujjwalguptaofficial** [comment]
BTW - you can use our idbstudio app for performance testing and share the results publically. Here is the link - https://ujjwalguptaofficial.github.io/idbstudio/

Thanks

**Comment by olintononthemovesw** [comment]
Tasks are automatically setup when a new global execution context is made.
The performance degredation is more easily seen when there are 1000+ records in the tables.

**Comment by ujjwalguptaofficial** [comment]
What "global execution context" ? Could you point me to some article ? 

I am sorry but i am not able to understand what you are saying. As for what you have suggested - we are already using promise api.

Thanks

**Comment by olintononthemovesw** [comment]
this explains it nicely:
https://www.valentinog.com/blog/context/
or this:
https://hackernoon.com/execution-context-in-javascript-319dd72e8e2c

essentially, all of the code needs to be kept inside a single 'global' function, while everything else is kept 'in memory' (or added as a dependancy at the very biginning of the global function call)

**Comment by ujjwalguptaofficial** [comment]
@olintononthemovesw since JsStore is a library its already inside a global function, you cant access JsStore code outside JsStore without calling JsStore.

**Comment by olintononthemovesw** [comment]
Looks like this problem is actually caused by the base IndexedDb implementation of their Cursor...

Thank you for being an active repository!
