### ISSUE TITLE
如何在页面刷新的时候删除数据库？谢谢

### ISSUE THREAD

**Issue by HuDaHei** [ujjwalguptaofficial/JsStore#136]
# Title // Add your title here

# Description // Add your description here

Note: Description should contains the query, the current output & the expected output. You can use idbstudio to generate the example.

**Comment by ujjwalguptaofficial** [comment]
What's this issue @HuDaHei . Please don't pollute the issue section, if you have some issue please edit this and make sure its readable.

Thanks
