### ISSUE TITLE
Using same column in set and where while updating.

### ISSUE THREAD

**Issue by btk** [ujjwalguptaofficial/JsStore#145]
# Title

Using same column in set and where while updating

# Description

Unable to use `productId` in the same query for set and where properties.

```
update({
    in: "Products",
    set: {
        productId: {
            '*': 5
        }
    },
    where: {
        productId: {
            '>=': 60
        }
    }
});
```

My goal for this command is to update the productId values of all products that has 60+ productId's to their own id's times 5.

Here is the sql version of what I'm trying to achieve;

`UPDATE Products set productId = productId+1 WHERE productId >= 60;`

This seems like a useless example, but bare with me, it could have been something like, adding +$10 for all items' prices in the database which has $100 and more prices.

Note: Description should contains the query, the current output & the expected output. You can use idbstudio to generate the example.

IDBstudio link:
https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=update(%7B%0A%20%20%20%20in%3A%20%22Products%22%2C%0A%20%20%20%20set%3A%20%7B%0A%20%20%20%20%20%20%20%20productId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20'*'%3A%205%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20productId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20'%3E%3D'%3A%2060%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)%3B

Is this an indexedDb limitation, or can we be able to implement this, or is there any recommentations how I can manage this on my end?

**Comment by ujjwalguptaofficial** [comment]
Yes you can do but in your example `productId` is primary key which mean you can't mutate it. Try with other columns - 

I tried with price & it worked - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=update(%7B%0A%20%20%20%20in%3A%20%22Products%22%2C%0A%20%20%20%20set%3A%20%7B%0A%20%20%20%20%20%20%20%20price%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20'*'%3A%205%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20productId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20'%3E%3D'%3A%2060%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)%3B

**Comment by btk** [comment]
Hey @ujjwalguptaofficial thank you for getting back so fast, productId was an example, I think this query makes it more understandable, what my problem was;

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=update(%7B%0A%20%20%20%20in%3A%20%22Products%22%2C%0A%20%20%20%20set%3A%20%7B%0A%20%20%20%20%20%20%20%20price%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20'*'%3A%205%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20price%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20'%3E%3D'%3A%2020%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)%3B

It takes like 6 seconds, my guess is that it recursively updates the records that had been multiplied.

Sorry for not making it more clear, also thank you for building this interface, it is really easy to test things out & see performance metrics.

**Comment by ujjwalguptaofficial** [comment]
Yes it does recursively, but it shouldn't take that much time but

> Again in your example - you are querying on field price & updating the price , so it is becoming kinda of infinite loop, since price is always increasing & indexeddb finds new data always. Its updating 16729 records (see the result section) but products table has only 77 record.

![Screenshot from 2019-11-08 08-16-13](https://user-images.githubusercontent.com/10938615/68445509-21e2f900-0200-11ea-9410-5dc009e248e3.png)

For this case - I will recommend to fetch data and then do a in query

e.g - 

```
const products = await select({
    from: 'Products',
    where: {
        price: {
            '>=': 20
        }
    }
})

update({
    in: "Products",
    set: {
        price: {
            '*': 5
        }
    },
    where: {
        id: {
            'in': products.filter(q => q.id)
        }
    }
});
```

Let me know if it's not making sense. But its a good situation where thing might go wrong.

And i am really glad :) to know that you used idbstudio for performance metrics & debugging, the sole purpose of creating idbstudio was only this. Hope you will help & encourage others to use indexeddb studio.

Thanks

**Comment by btk** [comment]
Makes sense, thank you for your help!
