### ISSUE TITLE
sg.Instance is not a constructor

### ISSUE THREAD

**Issue by MY020537** [ujjwalguptaofficial/JsStore#146]
Implemented with electron js it prompts with "sg.Instance is not a constructor" .  Crash point is at line
new JsStore.Instance(new Worker(workerPath));  while initializing instance. 

Dev environment it works fine but after publishing electron app it creates such issue. 
Any recommendation to solve this ?

**Comment by ujjwalguptaofficial** [comment]
Somehow the production build is removing jsstore. Enable the development tool for your production build and log everything.
