### ISSUE TITLE
SELECT columns

### ISSUE THREAD

**Issue by ijcurtis** [ujjwalguptaofficial/JsStore#15]
Is it possible to specify columns in a SELECT statement - the examples only appear to be SELECT *

**Comment by ujjwalguptaofficial** [comment]
IndexedDB is no sql database. It stores the data in form of objects associated with a key and when querying - it returns the whole data. JsStore returns the same data as indexedDB. It is poosible to give the result like relational database but manipulating it will take some time and resources. So it is better to return data as it comes.

**Comment by ijcurtis** [comment]
Thanks, I guessed that would be the answer, I will have to look at a different solution for my particular user case

**Comment by ujjwalguptaofficial** [comment]
You can remove some properties from object or you can create another object from result .

This will be a way to achieve the solution.
