### ISSUE TITLE
groupBy and aggregate

### ISSUE THREAD

**Issue by amberdiehl** [ujjwalguptaofficial/JsStore#151]
groupBy and aggregate

I am looking at your examples and am not seeing how to get summarized counts for items. This is what I'm providing connection.select:
```
var SQL_STATUS_COUNT = {
    from: "Inspection",
    groupBy: 'status',
    aggregate: {
        count: 'status'
    }
};
```
I am looking for output something like this:
[{'PENDING': 3}, {'REJECTED': 2}]

I am getting back an array, but with just one item regardless how many records are in the table and it's the full object rather than a count.

Thanks in advance.
AD

**Comment by ujjwalguptaofficial** [comment]
Hi 

Check out this example - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20'Products'%2C%0A%20%20%20%20groupBy%3A%20'categoryId'%2C%0A%20%20%20%20aggregate%3A%20%7B%0A%20%20%20%20%20%20%20%20count%3A%20%22categoryId%22%0A%20%20%20%20%7D%0A%7D)

In result - you will get array of objects but with extra property from your aggregare query. So in your case it should be - `count(status)` in each row.

Let me know if you have any question.

**Comment by amberdiehl** [comment]
Ahh, I see. I noticed you have that site with examples before. Should have thought to check it out. **Thank you** for your time and quick response!
