### ISSUE TITLE
count function has  a serious bug

### ISSUE THREAD

**Issue by f5cs** [ujjwalguptaofficial/JsStore#153]
# count function has  a serious bug

# Description

const results = await connection.count({
    from: "Table_Name",
    where: {
        Column1: some_value,   //only the Column1 has work
        Column2: some_another_value   **//the column2 can't work!** 
    }
});

**Comment by ujjwalguptaofficial** [comment]
@f5cs the issue is fixed in new version - 3.7.3. Please check and let me know.

**Comment by HongliangQiu** [comment]
The bug still exists!

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=count(%7B%0A%20%20%20%20from%3A%20%22Customers%22%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20customerId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22%3E%3D%22%3A%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22%3C%3D%22%3A%205%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)

![image](https://github.com/ujjwalguptaofficial/JsStore/assets/33348833/27acd815-5a44-472d-bf05-df03c7c91bb1)
