### ISSUE TITLE
'NOT LIKE' query or 'NOT' condition 

### ISSUE THREAD

**Issue by stanislav-grin** [ujjwalguptaofficial/JsStore#155]
# 'NOT LIKE' query with AND for one column

Hi there,
I searched in the documentation and among other issues, but it seems that I haven’t found any mention of how to make a `NOT LIKE` query.

Suppose we'd like to find all records where column `country` does not starts contain `Germ` entry.
SQL query is the following: 
`Select * from Customers where country NOT LIKE '%Germ%' AND country NOT LIKE '%Swed%'`

I guess it could look like this: 
```
select({
    from: "Customers",
    where: {
        country: {
           notLike: '%Germ%'
           and: {
              country: {
                notLike: '%Swed%',
                // and ... (continue if needed)
              }
           }
        }
    }
});
```
I know that there is no 'notLike', but is there some alternatives to perform such query?
Does it make sense to add a 'NOT' (`!`) statement? Like: 
`Select * from Customers where !(country LIKE '%Germ%' OR country LIKE '%Swed%')`

or:
```
select({
    from: "Customers",
    where: {
        '!': {
            country: {
                like: '%Germ%'
            },
            or: {
                country: {
                    like: '%Swed%'
                }
            }
        }
    }
});
```

Сountries are just an example, in reality there will be other data, but I'm interested in the approach itself.

Thanks!

**Comment by ujjwalguptaofficial** [comment]
Hi @stanislav-grin 

In these cases you can use regex. Here is link to regex doc - https://jsstore.net/tutorial/regex/

**Comment by stanislav-grin** [comment]
Thanks for the help, @ujjwalguptaofficial. 
Closing this issue.
