### ISSUE TITLE
IgnoreCase throws error when where clause has numeric values

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [ujjwalguptaofficial/JsStore#157]
# IgnoreCase throws error when Where In clause has numeric values

# Description 
I'm trying to query table with two where clauses one of them has numeric values. I want to ignore case of string column, but it also checks where numeric column which throws below error
`ERROR Error: Uncaught (in promise): Object: {"message":"subWord.charAt is not a function","type":"invalid_query"}`

# Steps to reproduce (Using [IDBStudio](https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0D%0A%20%20%20%20from%3A%20%22Categories%22%2C%0D%0A%20%20%20%20ignoreCase%3A%20true%2C%0D%0A%20%20%20%20where%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20categoryId%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20in%3A%20%5B5%2C%206%2C%207%5D%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20categoryName%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20like%3A%20'C%25'%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B))
```
select({
    from: "Categories",
    ignoreCase: true,
    where: {
        categoryId: {
            in: [5, 6, 7]
        },
        categoryName:{
            like: 'C%'
        }
    }
});
```
**Other issue with `IgnoreCase = true`**
When numbers are stored as string, the result set gives duplicate elements.

**Comment by ujjwalguptaofficial** [comment]
@Suroor-Ahmmad not able to understand second issue, please add another issue with all description.

**Comment by ujjwalguptaofficial** [comment]
@Suroor-Ahmmad issue is fixed in new version - v 3.7.4 . Please check and confirm.

**Comment by ujjwalguptaofficial** [comment]
i found another issue while fixing this bug & have fixed this in new version - 3.7.6.

**Comment by Suroor-Ahmmad** [comment]
Thank you. :+1: 
Can you explain what's that new issue? was that related to `in` ? The second issue what I mentioned was, if the numbers are stored as string and if I do `where:in{}` operation on that column, the result gives duplicates. I cant reproduce this using IDBStudio because I didn't find any column having number stored as string

**Comment by ujjwalguptaofficial** [comment]
yes it was related to in, query from one columns were being copied to another column. I found this when i put test cases for multiple columns.
