### ISSUE TITLE
how to use it in webpack

### ISSUE THREAD

**Issue by dejavuwow** [ujjwalguptaofficial/JsStore#16]
import it  like this :  import  JsStore  from "jsstore".

it dosen't work :(

how to import it as  a module.

**Comment by ujjwalguptaofficial** [comment]
You can use [externals ](https://webpack.js.org/configuration/externals/)for this. I will share a code tomorrow.

**Comment by ujjwalguptaofficial** [comment]
Here is the code for setup jsstore with webpack - https://gist.github.com/ujjwalguptaofficial/d0289a52e1dc5175a157975b0c5fc1e5.

**Comment by BrieucP** [comment]
It would be nice to be able to use it not as an external

**Comment by ujjwalguptaofficial** [comment]
@BrieucP - yes that's right. I will look into it, if we can do this and let you know.

Thanks

**Comment by ujjwalguptaofficial** [comment]
@dejavuwow , @BrieucP  - Now you can build using webpack or any other bundling tools. The issue has been resolved in jsstore v2. Please take a look at examples in examples folder - https://github.com/ujjwalguptaofficial/JsStore/tree/master/examples/

Thanks
