### ISSUE TITLE
Where clause with skip and limit returns wrong rows

### ISSUE THREAD

**Issue by altzan** [ujjwalguptaofficial/JsStore#166]
Hi, congratulations for your excellent job on JsStore. I'm facing a problem with a query that contains a complex "WHERE" clause in addition to "skip" and "limit" options. More specifically when the "WHERE" is of type array, "skip" and "limit" do not seem to work as expected and return wrong rows.

Here is an [example](https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Customers%22%2C%0A%20%20%20%20where%3A%5B%7B%0A%20%20%20%20%20%20%20%20country%3A'Mexico'%7D%2C%0A%20%20%20%20%20%20%20%20%7Bor%3A%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20country%3A'UK'%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%5D%2C%0A%20%20%20%20skip%3A%202%2C%0A%20%20%20%20limit%20%3A%202%0A%7D)%3B%0A)

The query should return the rows with customerId 4 and 11, but instead returns rows with customerId 13,16,19,58.

If the query is used in conjuction with an "order by" clause in "customerId" column the problem does not occur anymore.

Adding an "order by" in "customerId" adds a 5-10X overhead though in my app and I'm trying to avoid it.

Thank you for your help!

**Comment by ujjwalguptaofficial** [comment]
fixed in new version - 3.7.7. Please test and confirm.

**Comment by altzan** [comment]
Yes it has been fixed! Thank you!
