### ISSUE TITLE
Ignore Case unable to query result when there is join table

### ISSUE THREAD

**Issue by tanjooxiang** [ujjwalguptaofficial/JsStore#167]
Ignore Case unable to query result when there is join table

Hello, 
I trying to query result from a join table with where clause but it does not seem to be working well with ignoreCase. I want country where clause to be able to search case insensitive. 
 Below are the example using IDBstudio Demo database.  May i know if there is a work around or I'm just doing it the wrong way?

Not working with join table
`select({
    from: "Customers",
    ignoreCase:true,
    where:{
        country: "mexico"
    },
    join: {
        with: 'Orders',
        on: 'Customers.customerId=Orders.customerId',
        type: 'left'
    }
});
`

Working without join table
`select({
    from: "Customers",
    ignoreCase:true,
    where:{
        country: "mexico"
    }
});
`

Thank you.

**Comment by ujjwalguptaofficial** [comment]
@tanjooxiang ignoreCase wan not implemented for join condition. I have added this in new version - 3.8.0.  Here is idbstudio link for fix - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Customers%22%2C%0A%20%20%20%20ignoreCase%3A%20true%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20country%3A%20%22mexico%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20join%3A%20%7B%0A%20%20%20%20%20%20%20%20with%3A%20'Orders'%2C%0A%20%20%20%20%20%20%20%20on%3A%20'Customers.customerId%3DOrders.customerId'%2C%0A%20%20%20%20%20%20%20%20type%3A%20'left'%0A%20%20%20%20%7D%0A%7D)%3B

Please check and let me know.

**Comment by tanjooxiang** [comment]
Hello,

Yup. that what im looking for.  Will wait for your new release! 

thank you.

**Comment by ujjwalguptaofficial** [comment]
@tanjooxiang already released as v - 3.8.0.
