### ISSUE TITLE
keyPath incompatible with OR logic

### ISSUE THREAD

**Issue by MerlinB** [ujjwalguptaofficial/JsStore#168]
Given a query like this:
```js
db.select({
  ...,
  where: {
    x: [a, b],
    or: {
      x: [c, d]
    }
  }
})
```
The result will be a comparison of `(a AND b) OR c OR d` instead of `(a ANF b) OR (c AND d)`.

**Comment by ujjwalguptaofficial** [comment]
@MerlinB unable to reproduce, it works for me. Have a look - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20'Customers'%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20countryCity%3A%20%5B%22Germany%22%2C%20%22Berlin%22%5D%2C%0A%20%20%20%20%20%20%20%20or%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20countryCity%3A%20%5B%22UK%22%2C%20%22London%22%5D%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)&drop=true

**Comment by MerlinB** [comment]
Interesting, thanks for checking. Can't easily reproduce at the moment, so I'm closing this for now.
