### ISSUE TITLE
Intersect compatibility with order by and limit

### ISSUE THREAD

**Issue by MerlinB** [ujjwalguptaofficial/JsStore#169]
There doesn't seem to be a way to add any ordering or limit to the intersection. 

The following query should return ordered results:
```sql
SELECT * FROM Orders
WHERE ((shipperId = 3 AND employeeId = 4)
OR (shipperId = 2 AND employeeId = 3))
INTERSECT
SELECT * FROM Orders
WHERE ((orderId < 10300 AND customerId = 88) OR orderID > 10400)
ORDER BY EmployeeID DESC, CustomerID DESC 
```

Similarly, this limited query should produce 9 results:
```sql
SELECT * FROM Orders
WHERE ((shipperId = 3 AND employeeId = 4)
OR (shipperId = 2 AND employeeId = 3))
INTERSECT
SELECT * FROM Orders
WHERE ((orderId < 10300 AND customerId = 88) OR orderID > 10400)
LIMIT 9
```

**Comment by ujjwalguptaofficial** [comment]
Have added skip,limit in v - 3.9.1. Will add order by in next release.

**Comment by ujjwalguptaofficial** [comment]
Here is an example 

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=intersect(%7B%0A%20%20%20%20queries%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20from%3A%20'Orders'%2C%0A%20%20%20%20%20%20%20%20where%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20shipperId%3A%203%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20employeeId%3A%204%0A%20%20%20%20%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20or%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20shipperId%3A%202%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20employeeId%3A%203%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20from%3A%20'Orders'%2C%0A%20%20%20%20%20%20%20%20where%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20orderId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'%3C'%3A%2010300%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20customerId%3A%2088%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20or%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20orderId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'%3E'%3A%2010400%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%5D%2C%0A%20%20%20%20skip%3A%205%2C%0A%20%20%20%20limit%3A%205%0A%7D)

**Comment by ujjwalguptaofficial** [comment]
@MerlinB implemented order by in v - 3.9.2. Here is an example - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=intersect(%7B%0A%20%20%20%20order%3A%7B%0A%20%20%20%20%20%20by%3A%22Orders.orderId%22%2C%0A%20%20%20%20%20%20type%3A%22desc%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20queries%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20from%3A%20'Orders'%2C%0A%20%20%20%20%20%20%20%20where%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20shipperId%3A%203%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20employeeId%3A%204%0A%20%20%20%20%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20or%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20shipperId%3A%202%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20employeeId%3A%203%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20from%3A%20'Orders'%2C%0A%20%20%20%20%20%20%20%20where%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20orderId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'%3C'%3A%2010300%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20customerId%3A%2088%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20or%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20orderId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'%3E'%3A%2010400%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%5D%2C%0A%20%20%20%20skip%3A%205%2C%0A%20%20%20%20limit%3A%205%0A%7D)

please test and let me know.

**Comment by MerlinB** [comment]
Seems to work fine, thank you!
