### ISSUE TITLE
Uncaught TypeError: Cannot read property '_name' of null"

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#17]
After clearing browsing data by pressing ctrl shift delete and then pressing clear data ,while running project I am getting below error

> "jsstore.min.js:6 Uncaught TypeError: Cannot read property '_name' of
> null"

while creating indexeddb using jsstore.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/UwuIX.png

**Comment by ujjwalguptaofficial** [comment]
I will be adding a proper error message in next version. This will help you to find the exact bug.

Thanks.

**Comment by ujjwalguptaofficial** [comment]
Added the error message. Please check and let me know your result.

Please install latest version - 1.4.4

**Comment by ujjwalguptaofficial** [comment]
Are we good here ? Should I close thie issue ?

**Comment by kamalakkanni** [comment]
Thanks

I installed latest version.I think this will help to find exact bug

**Comment by kamalakkanni** [comment]
Hi,After updating jsstore version also I am getting same error.I can't get
exact bug

Cannot read property '_name' of null

**Comment by ujjwalguptaofficial** [comment]
oho ok. Seems like the update didn't go. There was some merge issue.

Please take the latest version - 1.5.0. I have updated this today.  I have also added some test cases regarding your issue.

Hope this will help you.

Thanks.

**Comment by ujjwalguptaofficial** [comment]
Are you deleting the data and reloading the app after that or not reloading the app ?

**Comment by ujjwalguptaofficial** [comment]
Hi - @kamalakkanni : need your input on this.

> Are you deleting the data and reloading the app after that or not reloading the app ?

Please let me know. Thanks.

**Comment by kamalakkanni** [comment]
Yes.I am deleting the data and inserting while reloading the page.But now,I
changed delete operation as clear



Thanks

**Comment by ujjwalguptaofficial** [comment]
So it is working good right and you are getting no problem right ?

**Comment by kamalakkanni** [comment]
yes its working good.can you pls help me to store image as blob in
indexeddb.I have created issue regarding this,
https://stackoverflow.com/questions/48515936/sending-xhrrequest-doesnt-give-response-sometime



Thanks

**Comment by ujjwalguptaofficial** [comment]
yeah sure, but this is not part of this issue. So I am closing it.

**Comment by kamalakkanni** [comment]
ok,thanks
