### ISSUE TITLE
Select only specific columns from a table

### ISSUE THREAD

**Issue by anujkumar10** [ujjwalguptaofficial/JsStore#170]
I am going through the docs but couldn't see option to select only few columns from a table.

Actually i need to select only few columns from 2 tables using join.
Would be really helpful if this feature exists or can be added

**Comment by ujjwalguptaofficial** [comment]
IndexedDb is nosql database which means your whole data is saved as object. So when retrieving whole data is retrieved not particular column. 

So if we want to select particular columns which means we will have to do some computation which is not good considering client (browser).  It is better to ignore extra column & take what you need.

**Comment by ujjwalguptaofficial** [comment]
@anujkumar10 let me know if this helps or you have some issues with columns.

**Comment by anujkumar10** [comment]
Actually i have modifiedDate column which is repeated in all tables.
And when i try to join to tables, i get the below error:
**{"message":"column modifiedDate exist in both table CustomerOrders & CustomerHistory","type":"invalid_join_query"}**

**Comment by ujjwalguptaofficial** [comment]
For join query - JsStore have `as` property which can be used to rename a column to some other name. 

Here is an example - 

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Orders%22%2C%0A%20%20%20%20join%3A%20%7B%0A%20%20%20%20%20%20%20%20with%3A%20%22Shippers%22%2C%0A%20%20%20%20%20%20%20%20on%3A%20%22Shippers.shipperId%20%3D%20Orders.shipperId%22%2C%0A%20%20%20%20%20%20%20%20as%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20shipperId%3A%20%22Shippers.shipperId%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20shipperName%3A%20%22Shippers.shipperName%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20phone%3A%20%22Shippers.phone%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20type%3A%20%22left%22%0A%20%20%20%20%7D%0A%7D)%3B

**Comment by anujkumar10** [comment]
It worked perfect. Thanks a lot Ujjwal for the quick response.
