### ISSUE TITLE
Failed to execute 'postMessage' on 'Worker' with Update function

### ISSUE THREAD

**Issue by chagamama** [ujjwalguptaofficial/JsStore#18]
On most of my update functions I get the following error in Chrome console;

Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': function (results){

alert(results);
} could not be cloned.

Here is my code:
```				
						
							JSConn.count({
From: "report_topics",
Where: {
user_id: userid,
report_cat_id: catid,
show_topic: 'show',
topic_id: topid
},
OnSuccess:function (results){
//results will be array of objects.
//console.log('c2' + results);
if(results > 0){
plzwork()
}
},
OnError:function (error) {
//error = JSON.parse(JSON.stringify(error));
// alert('e'); alert(error.Name + error.Message ); alert(Object.keys(error));
}
});
						function plzwork(){
						alert('update to hide');
JSConn.update({
In: "report_topics",
Set:{
show_topic:"hide"
},
Where: {
user_id: userid,
report_cat_id: catid,
topic_id: topid
},
onSuccess:function(results){

alert(results);
},
onError:function (error)
{
//error = JSON.parse(JSON.stringify(error));
// alert('e'); alert(error.Name + error.Message ); alert(Object.keys(error));
}});
}
` 
The function plzwork() fires but then the update fails with the error from above.
I'm running this with phonegap (cordova) it is part of a crossplatform app.

**Comment by chagamama** [comment]
Here is the entire error message: 

Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': function (results){

alert(results);
} could not be cloned.
    at Instance.CodeExecutionHelper.executeCodeUsingWorker (http://192.168.0.6:5000/jsstore.js:4524:40)
    at Instance.CodeExecutionHelper.executeCode (http://192.168.0.6:5000/jsstore.js:4510:30)
    at Instance.CodeExecutionHelper.prcoessExecutionOfCode (http://192.168.0.6:5000/jsstore.js:4496:30)
    at http://192.168.0.6:5000/jsstore.js:4470:30
    at new Promise (<anonymous>)
    at Instance.CodeExecutionHelper.pushApi (http://192.168.0.6:5000/jsstore.js:4463:28)
    at Instance._this.update (http://192.168.0.6:5000/jsstore.js:4773:29)
    at plzwork (http://192.168.0.6:5000/edit-report.html:4112:8)
    at Object.OnSuccess (http://192.168.0.6:5000/edit-report.html:4102:1)
    at Instance.CodeExecutionHelper.processFinishedRequest (http://192.168.0.6:5000/jsstore.js:4539:49)
CodeExecutionHelper.executeCodeUsingWorker @ CodeExecutionHelper.ts:75
CodeExecutionHelper.executeCode @ CodeExecutionHelper.ts:60
CodeExecutionHelper.prcoessExecutionOfCode @ CodeExecutionHelper.ts:44
(anonymous) @ CodeExecutionHelper.ts:18
CodeExecutionHelper.pushApi @ CodeExecutionHelper.ts:11
Instance._this.update @ JsStoreInstance.ts:155
plzwork @ edit-report.html:4112
OnSuccess @ edit-report.html:4102
CodeExecutionHelper.processFinishedRequest @ CodeExecutionHelper.ts:91
CodeExecutionHelper.onMessageFromWorker @ CodeExecutionHelper.ts:174
JsStore.WorkerInstance.onmessage @ CodeExecutionHelper.ts:118


Please any help would be greatly appreciated, if I can overcome this last hurdle I will be able to release soon

**Comment by ujjwalguptaofficial** [comment]
```
JSConn.update({
In: "report_topics",
Set:{
   show_topic:"hide"
},
Where: {
 user_id: userid,
report_cat_id: catid,
topic_id: topid
},
onSuccess:function(results){

alert(results);
},
onError:function (error)
{
//error = JSON.parse(JSON.stringify(error));
// alert('e'); alert(error.Name + error.Message ); alert(Object.keys(error));
}});
}
```
Here you are using 'onSuccess' instead of  'OnSuccess' . This is just a typo mistake.

Let me know if you are getting this any more.

**Comment by chagamama** [comment]
It worked thank you sooo much!

**Comment by ujjwalguptaofficial** [comment]
Good to know.
