### ISSUE TITLE
How can I update dexie to JsStore gradually

### ISSUE THREAD

**Issue by xland** [ujjwalguptaofficial/JsStore#184]
# Title 
How can I update dexie to JsStore gradually

# Description
I try to connect my indexeddb ( which is created by `dexie`)  by `JsStore`
I found that `JsStore` will renew the table, and all the data in the table will be cleared.
Is there some way to update dexie to JsStore gradually?

**Comment by ujjwalguptaofficial** [comment]
Can be but i will have to find steps. Could you please create a demo using dexie & then i will try to find steps.

**Comment by xland** [comment]
```html
<!doctype html>
<html>
  <head>
      <script src="./dexie.min.js"></script>
      <script src="./jsstore.min.js"></script>
      <script src="./jsstore.worker.min.js"></script>
      <script>
        let dexieDbInit = async ()=>{
            var db = new Dexie("friend_database");
            db.version(10).stores({ friends: 'name' });
            await db.friends.put({name: "allen"})
            let obj = await db.friends.get('allen');
            console.log(obj)
        }
        let jsStoreDbInit = async ()=>{
          var jsstoreCon = new JsStore.Connection();
          jsstoreCon.initDb({
              name: 'friend_database',
              tables: [{
                name:"friends",
                columns: {
                  name: {
                    primaryKey: true,
                    dataType: 'string'
                  }
                }
              }]
          })
          var students = await jsstoreCon.select({ from: 'friends' });
          console.log(students)
        }
        (async ()=>{
          await dexieDbInit();
          // await jsStoreDbInit();
        })()
      </script>
  </head>
</html>
```

When `jsStoreDbInit` execute , the db version will increased from 1 to 10
When I set  the db version for `JsStore` (by debugger), the table will be cleared.

**Comment by ujjwalguptaofficial** [comment]
sorry due to some personal work, i am not able to look into this. If you are in hurry, simplest solution is to change db name so there is no issue of any other framework.

But yes if you want to retain data, then this won't work.

**Comment by ujjwalguptaofficial** [comment]
@xland check out this doc for migrating fromv3 to v4 - https://jsstore.net/tutorial/v3-to-v4/

The same can be applied for any other framework like dexie. 

So simple, create your db schema in form of jsstore & increase your db version or table version greater than current db version.
