### ISSUE TITLE
Between doesn't work with equal to and like where clause conditions

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [ujjwalguptaofficial/JsStore#185]
# Between doesn't work with equal to and like where clause conditions

- [x] Bug

**Version:** jsstore:^3.10.3

**Issue Description:** When `between` clause used along with equal to and like conditions it doesn't work as expected. `Between` condition is not considered while fetching the data.

**Observation:** This issue happens when the `equal to` clause is the first condition in the where clause

**Steps to reproduce**

    select({
    from: "Products",
    where: {
        productName: "Aniseed Syrup",
        price: {
            "-": {
                low: 20,
                high: 20
            }
        }
    }
    })

**Comment by ujjwalguptaofficial** [comment]
Seems fine for me , here is idbstudio link - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Products%22%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20productName%3A%20%22Aniseed%20Syrup%22%2C%0A%20%20%20%20%20%20%20%20price%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22-%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20low%3A%2020%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20high%3A%2020%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)

may be you want something else. Could you tell me equivalent sql query ?

**Comment by Suroor-Ahmmad** [comment]
The link what you shared doesn't give proper output, it only checks for `productName` match, this works fine if you change order, that is `between` as first where clause and productName as second

this is the equivalent sql query.
`Select * from Products where productName = "Aniseed Syrup" and price >= 15 and price <= 20`.

**Comment by ujjwalguptaofficial** [comment]
yes there is issue. So when changing the order results is zero. 

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Products%22%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20price%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22-%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20low%3A%2020%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20high%3A%2020%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20productName%3A%20%22Aniseed%20Syrup%22%2C%0A%20%20%20%20%7D%0A%7D)

Will fix and let you know

**Comment by Suroor-Ahmmad** [comment]
Yes, the result is zero because there's no any match cases.

**Comment by ujjwalguptaofficial** [comment]
@Suroor-Ahmmad  i have fixed in v - 3.11.2 . Please install and let me know if issue is fixed.
