### ISSUE TITLE
Updating an object value as blob gives “Invalid Op Value 'size'”, _type: “invalid_operator”} error using jsstore

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#19]
I would have updated a column (type object) by blob value.Iam getting

"Invalid Op Value 'size'", _type: "invalid_operator"} error.Can anyone pls help me to fix it

    UpdateBLobInIndexedDb(blob,Id)
    {
        this._connection.openDb(this._indexedDBLiveDBName);
        return this._connection.update({
            In: this._indexedDBLiveDBTableName,
            Set: {
                ImageBlob: blob,
            },
            Where: {
                ArticleId:Id
            }
       });
    }
thanks

**Comment by ujjwalguptaofficial** [comment]
Ok, this is an issue. I will solve it asap and let you know.

**Comment by ujjwalguptaofficial** [comment]
btw - if you are in hurry, you can save the image as base64 and after that you can update it. Here is the demo for how to do it - https://github.com/udaychy/ImageDemo

there is some problem in updating the object under a property. We have not expected such scenario.

Thanks

**Comment by kamalakkanni** [comment]
Thanks,But inserting blob as object is working fine.So,that I am using
another table to store image as blob (object)

**Comment by ujjwalguptaofficial** [comment]
Please update the jsstore version.

**Comment by kamalakkanni** [comment]
update query gives below error

 ArticleId is not defined

 for below code

UpdateBLobInIndexedDb(blob,articleId)
{
this._connection.openDb(this._indexedDBLiveDBName);
this._connection.update({
In:this._indexedDBLiveDBArticleTableName,
Set: {ImageBlob:blob},
Where:{ArticleId,articleId},
Return: 'Boolean',
SkipDataCheck: 'Boolean'
});
}
But It has column ArticleId

**Comment by kamalakkanni** [comment]
It is due to articleId value is 0000000000 for one record.But all other
records should be updated right.No one is getting updated.While debugging I
am getting bob

**Comment by ujjwalguptaofficial** [comment]
first - remove return and skipdatacheck : there is no use of these options in update. They are only valid for insert query.

**Comment by ujjwalguptaofficial** [comment]
and please provide the whole error object, with error type and message. So that I can see what is actual error.

**Comment by kamalakkanni** [comment]
I removed those.now also it is not getting updated

**Comment by ujjwalguptaofficial** [comment]
> Where:{ArticleId,articleId},

you have written ',' instead of ':' . It may be due to this typo mistake.

**Comment by kamalakkanni** [comment]
Thanks,Its working fine now

**Comment by kamalakkanni** [comment]
hi,after updating blob in table,fetching of data is very slow
