### ISSUE TITLE
Can't figure out how to search same field for multiple values

### ISSUE THREAD

**Issue by kwlayman** [ujjwalguptaofficial/JsStore#193]
How to construct where clause to search for multiple values in array type multientry field?

I have a TAGS array-type field, multiEntry.

How do I construct a where clause to do an AND search for multiple tags?

**Comment by kwlayman** [comment]
Need something like below but apparent and is not supported like this:
where:{
   TAGS: 'test1',
   and:{
      TAGS:'test2'
   }
}

**Comment by ujjwalguptaofficial** [comment]
have you tried ?  

```
where: [{
    TAGS: 'test1'
}, {
    TAGS: 'test2'
}]
```

**Comment by kwlayman** [comment]
That works! Thanks!
