### ISSUE TITLE
Bug in transaction example

### ISSUE THREAD

**Issue by The-MAZZTer** [ujjwalguptaofficial/JsStore#197]
The beginning of the transaction example reads:

    logic: async function(ctx) {  // async is used to make code more clear
        start(); // start the transaction

It should be:

    logic: async function(ctx) {  // async is used to make code more clear
        ctx.start(); // start the transaction

Also there is no example button to allow to mess with it on idbstudio. I think for this complex a topic that would really be useful.

**Comment by ujjwalguptaofficial** [comment]
the transaction api doc is updated. Now you will have to call first importScript and then transaction api.
