### ISSUE TITLE
GROUP BY Clause

### ISSUE THREAD

**Issue by udaychy** [ujjwalguptaofficial/JsStore#2]
Hi 
I came across a situation where i needed to perform a GROUP BY operation.
I figured out a way by applying filter after getting the complete set of results but it may not be the right and efficient way to do that. 

It will be very helpful if you provide an API for GROUP BY too.

**Comment by ujjwalguptaofficial** [comment]
Hey @udaychy  - yes you are right. Calling select query multiple times does the things but its not a good idea.

Thanks for letting us know. We will surely implement this one. It Seems a more important option for users.

**Comment by ujjwalguptaofficial** [comment]
@udaychy - we have added the support for group by. Here is the link - http://www.jsstore.net/tutorial/group_by.

We have also added support for aggregation functions like - sum, count, max, avg, min. You can execute aggregate functions alone as well as with group by. Here is the link - http://jsstore.net/tutorial/aggregate

Thanks for your contribution.

**Comment by di3nt3d3l3on** [comment]
@ujjwalguptaofficial does this functionality still working? http://www.jsstore.net/tutorial/group_by. the link you've provided said 404 Page not found. 

Thanks,
