### ISSUE TITLE
for in used to iterate over array in BaseSelect.prototype.removeDuplicates

### ISSUE THREAD

**Issue by The-MAZZTer** [ujjwalguptaofficial/JsStore#200]
For in is not recommended for use to iterate over arrays as it can cause problems

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#array_iteration_and_for...in

For example if I add helper functions to Array.prototype, for in ends up iterating over them, if I use jsstore without the webworker (required if invoked from a service worker).

(Of course if jsstore runs in its own worker it has its own Array.prototype so the bug cannot be triggered.)

jsstore.worker.js:2857 BaseSelect.prototype.removeDuplicates does this

        for (var i in datas) {
            lookupObject[datas[i][key]] = datas[i];
        }  // free datas memory

should be

        for (var i of datas) {
            lookupObject[i[key]] = i;
        }  // free datas memory

or if targeting older JS versions or the array index is needed

        for (var i = 0; i < datas.length; i++) {
            lookupObject[datas[i][key]] = datas[i];
        }  // free datas memory

I have tested latter form and it fixes the problem I was having

This is difficult to reproduce in idbstudio since idbstudio only allows for use of jsstore with the web worker, where this problem can't normally occur.

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Products%22%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20price%3A%7B%0A%20%20%20%20%20%20%20%20%20%22!%3D%22%3A20%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)%3B%0A

Open the Chrome debugger and open the console. Select jsstore.worker.whatever from the context dropdown (in the console toolbar on the left). Add something to Array prototype like `Array.prototype.testValue = 10`. Now execute the query. Scroll to the bottom and you'll see an extra "undefined" record; that is the result of the value 10 being added to the array of results.

**Comment by ujjwalguptaofficial** [comment]
fixed in version - 3.13.3
