### ISSUE TITLE
While Clearing browser data keystore is not deleted So that getting db not exist error

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#21]
Hi,

While Clearing browser data keystore is not deleted So that getting db not exist error sometimes.Can you pls help me to fix it when u r free

I am using below code for checking dbexist

         JsStore.isDbExist(That._indexedDBLiveDBName).then(isExist => {
            if (!isExist) {
                const DataBase = That.getDbSchema();
                That._connection.createDb(DataBase, function () {
                    That._isLiveDbCreated = true;
                    localStorage.setItem('_isLiveDbCreated', 'true');
                    return;
                });
            }
            else {
                That._isLiveDbCreated = true;
                localStorage.setItem('_isLiveDbCreated', 'true');

                return;
            }
        }).catch(err => {
            // this will be fired when indexedDB is not supported.
            console.log(err.Message);
        });

Thanks

**Comment by ujjwalguptaofficial** [comment]
I am already working on it. Will let you know as soon as it is completed. This is a big change actually, so its gonna take some time.

Thanks.

**Comment by kamalakkanni** [comment]
ok.thanks

**Comment by ujjwalguptaofficial** [comment]
Hi
I have solved this issue. Please install the latest version -1.6.0.

Please let me know if its solved or the problem remains still.

thanks.

**Comment by kamalakkanni** [comment]
Hi,

Thanks,That error is fixed after intalling latest version 1.6.0 ."But It
gives Uncaught (in promise): undefined at resolvePromise
(webpack-internal:///../../../../zone.…, …}".



Thanks

**Comment by ujjwalguptaofficial** [comment]
I cant see code, where it is showing undefined.

Can you add a screenshot or the code snippet ?

**Comment by ujjwalguptaofficial** [comment]
Are you getting this at 'delete' method ?

**Comment by kamalakkanni** [comment]
I am having clear method only.I didn't check where it is from .Since it was
fine before updating jsstore.After that error I installed old version
1.5.2.That's y I said to you

**Comment by ujjwalguptaofficial** [comment]
please let me know if all good.

Thanks.

**Comment by kamalakkanni** [comment]
thanks,Its working fine.(Sorry for the late reply(I can't update the
version because I worked for the demo )

**Comment by ujjwalguptaofficial** [comment]
Ok thanks. Closing the issue.

**Comment by kamalakkanni** [comment]
Hi,

After clearing indexeddb table gives
"Error: Uncaught (in promise): undefined at resolvePromise
(webpack-internal:///../../../../zone.js/dist/zone.js:665:31)" error.How
can i fix it.

**Comment by ujjwalguptaofficial** [comment]
How are you clearing the table ?

**Comment by kamalakkanni** [comment]
if (this._isLiveDbCreated) {
this._connection.openDb(this._indexedDBLiveDBName);
return this._connection.clear(this._indexedDBLiveDBArticleTableName);

}

**Comment by ujjwalguptaofficial** [comment]
Can you share the code - where you are getting error. I mean code which is at zone.js : 665

**Comment by kamalakkanni** [comment]
Hi,

while returning clear method I got below

"Error: Uncaught (in promise): undefined at resolvePromise
(webpack-internal:///../../../../zone.js/dist/zone.js:665:31) [<root>] at
eval (webpack-internal:///../../../../zone.js/dist/zone.js:591:17) [<root>]
at Object.e.OnError (http://localhost:4200/assets/js/jsstore.min.js:6:81017)
[<root>] at r.t.processFinishedRequest (
http://localhost:4200/assets/js/jsstore.min.js:6:82929) [<root>] at
r.t.onMessageFromWorker (
http://localhost:4200/assets/js/jsstore.min.js:6:83644) [<root>] at
r.<anonymous> (http://localhost:4200/assets/js/jsstore.min.js:6:81286)
[<root>]"

Below zone.js code from where I am getting this error

 function consoleError(e) {
        if (Zone[__symbol__('ignoreConsoleErrorUncaughtError')]) {
            return;
        }
        var rejection = e && e.rejection;
        if (rejection) {
            console.error('Unhandled Promise rejection:', rejection
instanceof Error ? rejection.message : rejection, '; Zone:', e.zone.name,
'; Task:', e.task && e.task.source, '; Value:', rejection, rejection
instanceof Error ? rejection.stack : undefined);
        }
        console.error(e);
    }

**Comment by ujjwalguptaofficial** [comment]
Please add another issue for this. I will try to reproduce this.

**Comment by kamalakkanni** [comment]
Hi,db not exist is coming again
