### ISSUE TITLE
How to use INSERT IGNORE?

### ISSUE THREAD

**Issue by imannms** [ujjwalguptaofficial/JsStore#211]
# How to use `INSERT IGNORE`?

# 
```sql

CREATE TABLE subscribers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL UNIQUE
);

INSERT IGNORE INTO subscribers(email)
VALUES('john.doe@gmail.com'), 
      ('jane.smith@ibm.com');

```

How to do this in JsStore? I can't find the tutorial in the docs.

**Comment by ujjwalguptaofficial** [comment]
`ignore` in insert api is not implemented. Will work on this.

**Comment by imannms** [comment]
Thank you for your quick response.

**Comment by ujjwalguptaofficial** [comment]
@imannms `ignore` is implemented in new version - 4.0.2. Here is doc - https://jsstore.net/tutorial/insert/#ignore

Let me know if you see any issue or have any suggestion.

**Comment by imannms** [comment]
I don't know if it's related to this but I have issue with `insert` for some time now. This issue appeared after `ignore` was implemented. But the thing is, this issue appears randomly. I don't know what caused this. Not all tables have this issue. Just random.

Insert some random unique_key that doesn't exists in the table, and it's just failed.

Error message:
```js
{
  message: "Key already exists in the object store.",
  type: "ConstraintError"
}
```

I check indexeddb but that key doesn't exists.

The way to fix this is to use `await connection.clear(table_name)` . Somehow after clearing the table, my `insert` query started working again.

For the current workaround, I need to `clear` all tables after `initializing` the database for the first time.

**Comment by ujjwalguptaofficial** [comment]
this is happening for insert with ignore right ? also are you inserting multiple record at a time - if yes, then could you tell me how many max record ? I will try to add a test in this case.

**Comment by ujjwalguptaofficial** [comment]
i just added a test for multiple data insert and it works fine. Ref - https://github.com/ujjwalguptaofficial/JsStore/commit/b2d76b0ae7a824aada727a8c5b00149edaa9fa8d

My guess is your unique data is sometimes not unique. You can use count first and then insert the data.

```
const result = await count({
  from:'table',
  where:{ unique: unique_value }
});

if(result==0){
  // insert data
}
```
