### ISSUE TITLE
Make usable from SharedWorker

### ISSUE THREAD

**Issue by Madman600** [ujjwalguptaofficial/JsStore#221]
Is it possible to make usable from SharedWorker? window is undefined and Worker constructor is unavailable, and importScripts is unavailable.

**Comment by ujjwalguptaofficial** [comment]
yes its possible, but there is small issue. Will fix it in some time.

**Comment by ujjwalguptaofficial** [comment]
fixed in v - 4.2.3

**Comment by Madman600** [comment]
Thank you.
