### ISSUE TITLE
select order does not look to work

### ISSUE THREAD

**Issue by nielsnl68** [ujjwalguptaofficial/JsStore#224]
# Title 

I doing a sort on two fields 

``` javascript
        var result = await jsstoreCon.select({
            from: "metingen",
            where: {meter: ref, datum: { ">=": oldDate.format("YYYYMMDD") } },
            order: [{ by: 'datum', type: "desc" },
            { by: 'tijd',  type: "asc" }]
        });
```

``` javascript
    var metingen = {
        name: 'metingen',
        columns: {
            id: { primaryKey: true, autoIncrement: true },
            meter: { notNull: true, dataType: 'number' },
            datum: { notNull: true, dataType: 'string' },
            tijd: { notNull: true, dataType: 'string' },
            waarde: { notNull: true, dataType: 'number' },
            maaltijd: { notNull: true, dataType: 'string', default: 'U' },
            importDT: { notNull: true, dataType: 'string' },
            unique: { keyPath: ['meter', 'datum', 'tijd'], unique: true }
        },
        alter: {

        }
    };
```
but the result is not sorted at datum field:

```
0: {meter: 1, datum: "20210616", tijd: "1130", waarde: 14, importDT: "1", …}
1: {meter: 1, datum: "20210614", tijd: "0019", waarde: 18.17, importDT: "1", …}
2: {meter: 1, datum: "20210615", tijd: "0726", waarde: 0.67, importDT: "1", …}
3: {meter: 1, datum: "20210614", tijd: "0956", waarde: 14.11, importDT: "1", …}
4: {meter: 1, datum: "20210612", tijd: "0612", waarde: 13.78, importDT: "1", …}
5: {meter: 1, datum: "20210612", tijd: "1634", waarde: 17.61, importDT: "1", …}
6: {meter: 1, datum: "20210611", tijd: "0931", waarde: 12.67, importDT: "1", …}
7: {meter: 1, datum: "20210609", tijd: "0827", waarde: 12.22, importDT: "1", …}
8: {meter: 1, datum: "20210608", tijd: "0634", waarde: 10.11, importDT: "1", …}
```
in my opinion it should look like:

```
0: {meter: 1, datum: "20210616", tijd: "1130", waarde: 14, importDT: "1", …}
2: {meter: 1, datum: "20210615", tijd: "0726", waarde: 0.67, importDT: "1", …}
1: {meter: 1, datum: "20210614", tijd: "0019", waarde: 18.17, importDT: "1", …}
3: {meter: 1, datum: "20210614", tijd: "0956", waarde: 14.11, importDT: "1", …}
4: {meter: 1, datum: "20210612", tijd: "0612", waarde: 13.78, importDT: "1", …}
5: {meter: 1, datum: "20210612", tijd: "1634", waarde: 17.61, importDT: "1", …}
6: {meter: 1, datum: "20210611", tijd: "0931", waarde: 12.67, importDT: "1", …}
7: {meter: 1, datum: "20210609", tijd: "0827", waarde: 12.22, importDT: "1", …}
8: {meter: 1, datum: "20210608", tijd: "0634", waarde: 10.11, importDT: "1", …}
```

**Comment by ujjwalguptaofficial** [comment]
use `idbSorting:false` . By default `idbSorting` is true which means sort the data using indexeddb which works most of time but for some cases it does not. 

so query will be - 

```
var result = await jsstoreCon.select({
    from: "metingen",
    where: {
        meter: ref,
        datum: {
            ">=": oldDate.format("YYYYMMDD")
        }
    },
    order: [{
            by: 'datum',
            type: "desc",
            idbSorting: false
        },
        {
            by: 'tijd',
            type: "asc",
            idbSorting: false
        }
    ]
});
```

**Comment by nielsnl68** [comment]
Sadly, that did not fix it. 
I really can't see any reason why jsStore changed the order of those 2 records, from the currently 172 i see it 3 times. First i thought it could be the generated id but those are in sync.

Is there anyway i can debug this more?

**Comment by ujjwalguptaofficial** [comment]
strange :thinking: .

@nielsnl68 could you give me your table data as json file. There might be some edge case.

**Comment by ujjwalguptaofficial** [comment]
I tried to reproduce but couldn't - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20'OrderDetails'%2C%0A%20%20%20%20limit%3A%20100%2C%0A%20%20%20%20order%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20by%3A%20%22orderId%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3A%22desc%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20by%3A%20%22productId%22%2C%20type%3A%22desc%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%7D)

@nielsnl68 if you can generate on idbstudio, then it is also fine for me.

**Comment by nielsnl68** [comment]
it seems that https://localhost:3000 and http://localhost:3000 are not the same for chrome. i cant access my database from within idbstudio. 

I have no  issue to show the data but not openly. any change you can a private way to send the data.

**Comment by ujjwalguptaofficial** [comment]
send me at my mail - ujjwalkumargupta44@gmail.com

**Comment by nielsnl68** [comment]
I send you the data soon. 

you fixed something with new column added using alter query is not indexable. How can i see of i suffer from that bug. It sounds a possible issue i could see with my issue. it make's sense, although the fields i sorted on where always there from the start.
How can i check this on my db?

**Comment by ujjwalguptaofficial** [comment]
@nielsnl68 please use discussion for asking something which is not related to the issue page. So that we can make the issue page clear. here i have created a q&a discussion for you - https://github.com/ujjwalguptaofficial/JsStore/discussions/225

**Comment by nielsnl68** [comment]
i saw a possible relationship with my issue. that's why i asked here. ;)

**Comment by ujjwalguptaofficial** [comment]
@nielsnl68 i have not yet received datas. Please send it my email or you can install idbstudio at your site and provide me link to the idbstudio.

**Comment by nielsnl68** [comment]
Thanks for reminding. 
I cant preproduce the issue outside the current structure. 
When i run my webapp on a other setup the issue was gone.

**Comment by ujjwalguptaofficial** [comment]
ohk, closing the issue then.Feel free to reopen.
