### ISSUE TITLE
"Supplied value is not an array" error when inserting into string column

### ISSUE THREAD

**Issue by kinhoon** [ujjwalguptaofficial/JsStore#244]
I am trying to insert a stringified JSON array into a table, but keep getting error "Supplied value is not an array".
![image](https://user-images.githubusercontent.com/46112444/130500279-c66b8420-2111-4a30-9009-b26397281043.png)

I do not have any column of array type.
![image](https://user-images.githubusercontent.com/46112444/130500229-0a505776-1078-43e1-b340-4c9bc01a1d3f.png)

The stringified JSON array is in the following format:
`[ ["2021-08-01 12:00:00", 1.223], ["2021-08-01 12:00:01", 2.345], ["2021-08-01 12:00:02", 52.321] ]`

I chose to stringify the JSON array instead of creating a column of `array` type because I never able to insert this JSON array into the array column, so I thought I can try to save the stringified version instead, but it seems `JsStore` internally still insist to perform data parsing before inserting into a string column?

**Comment by ujjwalguptaofficial** [comment]
Seems like your insert query is wrong. Please post your insert query with values.

**Comment by kinhoon** [comment]
The function `fetchChartData` returns a string containing a stringify JSON array.
The table is empty when performing insertion.

``` let fetchResults1 = await this.fetchChartData(tag, begin, end);
 if (fetchResults1 != '') {
     this.db?.insert({
         into: DbTable.HistorianLog,
         values: {
             Id: null,
             Tag: tag,
             Begin: begin,
             End: end,
             Value: fetchResults1
         }
     });
 }
```

**Comment by ujjwalguptaofficial** [comment]
values is supposed to be array. 

```
 this.db?.insert({
         into: DbTable.HistorianLog,
         values: [{
             Id: null,
             Tag: tag,
             Begin: begin,
             End: end,
             Value: fetchResults1
         }]
     });
```

just add array syntax, and it will work.

**Comment by kinhoon** [comment]
Updated a bit, same result.

``` javascript
let fetchResults1 = await this.fetchChartData(tag, begin, end);
if (fetchResults1) {
    this.$log.info('save into db', fetchResults1);
    this.db?.connection?.insert({
        into: DbTable.HistorianLog,
        values: {
            Id: null,
            Tag: tag,
            Begin: begin,
            End: end,
            Value: fetchResults1
        }
    });
}
```

The `fetchChartData` function just returns an actual array.
``` javascript
async fetchChartData(tag, begin, end) {
    return JSON.parse('[ ["2021-08-01 12:00:00", 1.223], ["2021-08-01 12:00:01", 2.345], ["2021-08-01 12:00:02", 52.321] ]');
}
```

The console shows browser recognize the `fetchResults1` as array, but `JsStore` still complaining the `Supplied value is not an array`.
![image](https://user-images.githubusercontent.com/46112444/130552526-d9f3f9c9-88c6-4670-ae63-b032e9f88a54.png)

The schema also showing the column data type is setup correctly as `array`.
![image](https://user-images.githubusercontent.com/46112444/130552721-e8d28f5f-30e0-4ed9-b46c-aad32ad72bba.png)

I can't see where goes wrong?

**Comment by ujjwalguptaofficial** [comment]
jsstore expects array of value into `values` field but you are providing a single value (single object) . You are supplying - 

```
{
            Id: null,
            Tag: tag,
            Begin: begin,
            End: end,
            Value: fetchResults1
        }
```

Use [ value ]  and your value will be inserted.

**Comment by kinhoon** [comment]
Got it !!!! Thanks. I missed that tiny details.

Just a suggestion, is it possible to add support to accept either a single object or an actual array as `values` and `JsStore` push the object into an array internally? Since Javascript supports operation like this.

**Comment by ujjwalguptaofficial** [comment]
Yes its possible, you can create a method to take single object and insert - 

```
funcion insertValue(value){
   return con.insert({
       into:'table',
       values : [ value ]
   })
}
```

and we already support for pushing data into existing array. You will have to use update for this - https://jsstore.net/tutorial/update/with-operators/

use `{push}` operator
