### ISSUE TITLE
为什么new Connection()的时候，不传递worker就会报错。 是必须使用worker吗

### ISSUE THREAD

**Issue by cy-biggray** [ujjwalguptaofficial/JsStore#246]
## Summary

Brief explanation of the feature.

### Basic example

Include a basic example or links here.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by cy-biggray** [comment]
为什么new Connection()的时候，不传递worker就会报错。 是必须使用worker吗? 
我想不使用worker去使用他。

**Comment by ujjwalguptaofficial** [comment]
If you are not using worker, you will have to tell jsstore to use `worker logic` in the same thread by using below code - 

```
Copy 
import workerInjector from "jsstore/dist/worker_injector";
const connection = new Connection();

connection.addPlugin(workerInjector);
```

I hope this helps.
