### ISSUE TITLE
After clearing data using clear api got uncaught (in promise): undefined at resolvePromise issue in v:1.6.0

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#25]
Hi,

while returning clear method I got below

"Error: Uncaught (in promise): undefined at resolvePromise
(webpack-internal:///../../../../zone.js/dist/zone.js:665:31) [<root>] at
eval (webpack-internal:///../../../../zone.js/dist/zone.js:591:17) [<root>]
at Object.e.OnError (http://localhost:4200/assets/js/jsstore.min.js:6:81017)
[<root>] at r.t.processFinishedRequest (
http://localhost:4200/assets/js/jsstore.min.js:6:82929) [<root>] at
r.t.onMessageFromWorker (
http://localhost:4200/assets/js/jsstore.min.js:6:83644) [<root>] at
r.<anonymous> (http://localhost:4200/assets/js/jsstore.min.js:6:81286)
[<root>]"

Below zone.js code from where I am getting this error

 function consoleError(e) {
        if (Zone[__symbol__('ignoreConsoleErrorUncaughtError')]) {
            return;
        }
        var rejection = e && e.rejection;
        if (rejection) {
            console.error('Unhandled Promise rejection:', rejection
instanceof Error ? rejection.message : rejection, '; Zone:', e.zone.name,
'; Task:', e.task && e.task.source, '; Value:', rejection, rejection
instanceof Error ? rejection.stack : undefined);
        }
        console.error(e);
    }

Can you pls help me to fix it.

Thanks

**Comment by ujjwalguptaofficial** [comment]
Are you using catch when calling clear api?

**Comment by kamalakkanni** [comment]
no,I am not using

**Comment by ujjwalguptaofficial** [comment]
I see you are compiling the jsstore with angular and i did too.
I found that promise rejection is being called before the jsstore process has finished. So  there is some issue with angular. 

I executed the jsstore from index.html (not compiling with angular code) and it worked great.

**Comment by ujjwalguptaofficial** [comment]
Sorry , its something else. I will let you know. Ignore the above message.

**Comment by ujjwalguptaofficial** [comment]
@kamalakkanni - issue is solved. Please confirm from your side. Please download the latest version.

Thanks.

**Comment by kamalakkanni** [comment]
Thanks.it is fixed.may i know  the root cause

**Comment by ujjwalguptaofficial** [comment]
There was a small mistake, where onerror event was being called for success.
