### ISSUE TITLE
notNull constraint causes inserting empty strings to fail

### ISSUE THREAD

**Issue by D4uS1** [ujjwalguptaofficial/JsStore#259]
Hi everyone,

if i try to insert an empty string in a table having a notNull constraint, it fails.
This seems to be because of [this line](https://github.com/ujjwalguptaofficial/JsStore/blob/054314113458bfaabd683e9985e86da274706e09/src/worker/utils/is_null.ts#L6).

I think this is not really an issue but more some matter of opinion.
In my opinion, an empty string is not null. I think there is a difference between "not existent" and "empty" that should be distinguishable in code and database.

Do you also think we should correct this and allow empty strings to be inserted?

Thank you very much

**Comment by ujjwalguptaofficial** [comment]
That makes sense, let me check out the code and come back to you.

**Comment by ujjwalguptaofficial** [comment]
This has been fixed and release in version - 4.3.8.
