### ISSUE TITLE
Can I use not operator in where clause using jsstore while fetching data from indexeddb

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#26]
Hi,

Can I use not operator in where clause using jsstore while fetching data from indexeddb.I tried below but not working

this._connection.openDb(this._indexedDBLiveDBName);
     
        return this._connection.select({
            From: this._indexedDBLiveDBArticleTableName,
            Distinct: true,
            Where: {
                CustomSection: section,
               ** Url: ! url**
            },
            Limit: this._Count
        });

Thanks

**Comment by ujjwalguptaofficial** [comment]
No its not there. But this will be great feature though. I will add it .

Thanks for pointing it out.

**Comment by kamalakkanni** [comment]
Hi,

If u added ,pls let me know

Thanks

**Comment by ujjwalguptaofficial** [comment]
Hi - its gonna take some time. I will let you know.

Thanks

**Comment by ujjwalguptaofficial** [comment]
@kamalakkanni - feature for using not is added. Please install the version - 1.6.3 .

Here is the doc link - http://jsstore.net/tutorial/operators

Thanks

**Comment by kamalakkanni** [comment]
ok.Thank you so much
