### ISSUE TITLE
Chrome process CRASHES due to "heavy" data storage (?)

### ISSUE THREAD

**Issue by mikron123** [ujjwalguptaofficial/JsStore#264]
I'm trying to store around 100-200 blob records, a few MBs each, of short video clips.

After I reach this number, I quit the browser, and try to load the website again, it crashes right on the start, along with the Chrome process (the whole process is crashing, not only the website!)

What is the reason for it? is there a storage limitation in JsStore? Or is it Chrome?

**Comment by ujjwalguptaofficial** [comment]
jsstore does not add any limit on data size or whole indexeddb size. But browser restrict this.

There might be some primary memory issue also while processing large no of blobs.
