### ISSUE TITLE
It seems like all the jsstore file links are broken in the examples

### ISSUE THREAD

**Issue by NJseo** [ujjwalguptaofficial/JsStore#27]
I do not know if this is supposed to be installed with NPM or something but, the links are going to .js and in the folders are .d.ts files instead. Why was this setup this way are is this on purpose. As a result the examples do not work. I would live to try out this library but I have a feeling there is a miss in the directions.

**Comment by ujjwalguptaofficial** [comment]
May i know - which example file we are talking ? Is this example folder in the project ?

**Comment by NJseo** [comment]
I was able to modify the script tag to goto the DIST folder, but it was the two examples were using .d.ts files instead of .js files. It was the two examples.

While I got your attention, can these scripts easily be adapted to run on sqllite-3? That might be a great solution if the sql can remain in the cached files and served locally, no?

**Comment by ujjwalguptaofficial** [comment]
There are multiple files - 
1. jsstore.js - debug js file
2. jsstore.min.js - production js file
3. .d.ts - is a definition file for typescript.

can you tell me how you are using these files, I mean how you are creating the application. It might be that you are doing it wrong or may be you are using some different process which I m unaware of.

Btw - please have a look at : http://jsstore.net/Tutorial/

Please, Let me know

**Comment by ujjwalguptaofficial** [comment]
> can these scripts easily be adapted to run on sqllite-3? That might be a great solution if the sql can remain in the cached files and served locally, no?

there is no relation of sql code with jsstore. It just provides api which is similar to sql, so that you can easily learn and use it. The actually operation is done in indexeddb.

Thanks.

**Comment by NJseo** [comment]
I just took your example after uploading it, and then I tried to run it. I saw that there was roken links after it didnt work, so I updated the inks to go to the DIST folder. Seems pretty neat though. I would like to see the shopping cart and the image dropper in the examples folder, that would be great.

Also, I am at a sticking point with my other question too, so if you could help me out with that I would appreciate it.

**Comment by ujjwalguptaofficial** [comment]
Oho ok, I got it. By default it is pointing to output folder and it might be not linked perfectly right ?

**Comment by ujjwalguptaofficial** [comment]
I have updated the example folder code. Please have a look and let me know if you are still getting it.

**Comment by NJseo** [comment]
Yeah, so at first I figured another one of these broken projects. But because I wanted this solution, I looked into the code and the links were off. So I fixed them. But if you want it to pick up, you shuold include all of the examples working in the proper order in the examples folder. Just my opinion, thats all.

**Comment by ujjwalguptaofficial** [comment]
Are we good on this ?  Should I close the issue ?

**Comment by NJseo** [comment]
Yeah, close it. Thanks.
