### ISSUE TITLE
Count query with "In" operator doesn't work properly

### ISSUE THREAD

**Issue by alisabrigok** [ujjwalguptaofficial/JsStore#273]
# Title 

Using the "Where" clause with the "In" operator in the Count query doesn't work properly.

# Description 

Note: The below queries can be tested on IDBStudio with the existing Demo database.

When I perform a Select query using the "Where" clause with the "In" operator, I receive the correct result. But when I apply the same query in order to get the count, the query works incorrectly.

Below query shows 3 rows, which is correct:

```
select({
    from: 'Orders',
    where: {
        employeeId: {
            in: [5, 3]
        },
        customerId: {
            in: [87]
        },
    }
})
```

But the same query using Count returns 42, which is incorrect. The expected output was 3, instead got 42:

```
count({
    from: 'Orders',
    where: {
        employeeId: {
            in: [5, 3]
        },
        customerId: {
            in: [87]
        },
    }
})
```

In the above query, Count ignores customerId filter. 

In fact based on my testing, if the filter was performed with "In" operator being the first filter, Count ignores any filter that comes after the "In" operator.

For example, the below query works as expected. The output is 1:

```
count({
    from: 'Orders',
    where: {
        customerId: 87,
        employeeId: {
            in: [5, 3]
        },
        orderId: {
            in: [10266]
        },
    }
})
```

But if I move employeeId to the top, the other filters are ignored. Below, the output is again 42.

```
count({
    from: 'Orders',
    where: {
        employeeId: {
            in: [5, 3]
        },
        customerId: 87,
        orderId: {
            in: [10266]
        },
    }
})
```

But the very same query as above but using Select, I correctly get 1 row as expected:

```
select({
    from: 'Orders',
    where: {
        employeeId: {
            in: [5, 3]
        },
        customerId: 87,
        orderId: {
            in: [10266]
        },
    }
})
```

So I think the bug here is about using the "In" operator in the first filter field in the Count query.

I hope I was able to explain clearly.

Thanks for all the great work.

Related to #153.

**Comment by ujjwalguptaofficial** [comment]
Hey, thanks for great explanation. I am able to reproduce the issue, will fix it ASAP.

**Comment by ujjwalguptaofficial** [comment]
@alisabrigok i have fixed the issue in version - 4.3.9, please try and let me know.

**Comment by alisabrigok** [comment]
Thanks a lot for the super swift fix. I have tested and I can confirm that it's resolved. I would appreciate if you can update the deployed IDBStudio as well, I find it super handy to test things out. Thank you again for the great work 🙏

**Comment by ujjwalguptaofficial** [comment]
@alisabrigok have also updated idbstudio.
