### ISSUE TITLE
 Cannot read property 'then' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'then'

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#30]
Hi,

In online I can get the article from indexeddb.But in offline it shows then of undefined error while fetching data in offline.Before it was fine.(previous version).pls help me to fix it.today is my project demo.Now its not working

Thanks

**Comment by ujjwalguptaofficial** [comment]
well the error says - you are not returning promise from the function you are calling .

e. g -  if you are calling function select article 

```
function selectArticle()
{
     connection.select(query); // this will give error
     return connection.select(query) // this should work
}
```

**Comment by ujjwalguptaofficial** [comment]
Is it happening in select query ?

**Comment by ujjwalguptaofficial** [comment]
paste here both the service code and component code.

**Comment by kamalakkanni** [comment]
my service code

 //Fetch articles From IndexedDB
    GetArticleFromIndexedDb(section, subsequent) {
     
        if (subsequent==false) {
            this._connection.openDb(this._indexedDBLiveDBName);
            return this._connection.select({
                From: this._indexedDBLiveDBArticleTableName,
                Where: {
                    CustomSection: section
                }
            });
        }
        else {
            let count=this._subsequentArticleCount;
         if(subsequent=="Detail")
         count=this._detailsubsequentArticleCount;
         if(
            (screen.width <= 640) || 
            (window.matchMedia && 
             window.matchMedia('only screen and (max-width: 640px)').matches
            )
          ){
           if(subsequent=="Detail")
           count=this._detailsubsequentArticleCount
           else
           count=environment.otherSectionCountForMobile;
          }
            this._connection.openDb(this._indexedDBLiveDBName);
            return this._connection.select({
                From: this._indexedDBLiveDBArticleTableName,
                Where: {
                    CustomSection: section
                },
                Limit: count
            });
        }
      
    }

my component code

  if (this._service.updateContent && this._service._isInserted != true) {

          this.CallGetArticleDetails();
        }
        else {
          this.CallGetArticleDetailsFromIndexedDB();
        }
      }
        else {
          this.CallGetArticleDetailsFromIndexedDB();
        }

**Comment by ujjwalguptaofficial** [comment]
I don't see calling of  "GetArticleFromIndexedDb" in component. Can you give me the code where you are calling the "GetArticleFromIndexedDb" in component.

**Comment by kamalakkanni** [comment]
I updated

**Comment by ujjwalguptaofficial** [comment]
Actually its hard to tell where its failing. Can you revert back to previous version and see if its working ?

**Comment by kamalakkanni** [comment]
sorry.It is not fault in version.Its in my code.I have put check for dbcreated.before selecting.that check variable value is false.so that I am getting this error

**Comment by kamalakkanni** [comment]
now,I removed that error and working fine
