### ISSUE TITLE
Array aggregation

### ISSUE THREAD

**Issue by MaxEtMoritz** [ujjwalguptaofficial/JsStore#307]
## Summary

It would be great if there is an aggregation type `array` that groups all values into an array column.

The current aggregation types mostly make sense for numerical data only (except `count`) but are pretty useless for e.g. strings and will fail for generic object columns.

### Basic example

e.g. in Demo Database:

Wanting to join Customers with Orders while aggregating the order ID for each customer to an array.

(in that example one would probably want to go on joining Order with OrderDetails with Products and e.g. get a list of product names each customer has ordered, but that would be a bit too many joins for a simple example...)

even though the data is numerical in this case, summing up IDs etc. is also pretty useless.

[see IDBStudio](https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20%22from%22%3A%20%22Customers%22%2C%0A%20%20%20%20join%3A%7B%0A%20%20%20%20%20%20%20%20with%3A%20'Orders'%2C%0A%20%20%20%20%20%20%20%20on%3A%20'Customers.customerId%3DOrders.customerId'%0A%20%20%20%20%7D%2C%0A%20%20%20%20groupBy%3A%20'customerId'%2C%0A%20%20%20%20aggregate%3A%7B%0A%20%20%20%20%20%20%20%20count%3A%20'orderId'%0A%20%20%20%20%20%20%20%20%2F%2F%20array%3A%20'orderId'%20would%20be%20great%20here%0A%20%20%20%20%7D%0A%7D)%3B)

### Motivation

I have a one-to-many relationship between two tables and would like to join them, aggregating a column of string values to a string array.

**Comment by ujjwalguptaofficial** [comment]
So you want `orderIds` value in an array right ?

**Comment by ujjwalguptaofficial** [comment]
added in v- 4.5.0 @MaxEtMoritz . Thanks for the well explanation - I think this is going to be an amazing feature although it is small. 

Please check and confirm if its working well.

**Comment by MaxEtMoritz** [comment]
Thanks for adding it, works good in the demo database.

wanted to test it out on my use case, but since the tables i planned to join are quite large i wanted to join with a limit to get a faster result. but what happened was that the join seems to not respect the set limit, so used up all the RAM and i got no result at all.

but i will open a different issue for this.
