### ISSUE TITLE
JsStore does not work without web worker

### ISSUE THREAD

**Issue by excitedelektron** [ujjwalguptaofficial/JsStore#309]
# Title 

JsStore does not work without web worker

# Description 

I am trying to run the minimal version (without workers) verbatim from the official documentation but even that doesn't work:
I am getting:

jsstore.js:549 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'run')
    at Connection.sendRequestToWorker_ (jsstore.js:549:31)
    at Connection.executeQry_ (jsstore.js:522:22)
    at Connection.prcoessExecutionOfQry_ (jsstore.js:508:14)
    at jsstore.js:495:23

![image](https://user-images.githubusercontent.com/6664899/208252952-48384162-1f7b-4b56-a435-43e4750c63ab.png)

I am using vanilla Javascript with jsstore v4.5.0

Here is my code:

```
async function minimalExample() {


    var connection = new JsStore.Connection();

    var dbName = 'JsStore_Demo';
    var tblProduct = {
        name: 'Product',
        columns: {
            id: { primaryKey: true, autoIncrement: true },
            itemName: { notNull: true, dataType: "string" },
            price: { notNull: true, dataType: "number" },
            quantity: { notNull: true, dataType: "number" }
        }
    };
    var database = {
        name: dbName,
        tables: [tblProduct]
    }


    const isDbCreated = await connection.initDb(database);
    if (isDbCreated === true) {
        console.log("db created");
    }
    else {
        console.log("db opened");
    }

    var value = {
        itemName: 'Blue Jeans',
        price: 2000,
        quantity: 1000
    }

    var insertCount = await connection.insert({
        into: 'Product',
        values: [value]
    });

    console.log(`${insertCount} rows inserted`);
}
```

Note: Description should contains the query, the current output & the expected output. You can use idbstudio to generate the example.

**Comment by ujjwalguptaofficial** [comment]
@excitedelektron are you including jsstore worker file ?

**Comment by LeoZxy** [comment]
I met the same error, 
I create new connection without using 
new Connection(new Worker(workerPath))
I just new Connection()
then the error display like this
err TypeError: Cannot read properties of undefined (reading 'run')
    at ConnectionHelper2.sendRequestToWorker_ (connection_helper.ts:263:25)
    at ConnectionHelper2.executeQry_ (connection_helper.ts:234:14)
    at ConnectionHelper2.prcoessExecutionOfQry_ (connection_helper.ts:212:10)
    at connection_helper.ts:198:14
![Screenshot 2022-12-20 at 11 05 26](https://user-images.githubusercontent.com/96618210/208572056-33a65d27-9578-4380-b960-8d3cfbcaef98.png)

**Comment by ujjwalguptaofficial** [comment]
getWorkerPath use file-loader to move the worker script  to `build` folder and return the path of that file, so that you can use in Worker.

```
const worker = new Worker(<worker file path>)
```

**Comment by ujjwalguptaofficial** [comment]
@LeoZxy @excitedelektron can you guys provide me a reproducable repo, so that i can help you guys.

**Comment by LeoZxy** [comment]
Hi @ujjwalguptaofficial  @excitedelektron 

I think we forget to add this code below

coonection.addPlugin(workerInjector)

now its seems working.

**Comment by ujjwalguptaofficial** [comment]
@excitedelektron hope your issue is also fixed, but if not please provide a reproducable repo - i am always there to help.

For now i am closing the issue.
