### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by zakaria-chahboun** [ujjwalguptaofficial/JsStore#310]
I have this errors:
```
ReferenceError: self is not defined
jsstore@4.5.0/node_modules/jsstore/dist/jsstore.commonjs2.js:352:36
jsstore@4.5.0/node_modules/jsstore/dist/jsstore.worker.commonjs2.js:1184:17
```
I believe webpack has set it as self for a certain reason. But in order to work on browser and node you can simply switch to this:

```js
output: {
  // ...
  globalObject: 'this',
},
```

**Comment by ujjwalguptaofficial** [comment]
@zakaria-chahboun i can understand why this issue ? but this should not occur in browser environment. Can you tell me where you are using this and more info about your app.

**Comment by zakaria-chahboun** [comment]
@ujjwalguptaofficial in `SvelteKit` framework, the code is running in both server-side and client-side! can you do something for that? Thanks! :tulip:

**Comment by ujjwalguptaofficial** [comment]
@zakaria-chahboun indexedd is client side tech, so in server it won't execute. Do something to make sure it runs inside only client only.

somthing like 

```
if(isClient){
   executeJsStore();
}
```
Hope this make sense.

**Comment by zakaria-chahboun** [comment]
i already did that by 
```js
import { browser } from '$app/environment';
if(brower){
// .....
}
```
and it's work fine, But if you can just eliminate the `worker`.

some libraries  support `SSR` even if it works only in the browser. if you can do that it will be good for SSR frameworks!
