### ISSUE TITLE
initDb throwing error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'run')

### ISSUE THREAD

**Issue by croraf** [ujjwalguptaofficial/JsStore#311]
# Title 
initDb throwing error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'run')

# Description 

Browser: Chrome Version 108.0.5359.124 (Official Build) (64-bit)

I'm creating a Connection without providing the worked. Am using create-react-app framework. 

codesandbox: https://codesandbox.io/s/jsstore-bug-p8g7u0?file=/src/App.tsx

```ts
import { useEffect, useState } from "react";
import * as JsStore from "jsstore";

const chatHistoryTable = {
  name: "chatHistory",
  columns: {
    id: { primaryKey: true, dataType: "string" },
    networkName: { dataType: "string" },
    channelName: { dataType: "string" },
    // message: { dataType: "object" },
  },
};
const database = {
  name: "irc-rafa",
  tables: [chatHistoryTable],
};

let connection: JsStore.Connection;

export const useIndexedDb = () => {
  const [connected, setConnected] = useState(false);
  useEffect(() => {
    connection = new JsStore.Connection();
    connection.initDb(database).then(() => {
      setConnected(true);
      console.log("db opened");
    });
  }, []);

  return connected;
};
```

It is throwing this error
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'run')

![image](https://user-images.githubusercontent.com/19698636/211141073-3a25b58c-2033-4f47-95c7-e76e471379d1.png)

**Comment by croraf** [comment]
I saw similar issues #309 #298 but they have been closed without actual resolution.

**Comment by ujjwalguptaofficial** [comment]
@croraf you will have to include the jsstore worker script or use injector plugin. Here is doc - https://jsstore.net/tutorial/connection/#webpack-without-web-worker

**Comment by croraf** [comment]
Thanks it is working now.
