### ISSUE TITLE
Can't reset auto_increment field

### ISSUE THREAD

**Issue by umer-prjmarker** [ujjwalguptaofficial/JsStore#314]
## Summary

Clear() function does empty the table but a flag should be passed as parameter to reset the auto_increment sequence.

### Basic example

await connection.clear(table_name, reset_auto_increment = false);

### Motivation

I need to clear table's data as well as resetting auto increment so the field doesn't get overflow or impact performance due to bulk of data has been cleared.

**Comment by ujjwalguptaofficial** [comment]
Ok, by default it should reset the auto increment. Let me check and get back to you.

**Comment by ujjwalguptaofficial** [comment]
I checked auto increment is always reset to zero when clearing. I also added some test cases.

**Comment by ujjwalguptaofficial** [comment]
yeah that's the latest version, please check and let me know.

**Comment by ujjwalguptaofficial** [comment]
closing, feel free to reopen if required.
