### ISSUE TITLE
Uncaught Error: JsStoreWorker not found

### ISSUE THREAD

**Issue by yibhou** [ujjwalguptaofficial/JsStore#316]
version upgraded from v4.5.0 to v4.5.1, but throw exception below:

![image](https://user-images.githubusercontent.com/10102594/223073784-25d627de-4659-4698-a097-59cf779078c2.png)

**Comment by yibhou** [comment]
yes, work well.

**Comment by ujjwalguptaofficial** [comment]
found it - fixing

**Comment by ujjwalguptaofficial** [comment]
fixed in v - 4.5.2. Please check and let me know.
