### ISSUE TITLE
JsStore.isDbExist doesn't work if you haven't create an instance JsStore.Instance

### ISSUE THREAD

**Issue by Slaaptrol** [ujjwalguptaofficial/JsStore#32]
The working of JsStore.isDbExist should't be dependent on logic outside this function but self contained
Now i always have to create an instance of JsStore.Instance before i call JsStore.isDbExist:
 ```
const instance  = new JsStore.Instance();
 JsStore.isDbExist('my database').then(..);
```
while it should be working without  `const instance  = new JsStore.Instance();`

**Comment by ujjwalguptaofficial** [comment]
Hi @Slaaptrol - you are right. This issue will be solved in version 2 of jsstore. I have already started working on v2.

**Comment by ujjwalguptaofficial** [comment]
@Slaaptrol - the problem is solved in v2. Now you can call isDbExist with instance object. Please have a look at examples in examples folder.

Thanks
