### ISSUE TITLE
Mismatch in interface between schema returned by JsStore.getDbSchema and interface IDataBaseOption

### ISSUE THREAD

**Issue by Slaaptrol** [ujjwalguptaofficial/JsStore#33]
The fields defined by IDataBaseOption don't match with the fields in the schema returned by JsStore.getDbSchema. All the fields in IDataBaseOption  are UpperCamelCase (should also be lowerCamelCase according to the javascript code styling guide) while the fields of the object returned by JsStore.getDbSchema are prefixed with an underscore. For example _name or _tables instead of Name or Tables as defined by the interface IDataBaseOption

**Comment by ujjwalguptaofficial** [comment]
ok, I will solve this out asap.

Thanks

**Comment by ujjwalguptaofficial** [comment]
Hi - this problem is solved in jsstore- v2. Please have a look at examples in examples folder.

Thanks
