### ISSUE TITLE
I now need to do three-end compatibility

### ISSUE THREAD

**Issue by xuyongweb** [ujjwalguptaofficial/JsStore#334]
### Discussed in https://github.com/ujjwalguptaofficial/JsStore/discussions/333

<div type='discussions-op-text'>

<sup>Originally posted by **xuyongweb** July 11, 2023</sup>
 jsstore for web side, sqlite for ios and Android, if the sqlite query statement passed into sqlweb, can I get the same query result</div>

**Comment by ujjwalguptaofficial** [comment]
nope, its like using mysql and postgresql - both uses sql but with different syntax. SqlWeb supports sql syntax but in its own flavour.
