### ISSUE TITLE
async call for api while inserting data into indexeddb

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#34]
Hi,

I am calling multiple api and inserting all my response data into indexeddb .After this process completion only,my other process are running.Can I make it async method.pls help me

Thanks

**Comment by ujjwalguptaofficial** [comment]
Well you are calling in Promise which means - it is async. So you can run other processes without waiting except that you want to do something after the promise has been resolved.

See the example below -

```
Con.select({
  From:'table'
}).then(function(){
// now you are waiting the process to be complete
console.log('hi');
})

But 

Con.select({
  From:'table'
})
// now below method will be executed , without waiting for completion.
console.log('hi'); 

```

**Comment by kamalakkanni** [comment]
Thanks,It is for selecting data from indexeddb right.But I need to select data from api and insert into indexeddb.this insertion should not affect others

**Comment by ujjwalguptaofficial** [comment]
I think you mean something different ? Please add some code or more explnation or add a link to a github project. You can create some demo and let us know what you want there.

Currently i dont understand what your problem is

**Comment by kamalakkanni** [comment]
GetAllApiDataAndStoreIntoIndexedDb()
{
 this.GetMostFromApi(SectionName).
                subscribe(
                res => {
                  this._allSectionArticles = [];
                  this.StoreResponseIntoIndexedDB(res, "MostRead");
                },
                error => this.PostErrorLog(<any>error));
            }
            if (SectionName.toLowerCase() == ("topnews")) {
              this.GetTopFromApi().
                subscribe(
                res => {
                  this._allSectionArticles = [];
                  this.StoreResponseIntoIndexedDB(res,SectionName);
                },
                error => this.PostErrorLog(<any>error));

................................
}
StoreResponseIntoIndexedDB(res,section)
{
 this.InsertSavedIntoIndexedDB(res).then(res => {
doing some operation
});
}


I called this service method in ngAfterViewInit(),In ngOnInit() ,I will call my api data fetching method.These should run asynchronously

**Comment by kamalakkanni** [comment]
I mean after inserting into indexeddb only ,fetching of data from api is working

**Comment by ujjwalguptaofficial** [comment]
I am working on version 2 - i will add something to control execution.

**Comment by kamalakkanni** [comment]
Hi,

Insertion should be run in background.That time i want to do other operations like page navigation swiping web api calls etc.My problem is not about selecting data from indexeddb only insertion.I am fetching data from web api and storing into indexeddb for all pages.in homepage itself.Then only I will fetch data from indexeddb for other pages

**Comment by ujjwalguptaofficial** [comment]
You mean insertion is affecting others functions right ?

**Comment by kamalakkanni** [comment]
yes

**Comment by ujjwalguptaofficial** [comment]
I think you are doing something different - 

1. IndexedDb is async.
2. jsstore is also async .
3. jsstore provides feature to execute in web worker, which means - no matter you are inserting, selecting : it wont affect dom features like navigation etc.

try to find if you are doing anything wrong. My guess will be - its not executing in web worker.

**Comment by kamalakkanni** [comment]
ok.thanks.can make api calls as async

**Comment by ujjwalguptaofficial** [comment]
Hi - This is out of context. I cant help you related to anything except jsstore.

Fyi - jsstore v2 is released. So you should start using it as it solves many problems like building with angular, full ts support, getting intillisense etc.  If you want to use it - have a look at examples in examples folder.

Thanks.
