### ISSUE TITLE
keyPath incompatible with AND logic

### ISSUE THREAD

**Issue by HongliangQiu** [ujjwalguptaofficial/JsStore#341]
# Title 
keyPath incompatible with AND logic

# Description 
JsStore could not select data when I use two where condition which include an "KeyPath".

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%27Customers%27%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20countryCity%3A%20%5B%22Germany%22%2C%20%22Berlin%22%5D%2C%0A%20%20%20%20%20%20%20%20or%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20countryCity%3A%20%5B%22UK%22%2C%20%22London%22%5D%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)&drop=true

![image](https://github.com/ujjwalguptaofficial/JsStore/assets/33348833/f15f0ff5-d2ec-474d-a6b6-f93fc0f69fa1)

**Comment by ujjwalguptaofficial** [comment]
fixed in v - 4,6.1. Please check and let me know.

**Comment by HongliangQiu** [comment]
It is ok now.
Thank you.
