### ISSUE TITLE
Working with dates

### ISSUE THREAD

**Issue by Mc128k** [ujjwalguptaofficial/JsStore#36]
Hi
I'm integrating this library into my project, and it works pretty well for my use. One of the thing that I see missing though is some date/time support. I understand that it's an advanced SQL topic, and it's reasonable to not include this in a small library that runs on a browser, but indeed I am facing a problem that is proving hard to solve. 

How do I select a date range? The currently available operators can obviously work on integers, but nothing is documented on other data types. If I had some kind of functions like DAY() or the like (like SQL) the problem could be easily solved, but this is just a plain query system.

Any suggestion?
Thanks a lot

**Comment by Mc128k** [comment]
I might add that I use ISO strings as dates. After some thinking I can say that a reasonable solution is using the seconds-after-epoch approach or something like this as a workaround, it requires a conversion layer when importing, but it's fine. Any better ideas?

**Comment by ujjwalguptaofficial** [comment]
You can save date as js date type, and query using between operator. The only thing you need to make sure - to convert your string back into js date object.

Check out this link for more - https://www.raymondcamden.com/2013/06/06/IndexedDB-and-Date-Example/

**Comment by Mc128k** [comment]
Cool, it would be useful to document it. This solution or the UNIX timestamps can work.

**Comment by ujjwalguptaofficial** [comment]
We have added new datatype -DateTime. So just declare the data type and jsstore will take care of rest.

Here is the link - http://jsstore.net/tutorial/enums/

Thanks
