### ISSUE TITLE
Type Typo issue

### ISSUE THREAD

**Issue by yusa-imit** [ujjwalguptaofficial/JsStore#361]
# Title 

ITransactionQuery typo issue

# Description 

<img width="92" alt="image" src="https://github.com/ujjwalguptaofficial/JsStore/assets/43007994/5fb95702-1c75-41fa-abfc-797c1a7e8115">

I think the type `ITranscationQuery` which query type for `transaction` has typo issue.
It'll be `ITransactionQuery`

Note: Description should contains the query, the current output & the expected output. You can use idbstudio to generate the example.

**Comment by ujjwalguptaofficial** [comment]
Fixed in v - 4.7.3.
