### ISSUE TITLE
count function has a serious bug: where conditions are not be use correct.

### ISSUE THREAD

**Issue by HongliangQiu** [ujjwalguptaofficial/JsStore#364]
count({
    from: "Customers",
    where: {
        customerId: {
            ">=": 1,           // only this works.
            "<=": 5            // does not work.
        }
    }
})

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=count(%7B%0A%20%20%20%20from%3A%20%22Customers%22%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20customerId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22%3E%3D%22%3A%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22%3C%3D%22%3A%205%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)

![image](https://github.com/ujjwalguptaofficial/JsStore/assets/33348833/4288d256-c511-45fa-a5bb-6f4096098db9)

**Comment by HongliangQiu** [comment]
![image](https://github.com/ujjwalguptaofficial/JsStore/assets/33348833/c0b81c4d-9d33-4863-b3d5-1c2a6b03c02b)

**Comment by ujjwalguptaofficial** [comment]
Thanks for reporting, let me see and solve.

**Comment by ujjwalguptaofficial** [comment]
This is fixed in v- 4.7.4.
