### ISSUE TITLE
is there any way to use for Chrome-Extension-of-Manifest-V3？

### ISSUE THREAD

**Issue by reedjones** [ujjwalguptaofficial/JsStore#373]
### Discussed in https://github.com/ujjwalguptaofficial/JsStore/discussions/250

<div type='discussions-op-text'>

<sup>Originally posted by **Achi-Z** October 28, 2021</sup>
is there any way to use for Chrome-Extension-of-Manifest-V3？</div>

**Comment by ujjwalguptaofficial** [comment]
We will create an example for this.

**Comment by ujjwalguptaofficial** [comment]
Here is a repo for using jsstore in chrome extension - https://github.com/dd3v/favbox/tree/master/src/storage
