### ISSUE TITLE
EINVALIDTAGNAME error within installation

### ISSUE THREAD

**Issue by Maks-Yaremenko** [ujjwalguptaofficial/JsStore#4]
Hello. First of all thanks for your good job. 
Could you please look at this error - I got it within the installation. 
thx

node: v8.3.0
os: linux lts 16.0.4
npm v: 5.3.0
log file:
`0 info it worked if it ends with ok
1 verbose cli [ '/home/maksim/.nvm/versions/node/v8.3.0/bin/node',
1 verbose cli   '/home/maksim/.nvm/versions/node/v8.3.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'jsstore',
1 verbose cli   '--save' ]
2 info using npm@5.3.0
3 info using node@v8.3.0
4 verbose npm-session 73935b444fd003ba
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/jsstore 663ms (from cache)
8 silly pacote tag manifest for jsstore@latest fetched in 681ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule jsstore@1.2.2 checking installable status
14 verbose stack Error: Invalid tag name "typescript@latest": Tags may not have any characters that encodeURIComponent encodes.
14 verbose stack     at invalidTagName (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:76:15)
14 verbose stack     at fromRegistry (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:265:13)
14 verbose stack     at Function.resolve (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:66:12)
14 verbose stack     at childDependencySpecifier (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/lib/install/deps.js:80:14)
14 verbose stack     at addDependency (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/lib/install/deps.js:518:15)
14 verbose stack     at /home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/lib/install/deps.js:468:5
14 verbose stack     at /home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
14 verbose stack     at Array.forEach (<anonymous>)
14 verbose stack     at /home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
14 verbose stack     at Array.forEach (<anonymous>)
14 verbose stack     at asyncMap (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
14 verbose stack     at loadDeps (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/lib/install/deps.js:460:3)
14 verbose stack     at Array.<anonymous> (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
14 verbose stack     at LOOP (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
14 verbose stack     at chain (/home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
14 verbose stack     at /home/maksim/.nvm/versions/node/v8.3.0/lib/node_modules/npm/lib/install/deps.js:355:5
15 verbose cwd /home/maksim/Documents/_projects/peopling/peopling-frontend
16 verbose Linux 4.10.0-35-generic
17 verbose argv "/home/maksim/.nvm/versions/node/v8.3.0/bin/node" "/home/maksim/.nvm/versions/node/v8.3.0/bin/npm" "install" "jsstore" "--save"
18 verbose node v8.3.0
19 verbose npm  v5.3.0
20 error code EINVALIDTAGNAME
21 error Invalid tag name "typescript@latest": Tags may not have any characters that encodeURIComponent encodes.
22 verbose exit [ 1, true ]`

**Comment by Maks-Yaremenko** [comment]
after downgrade node version I got a different error, but also with typescript
npm@3.10.10
node@v6.11.2
[npm-debug.log](https://github.com/ujjwalguptaofficial/JsStore/files/1414036/npm-debug.log)

**Comment by ujjwalguptaofficial** [comment]
Thank you very much for your appreciation - @Maks-Yaremenko. I think - its the npm package dependencies issue, I will fix this asap.

for now, you can try  the old version - npm install jsstore@1.2.1 . Hope this helps.

**Comment by ujjwalguptaofficial** [comment]
Issue is resolved. Now you can use the JsStore latest version. Let me know if it is not working for you.

**Comment by Maks-Yaremenko** [comment]
hello again! thank for a quick response. The issue is resolved, but there some small things that I would like to let you know, I think it helps make your library better!)
1. you forgot to upgrade file version to 1.2.3 =)
2. i use linux its case sensitive so JsStrore not the same as jsstore, this applies to your example

in your demo: `import { Instance } from 'JsStore';`
in my case: `import { Instance } from 'jsstore';`

in your demo: `../node_modules/jsstore/dist/jsstore-1.2.1.min.js`;
in my case: `["../node_modules/jsstore/Dist/JsStore-1.2.2.min.js"]`

also, demo file index.html doesn't run correctly by same reasons. 
linux cant resolve path if it not 100% match. 

Hope this information will be useful for you and in general for anyone. 

Thx for your great job, good documentation and library. 
Have a nice day! Keep going make this world better! Regards, thx

**Comment by ujjwalguptaofficial** [comment]
I got it buddy. Thanks for letting us know. I will run the code again on Linux and fix every issue. So that any one using Linux can use this.

**Comment by ujjwalguptaofficial** [comment]
We have solved the issue with example code. Regarding the demo with angular2, actually npm does not allow the publish the files with other than lowercase, so I have to made the file name in lower case.

Thanks for your contribution @Maks-Yaremenko , let me know if I can help you with anything else.
