### ISSUE TITLE
Wrong selection when dealing with null values

### ISSUE THREAD

**Issue by Mc128k** [ujjwalguptaofficial/JsStore#40]
Hi again
During development, I found that this query produces a wrong selection:
```
        {
            From: 'Job',
            Where: {
              jobSuspended_flag: { '!=': 1 },
              state: {
                In: ['Working', 'Diagnostics', 'FinalTest']
              }
            }
```

The records have the `jobSuspended_flag` set to 1, but they are selected anyway. There can be two values for this field, 1 or null.

If I change the row to this:
```
jobSuspended_flag: null
```

It throws an error:
```
scripts.bundle.js:3 TypeError: Cannot read property '!=' of null
    at scripts.bundle.js:3
    at Array.every (<anonymous>)
    at e.containsNot (scripts.bundle.js:3)
    at e.addGreatAndLessToNotOp (scripts.bundle.js:3)
    at e.execute (scripts.bundle.js:3)
    at Main.select (scripts.bundle.js:3)
    at Main.executeLogic (scripts.bundle.js:3)
    at Main.checkConnectionAndExecuteLogic (scripts.bundle.js:3)
    at e.executeCodeDirect (scripts.bundle.js:3)
    at e.executeCode (scripts.bundle.js:3)
```

I'm currently trying to understand JSStore's code in order to debug these problems myself (and maybe posting pull requests), but the way it's structured makes it hard for me. Also there are some type bugs, for example declaring the Promise as any in CodeExecutionHelper.ts makes the compiler angry:

```
ERROR in node_modules/JsStore/dist/jsstore.d.ts(1051,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'Promise' must be of type 'PromiseConstructor', but here has type 'any'.
src/app/@core/data/db.service.ts(2,26): error TS2306: File '/Users/mc128k/Dropbox/Projects/TRIAD/99 Web Apps/40 TRIAD_Dashboard/node_modules/JsStore/dist/jsstore.d.ts' is not a module.chunk
```
but the issue here is with the selection. I'm trying to figure out these by myself, just wanted to let you know.

**Comment by Mc128k** [comment]
By the way, the last error is because the latest build lacks the default export for the `.d.ts` typescript module, while the production version is ok

**Comment by ujjwalguptaofficial** [comment]
So you are saying that you are getting result with job_suspendedflag:1 right ?

**Comment by Mc128k** [comment]
Yes, I logged the found records and I see that some have the flag set to 1 (number)

**Comment by ujjwalguptaofficial** [comment]
Let me know others issue if you found please and any others improvement if you like to include in v2.

Thanks

**Comment by Mc128k** [comment]
I see that v2 has code that is A LOT better. Good job, this is something I can handle somehow.

**Comment by Mc128k** [comment]
I can confirm the issue exists in version 2.0.3

**Comment by Mc128k** [comment]
Reproduced successfully. See the attached files for the demo database and the query for the test:
```
select({
    from: 'Orders',
    where: {
      jobSuspended_flag: {'!=': 1},
      state: {
        in: ['Working', 'Diagnostics', 'FinalTest'],
      },
    },
})
```
[Orders.json.txt](https://github.com/ujjwalguptaofficial/JsStore/files/1998842/Orders.json.txt)

[demo_service.ts.txt](https://github.com/ujjwalguptaofficial/JsStore/files/1998843/demo_service.ts.txt)

**Comment by ujjwalguptaofficial** [comment]
@Mc128k - issue is resolved in version 2.0.5.Let me know if you are getting this any more.

Thanks.

**Comment by ujjwalguptaofficial** [comment]
Here is the link for testing in idbstudio - https://ujjwalguptaofficial.github.io/idbstudio/?query=select(%7B%0A%20%20%20%20from:%27Employees%27,%0A%20%20%20%20where:%20%7B%0A%20%20%20%20%20%20jobSuspendedFlag:%20%7B%27!=%27:%200%7D,%0A%20%20%20%20%20%20state:%20%7B%0A%20%20%20%20%20%20%20%20in:%20%5B%27Working%27,%20%27Diagnostics%27,%20%27FinalTest%27%5D,%0A%20%20%20%20%20%20%7D,%0A%20%20%20%20%7D%0A%7D)&db=Demo

**Comment by Mc128k** [comment]
Indeed it seems to be working! Thanks a lot!!
