### ISSUE TITLE
Bug when opening database [v2]

### ISSUE THREAD

**Issue by Mc128k** [ujjwalguptaofficial/JsStore#41]
Hi,
I'm playing with the version 2, and I think I understand how to handle it. I compiled it with webpack and placed the worker.js file in my project. For the main instance I'm referring the .ts files from my project, so I have the compiled worker and the native .ts imported from my project. I hope it's clear.

One thing I can't figure out is that in the worker, as soon as I try to open the database, I get an error where the dbName_ variable is undefined. I think it could be because the class is initialised before the IdbHelper actually has the data. This is the error:
![screen shot 2018-05-02 at 15 15 43](https://user-images.githubusercontent.com/3678359/39525402-29ffa302-4e1c-11e8-825e-252c53d5a24c.png)

And my code:
```
return this._conn.isDbExist(this._dbName)
      .then(exist => {
        if (exist) {
          this._conn.openDb(this._dbName); // <- fails after this
        } else {
          this._conn.createDb({
            name: this._dbName,
            tables: [{
              name: this._tableName,
              columns: [{
                name: 'id',
                primaryKey: true,
              }],
            }],
          });
        }
      })
```

Any clue?

**Comment by ujjwalguptaofficial** [comment]
I cant say whats the issue - it might be build issue or something else. I have created a example for using webpack in example folder for v2 and everything was working cool.

So please check the webpack example and in order to make it working - 

1. install jsstore
2. grab all files from webpack example-> node_modules ->jsstore and copy this into same location into your project.

Let me know if you are getting problem after this.

Thanks

**Comment by Mc128k** [comment]
Ok, I'll try. I'm having a hard time getting it to work, but I'll do everything I can before posting

**Comment by ujjwalguptaofficial** [comment]
Its ok, take it light. Since v2 is not published yet, we need to fix every possible problem before publishing. Please let me know if its working for you.

Thanks

**Comment by Mc128k** [comment]
I looked into the webpack directory, and I found the compiled worker in dist/scripts. Copying this into my project fails as the other one.
Why do you tell me to copy the one in node_modules? The package.json file tells to install the old version of JsStore inside node_modules, so I would be copying v1 instead of v2.

**Comment by ujjwalguptaofficial** [comment]
oh sorry, I forgot I am not commiting node_modules folder. Actually in my local I have setup v2 code to work as node_modules that's why I told you. 

Lets talk on gitter.

**Comment by Mc128k** [comment]
The problem was because of existing v1 data. Clearing the indexeddb database fixed it
