### ISSUE TITLE
In v2 Cannot find module 'file-loader?name=scripts/[name].[hash].js!jsstore/dist/jsstore.worker.min.js';

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#46]
Hi,

I referred your example https://github.com/ujjwalguptaofficial/JsStore/blob/master/examples/angular/my-app/src/app/service/idb.service.ts

here you imported webworkerpath from jsstore.worker.min.js.It gives cannot find module error.

Then I placed it  assets and imported then also i am getting error.What is wrong here. pls help me

Thanks

**Comment by ujjwalguptaofficial** [comment]
Hi

Check it out the extra folder there is a file with worker.d.ts , copy the
extra folder into your project directory. That will resolve the error.

**Comment by ujjwalguptaofficial** [comment]
File loader is a webpack plugin which is used by angular. We are using
typescript definition file to make it work in typescript.

**Comment by kamalakkanni** [comment]
thanks,I copied extra folder .it resolves that error.But it gives    You may need an appropriate loader to handle this file type.


             this._connection =  = new JsStore.Instance(new Worker(workerPath));


in this line

**Comment by kamalakkanni** [comment]
hi,
Property 'Birthdate' does not exist on type '{}' I changed all keywords like Select,Distinct,Like  as select,distinct,like.but It gives all my properties not exist which are good in v1

below is my code

 this.GetArticleFromIndexedDb(section, false).then(res => {
 

        res.forEach((item) => {
    console.log( item.Birthdate)
});
});

**Comment by ujjwalguptaofficial** [comment]
Check out how to do select operation in example.

You need to send type with select  api.

Let me know if u are not able to find

Thanks

**Comment by kamalakkanni** [comment]
I saw and change my code as 

self._connection.openDb(self._indexedDBLiveDBName);
    return self._connection.select<Class>({
      from: table,
       where: { id :id}
    })

then also Iam getting same

**Comment by ujjwalguptaofficial** [comment]
Just one thing you need to pass - your model as type like -

select<Student>(
{from: tableName}
)

Where student is model and this way jsstore will know that return type is
Student and will return list of  students.

Hope this is making sense.

**Comment by kamalakkanni** [comment]
I passed like that only.But in gitub comment it is hidden

**Comment by kamalakkanni** [comment]
thanks.I passed as the same.But got same

**Comment by ujjwalguptaofficial** [comment]
Check out getStudents in student service -
https://github.com/ujjwalguptaofficial/JsStore/blob/master/examples/angular/my-app/src/app/service/student.service.ts

You can see that I am passing IStudent which is an interface which
represent student type. You can also pass your model class.

**Comment by kamalakkanni** [comment]
Its fixed now.Thanks.for number what datatype I have to use.In version 1 I didn't mention anytype.But here It ask for model.I got error

**Comment by ujjwalguptaofficial** [comment]
Good to know. Just Import DATA_TYPE and write DATA_TYPE. and intillisense
will give you all the available date.

By the way - for number : it will be DATA_TYPE.Number

Also make sure that you have all your data from V1.

Thanks

**Comment by kamalakkanni** [comment]
Below is my code .
self._connection.openDb(self._indexedDBLiveDBName);
    return self._connection.select<class>({
      from: self.tablename,
       where: { Id: Id}
    }).then(res => {
      if (res.length > 0) {
        let count =res[0].Count + 1;
        self._connection.openDb(self._indexedDBLiveDBName);
        return self._connection.update({
          in: self.tablename,
          set: { Count: count },
           where: { Id: Id}
        });
      }
      else {
        mostread.push({ ArticleId: articleId, Count: 1 });
        return self._connection.insert({
          into: self.mostReadArticleTable,
          values: mostread
        }).then(
          res => {

          });

      }
    }).catch(res => {
    });


which gives below error

message: 'Argument of type '(res: MostRead[]) => Promise<number> | Promise<void>' is not assignable to parameter of type '(value: MostRead[]) => number | PromiseLike<number>'.
  Type 'Promise<number> | Promise<void>' is not assignable to type 'number | PromiseLike<number>'.
    Type 'Promise<void>' is not assignable to type 'number | PromiseLike<number>'.
      Type 'Promise<void>' is not assignable to type 'PromiseLike<number>'.
        Types of property 'then' are incompatible.
          Type '<TResult1 = void, TResult2 = never>(onfulfilled?: (value: void) => TResult1 | PromiseLike<TResult...' is not assignable to type '<TResult1 = number, TResult2 = never>(onfulfilled?: (value: number) => TResult1 | PromiseLike<TRe...'.
            Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
              Types of parameters 'value' and 'value' are incompatible.
                Type 'void' is not assignable to type 'number'.'
at: '1102,13'
source: 'ts'
code: '2345'

**Comment by ujjwalguptaofficial** [comment]
Send type DATA_TYPE.Number in insert api same as you have done with select

FYI - insert should return inserted data when return is true otherwise no
of inserted data. So there is two types of data insert can return based on
different situation.

**Comment by kamalakkanni** [comment]
I am not getting.I changed insert api like below

   return self._connection.insert<`class`>({
          into: self.tablename,
          values: mostread
        }).then(
          res => {

          });

**Comment by kamalakkanni** [comment]
this is my compile time error
