### ISSUE TITLE
Worker is not defined in production in angular universal

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#47]
Hi,

I am using angular universal. I am getting "worker not defined" error in production .pls help me

Thanks

**Comment by ujjwalguptaofficial** [comment]
Can you add a screenshot of error ?

**Comment by kamalakkanni** [comment]
@ujjwalguptaofficial  ,I can't attach file here.Below is my error

PS D:\Live\universal-starter-master-correct\worked> npm run serve:ssr

> worked@0.0.0 serve:ssr D:\Live\universal-starter-master-correct\worked
> node dist/server

D:\Live\universal-starter-master-correct\worked\dist\server.js:131453
!function(l,n){for(var e in n)l[e]=n[e]}(exports,function(l){var n={};function e(t){if(n[t])return n[t].exports;var i=n[t]={i:t,l:!1,exports:{}};return l[t].call(i.exports,i,i.exports,e),i.l=!0,i.exports}return e.m=l,e.c=n,e.d=function(l,n,t){e.o(l,n)||Object.defineProperty(l,n,{configurable:!1,enumerable:!0,get:t})},e.n=function(l){var n=l&&l.__esModule?function(){return l.default}:function(){return l};return e.d(n,"a",n),n},e.o=function(l,n){return Object.prototype.hasOwnProperty.call(l,n)},e.p="",e(e.s=0)}({"+ZWX":function(l,n,e){"use strict";var t=e("Sse8"),i=e("OQ0P"),o=e("6+M+"),u=e("XIMc"),r=e("ESuP"),a=e("A7Ap"),s=e("yv0u"),d=e("3cWk"),c=e("HER7"),p=e("nlmy"),m=e("rBb5"),f=e("knMA"),g=e("EGp1"),h=e("ECCM"),v=i.\u0275crt({encapsulation:0,styles:[t.styles],data:{}});function b(l){return i.\u0275vid(0,[(l()(),i.\u0275eld(0,0,null,null,1,"app-breaking-news",[],null,null,null,o.View_BreakingNewsComponent_0,o.RenderType_BreakingNewsComp

ReferenceError: Worker is not defined
    at D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:225821
    at Object.CuI+ (D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:225834)
    at e (D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:158)
    at Object.ESuP (D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:285302)
    at e (D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:158)
    at Object.wQAS (D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:655639)
    at e (D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:158)
    at Object.JwoV (D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:472257)
    at e (D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:158)
    at Object.Zq8w (D:\Live\universal-starter-master-correct\worked\dist\server.js:131453:535220)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! worked@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the worked@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kamalakkanniv\AppData\Roaming\npm-cache\_logs\2018-05-25T13_28_29_207Z-debug.log
PS D:\Live\universal-starter-master-correct\worked>

**Comment by ujjwalguptaofficial** [comment]
I think its a typescript issue. Please add webworker in lib in tsconfig.json that should solve the issue. Refer the below screenshot -

![image](https://user-images.githubusercontent.com/10938615/40597799-5b40023c-6261-11e8-94e3-021655f5ceec.png)

**Comment by kamalakkanni** [comment]
after adding this.I got 


 10% building modules 2/2 modules 0 activeNode#moveTo was deprecated. Use Container#append.
Date: 2018-05-28T06:31:24.077Z
Hash: e60d19ba727092a83467
Time: 12454ms
chunk {0} polyfills.08bc579cce135d57bf3a.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {1} main.ac12cef0639b0265a042.bundle.js (main) 84 bytes [initial] [rendered]
chunk {2} inline.088fae7297d67066d9b0.bundle.js (inline) 1.42 kB [entry] [rendered]

ERROR in node_modules/typescript/lib/lib.webworker.d.ts(1783,14): error TS2300: Duplicate identifier 'EventListenerOrEventListenerObject'.
node_modules/typescript/lib/lib.webworker.d.ts(1844,6): error TS2300: Duplicate identifier 'AlgorithmIdentifier'.
node_modules/typescript/lib/lib.webworker.d.ts(1845,6): error TS2300: Duplicate identifier 'BodyInit'.
node_modules/typescript/lib/lib.webworker.d.ts(1846,6): error TS2300: Duplicate identifier 'IDBKeyPath'.
node_modules/typescript/lib/lib.webworker.d.ts(1847,6): error TS2300: Duplicate identifier 'RequestInfo'.
node_modules/typescript/lib/lib.webworker.d.ts(1848,6): error TS2300: Duplicate identifier 'USVString'.
node_modules/typescript/lib/lib.webworker.d.ts(1849,6): error TS2300: Duplicate identifier 'IDBValidKey'.
node_modules/typescript/lib/lib.webworker.d.ts(1850,6): error TS2300: Duplicate identifier 'BufferSource'.
node_modules/typescript/lib/lib.webworker.d.ts(1851,6): error TS2300: Duplicate identifier 'FormDataEntryValue'.
node_modules/typescript/lib/lib.webworker.d.ts(1852,6): error TS2300: Duplicate identifier 'IDBCursorDirection'.
node_modules/typescript/lib/lib.webworker.d.ts(1853,6): error TS2300: Duplicate identifier 'IDBRequestReadyState'.
node_modules/typescript/lib/lib.webworker.d.ts(1854,6): error TS2300: Duplicate identifier 'IDBTransactionMode'.
node_modules/typescript/lib/lib.webworker.d.ts(1855,6): error TS2300: Duplicate identifier 'MediaKeyStatus'.
node_modules/typescript/lib/lib.webworker.d.ts(1856,6): error TS2300: Duplicate identifier 'NotificationDirection'.
node_modules/typescript/lib/lib.webworker.d.ts(1857,6): error TS2300: Duplicate identifier 'NotificationPermission'.
node_modules/typescript/lib/lib.webworker.d.ts(1858,6): error TS2300: Duplicate identifier 'PushEncryptionKeyName'.
node_modules/typescript/lib/lib.webworker.d.ts(1859,6): error TS2300: Duplicate identifier 'PushPermissionState'.
node_modules/typescript/lib/lib.webworker.d.ts(1860,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.
node_modules/typescript/lib/lib.webworker.d.ts(1861,6): error TS2300: Duplicate identifier 'RequestCache'.
node_modules/typescript/lib/lib.webworker.d.ts(1862,6): error TS2300: Duplicate identifier 'RequestCredentials'.
node_modules/typescript/lib/lib.webworker.d.ts(1863,6): error TS2300: Duplicate identifier 'RequestDestination'.
node_modules/typescript/lib/lib.webworker.d.ts(1864,6): error TS2300: Duplicate identifier 'RequestMode'.
node_modules/typescript/lib/lib.webworker.d.ts(1865,6): error TS2300: Duplicate identifier 'RequestRedirect'.
node_modules/typescript/lib/lib.webworker.d.ts(1866,6): error TS2300: Duplicate identifier 'RequestType'.
node_modules/typescript/lib/lib.webworker.d.ts(1867,6): error TS2300: Duplicate identifier 'ResponseType'.
node_modules/typescript/lib/lib.webworker.d.ts(1868,6): error TS2300: Duplicate identifier 'ServiceWorkerState'.
node_modules/typescript/lib/lib.webworker.d.ts(1869,6): error TS2300: Duplicate identifier 'VisibilityState'.
node_modules/typescript/lib/lib.webworker.d.ts(1870,6): error TS2300: Duplicate identifier 'XMLHttpRequestResponseType'.
node_modules/typescript/lib/lib.dom.d.ts(365,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'source' must be of type 'any', but here has type 'Window'.
node_modules/typescript/lib/lib.dom.d.ts(3465,5): error TS2375: Duplicate number index signature.
node_modules/typescript/lib/lib.dom.d.ts(3680,14): error TS2403: Subsequent variable declarations must have the same type.  Variable 'srcElement' must be of type 'any', but here has type 'Element'.
node_modules/typescript/lib/lib.dom.d.ts(3771,5): error TS2375: Duplicate number index signature.
node_modules/typescript/lib/lib.dom.d.ts(3827,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'FormData' must be of type '{ new (): FormData; prototype: FormData; }', but here has type '{ new (form?: HTMLFormElement): FormData; prototype: FormData; }'.
node_modules/typescript/lib/lib.dom.d.ts(7614,14): error TS2403: Subsequent variable declarations must have the same type.  Variable 'source' must be of type 'any', but here has type 'Window'.
node_modules/typescript/lib/lib.dom.d.ts(13364,14): error TS2403: Subsequent variable declarations must have the same type.  Variable 'responseXML' must be of type 'any', but here has type 'Document'.
node_modules/typescript/lib/lib.dom.d.ts(14224,14): error TS2300: Duplicate identifier 'EventListenerOrEventListenerObject'.
node_modules/typescript/lib/lib.dom.d.ts(14499,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'location' must be of type 'WorkerLocation', but here has type 'Location'.
node_modules/typescript/lib/lib.dom.d.ts(14505,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'navigator' must be of type 'WorkerNavigator', but here has type 'Navigator'.
node_modules/typescript/lib/lib.dom.d.ts(14532,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'onerror' must be of type '(this: DedicatedWorkerGlobalScope, ev: ErrorEvent) => any', but here has type 'ErrorEventHandler'.
node_modules/typescript/lib/lib.dom.d.ts(14544,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'onmessage' must be of type '(this: DedicatedWorkerGlobalScope, ev: MessageEvent) => any', but here has type '(this: Window, ev: MessageEvent) => any'.
node_modules/typescript/lib/lib.dom.d.ts(14615,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'self' must be of type 'WorkerGlobalScope', but here has type 'Window'.
node_modules/typescript/lib/lib.dom.d.ts(14691,6): error TS2300: Duplicate identifier 'AlgorithmIdentifier'.
node_modules/typescript/lib/lib.dom.d.ts(14692,6): error TS2300: Duplicate identifier 'BodyInit'.
node_modules/typescript/lib/lib.dom.d.ts(14714,6): error TS2300: Duplicate identifier 'IDBKeyPath'.
node_modules/typescript/lib/lib.dom.d.ts(14723,6): error TS2300: Duplicate identifier 'RequestInfo'.
node_modules/typescript/lib/lib.dom.d.ts(14724,6): error TS2300: Duplicate identifier 'USVString'.
node_modules/typescript/lib/lib.dom.d.ts(14728,6): error TS2300: Duplicate identifier 'IDBValidKey'.
node_modules/typescript/lib/lib.dom.d.ts(14729,6): error TS2300: Duplicate identifier 'BufferSource'.
node_modules/typescript/lib/lib.dom.d.ts(14732,6): error TS2300: Duplicate identifier 'FormDataEntryValue'.
node_modules/typescript/lib/lib.dom.d.ts(14743,6): error TS2300: Duplicate identifier 'IDBCursorDirection'.
node_modules/typescript/lib/lib.dom.d.ts(14744,6): error TS2300: Duplicate identifier 'IDBRequestReadyState'.
node_modules/typescript/lib/lib.dom.d.ts(14745,6): error TS2300: Duplicate identifier 'IDBTransactionMode'.
node_modules/typescript/lib/lib.dom.d.ts(14751,6): error TS2300: Duplicate identifier 'MediaKeyStatus'.
node_modules/typescript/lib/lib.dom.d.ts(14762,6): error TS2300: Duplicate identifier 'NotificationDirection'.
node_modules/typescript/lib/lib.dom.d.ts(14763,6): error TS2300: Duplicate identifier 'NotificationPermission'.
node_modules/typescript/lib/lib.dom.d.ts(14769,6): error TS2300: Duplicate identifier 'PushEncryptionKeyName'.
node_modules/typescript/lib/lib.dom.d.ts(14770,6): error TS2300: Duplicate identifier 'PushPermissionState'.
node_modules/typescript/lib/lib.dom.d.ts(14771,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.
node_modules/typescript/lib/lib.dom.d.ts(14772,6): error TS2300: Duplicate identifier 'RequestCache'.
node_modules/typescript/lib/lib.dom.d.ts(14773,6): error TS2300: Duplicate identifier 'RequestCredentials'.
node_modules/typescript/lib/lib.dom.d.ts(14774,6): error TS2300: Duplicate identifier 'RequestDestination'.
node_modules/typescript/lib/lib.dom.d.ts(14775,6): error TS2300: Duplicate identifier 'RequestMode'.
node_modules/typescript/lib/lib.dom.d.ts(14776,6): error TS2300: Duplicate identifier 'RequestRedirect'.
node_modules/typescript/lib/lib.dom.d.ts(14777,6): error TS2300: Duplicate identifier 'RequestType'.
node_modules/typescript/lib/lib.dom.d.ts(14778,6): error TS2300: Duplicate identifier 'ResponseType'.
node_modules/typescript/lib/lib.dom.d.ts(14800,6): error TS2300: Duplicate identifier 'ServiceWorkerState'.
node_modules/typescript/lib/lib.dom.d.ts(14803,6): error TS2300: Duplicate identifier 'VisibilityState'.
node_modules/typescript/lib/lib.dom.d.ts(14804,6): error TS2300: Duplicate identifier 'XMLHttpRequestResponseType'.

**Comment by ujjwalguptaofficial** [comment]
you can get relative path and add this to worker object. Check it out simple example - https://github.com/ujjwalguptaofficial/JsStore/tree/master/examples/Simple%20Example

**Comment by ujjwalguptaofficial** [comment]
so you need to copy two files jsstore.js and jsstore.worker.js into assets and access these scripts in your html page.

**Comment by kamalakkanni** [comment]
Thanks,you said to mention connection only in js file.how can i access that in my typescript file

**Comment by ujjwalguptaofficial** [comment]
you can declare the same variable what you have defined in js file. This way typescript wont throw compile errors.

so lets say you have defined `con` in js file as connection.

then in ts - 
`declare var con: JsStore.Instance`;  

here we are giving con variable a type of JsStore.Instance. If you will give type then you will be able to get intillisense features.

**Comment by kamalakkanni** [comment]
Hi,

I have created connection.js file.In that file,I have defined connection only like below

    var connection = new JsStore.Instance(new Worker('jsstore.worker.js'));

whether it is correct?

**Comment by kamalakkanni** [comment]
It gives _connection is not defined error

**Comment by ujjwalguptaofficial** [comment]
yes it is - but the `jsstore.worker.js` should be a path. so you should write the path relative to index.html.

**Comment by ujjwalguptaofficial** [comment]
lets continue this in gitter

**Comment by kamalakkanni** [comment]
Its working file.Thanks a lot

**Comment by ujjwalguptaofficial** [comment]
great 👍
