### ISSUE TITLE
Conditional Statements?

### ISSUE THREAD

**Issue by kakugiki** [ujjwalguptaofficial/JsStore#48]
Hi, thank you for sharing this wonderful tool. This is by far the best indexedDb wrapper I have found. 

Is it possible to add a new feature for conditional statements, something like connection.if ()?

**Comment by ujjwalguptaofficial** [comment]
Hi

Why do you want to use conditional statement. Could you describe your
situation please ?

**Comment by kakugiki** [comment]
Thanks for your prompt reply. I would like to insert response from web api but try to avoid duplicate records. Something like this:
 if (caseid not in (select caseid from table)) connection.insert()

**Comment by ujjwalguptaofficial** [comment]
yes you can do it easily - you just need to write few js code.

so for your case - it will be : 

```
connection.select({
    from: 'table_name',
    where: {
        caseid: {
            '!=': caseid // caseid from api
        }
    }
}).then(function(results) {
    if (results.length > 0) {
        connection.insert({
            into: 'table_name',
            values: [value]
        })
    }

}).catch(function(err) {

})
```

Hope above query makes sense. Let me know.

Thanks

**Comment by ujjwalguptaofficial** [comment]
Actually we can make the above query much good , same as you want - 

```
function getCountCaseIdInIndexedDb(caseId) {
    return connection.count({
        from: 'table_name',
        where: {
            caseid: caseid
        }
    })
}

var caseid = 5; // value from api

getCountCaseIdInIndexedDb(caseid).then(function(result) {

    // does not found any
    if (result == 0) {
        connection.insert({
            into: 'table_name',
            values: [value]
        })
    }

}).catch(function(err) {
    console.log(err);
})

```

**Comment by kakugiki** [comment]
Thank you very much for your efforts and prompt reply. I have only tried connection.count() and it works great. Still, a connect.if() will be more intuitive I guess.

**Comment by ujjwalguptaofficial** [comment]
That's a nice suggestion actually, but I don't see any possibility to add this into jsstore. 

Let's understand why - jsstore is nothing but lots of functions, code written in javascript which interacts with indexeddb. Now when we talk about condition statement, loops, etc. they are part of a language which is javascript in our case. 

When you say adding - "if(some query)" : that's part of a language but jsstore is not a language . Even if we can add something like that - that will make the codes heavy and thus the jsstore output file.

Lets compare it with sql - In sql we can execute query and same can be done in  jsstore. But Sql provides function and procedure where we can write condition statements, loops, can execute multiple statement etc. right?

Now as i have already told - jsstore is actually javascript, so the functions and sp in sql will be functions in javascript. So a function can use multiple jsstore query, can use if/else/for etc for different situation.

Hope you are able to understand this. 

I would encourage you to feel free to add any suggestion. This is a great suggestion actually, it helped me think what can be the possiblity and how we can make jsstore more better.

**Comment by ujjwalguptaofficial** [comment]
How about adding an api isExist - so it takes the query and return Boolean result. Something like this - 

```
con.isExist({
    from: 'table_name',
    where: {
        caseid: caseid
    }
}).then(function(isExist) {
 // isExist will be boolean
})
```
Let me know

**Comment by kakugiki** [comment]
I understood and expected that adding "if" is not possible. I was thinking what I really want is to use connection.set(key, value) so that I don't have to check whether the record exists or not. But connection.set sends the result to KeyStore instead of JsStore-Demo. If you can make the connection.set direct to JsStore-Demo, that will be great. I haven't tested your other codes yet. Will update if have any issue or feedback. Thank you very much for your time!

**Comment by ujjwalguptaofficial** [comment]
No its not possible. Set is simple api which stores data in the form of key and value and manages the database, table, primary key etc. for users.

Now if i will make set like the way you want - user will have to provide table name etc. 

But you can make it something like this for your app. So a set function which uses count api to check whether item exist or not then insert or update.
