### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by kakugiki** [ujjwalguptaofficial/JsStore#49]
JsStore works great on Chrome, but when I tried firefox, I got the following errors:

![image](https://user-images.githubusercontent.com/21064307/41101718-ecd5b27c-6a32-11e8-9ee1-8073bea493a5.png)

QueryExecutor.onQueryFinished
https://localhost:44329/idb/jsstore.worker.js:810:17
QueryExecutor.executeCode/<
https://localhost:44329/idb/jsstore.worker.js:798:17
Main.prototype.returnResult
https://localhost:44329/idb/jsstore.worker.js:917:13
onError
https://localhost:44329/idb/jsstore.worker.js:928:13
InitDb/dbRequest.onerror
https://localhost:44329/idb/jsstore.worker.js:1197:17

not sure this is just me or something else. Thanks.

**Comment by ujjwalguptaofficial** [comment]
As you can see In the console. The error is thrown by jsstore - Indexeddb_blocked. This happens in private mode of firefox. This is a kinda of bug in firefox and ie and a bug has been filed on their issue tracker but seems like they are not resolved yet.

Firefox issue link - https://bugzilla.mozilla.org/show_bug.cgi?id=781982

**Comment by kakugiki** [comment]
Just so you know, I just tried a regular firefox window, not the private mode, and got the same error.

**Comment by ujjwalguptaofficial** [comment]
ok that's something weird.

Please tell me the firefox version, jsstore version you are using.

**Comment by kakugiki** [comment]
Firefox is up to date: 60.0.2(64-bit)

@license :jsstore - V2.1.0 - 03/06/2018

**Comment by ujjwalguptaofficial** [comment]
Lets continue this in gitter - https://gitter.im/JsStore/Lobby. Please join the group and ping me.

**Comment by kakugiki** [comment]
OK, maybe it's just me. I'll close it the.

**Comment by kakugiki** [comment]
Actuall, I can't even load http://jsstore.net/example/like/ on firefox, regular mode.
same error: 
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
jsstore.worker.4bf42a1dec1b5527f6b6d2a995bbc6a6.js:810:17

**Comment by ujjwalguptaofficial** [comment]
Could you tell about the OS details ? 

I tried in windows7, windows10 - worked nice for me.

**Comment by kakugiki** [comment]
![image](https://user-images.githubusercontent.com/21064307/41171063-26e682a8-6b1d-11e8-9a16-103a1d5fc6c6.png)

**Comment by theS3ns** [comment]
Hello,

I once tested the link in my installed Firefox and the error did not occur. Reinstall your Firefox or create another profile in Firefox.

**Comment by kakugiki** [comment]
I reinstalled Firefox and it works now. Thanks.

Interestingly, even though Firefox doesn't show all the indexes, except the primary key, it certainly works as if all the indexes exist. I'll close this thread.

![image](https://user-images.githubusercontent.com/21064307/42509120-f4209a42-8418-11e8-9b7f-2e8ffa7c4f0f.png)

**Comment by ujjwalguptaofficial** [comment]
great 👏 , you guys found out. Seems like there may be some bugs in firefox particular version and then they fix it in another version (just a guess 🤓 ).

reagrding this >Note that Firefox doesn't show all the indexes, except the primary key

Browsers are dropping support for showing much information about indexedb data, so i would recommend to use idbstudio. I have built this to take the maximum benefit of jsstore and its very easy to use.

**Comment by kakugiki** [comment]
@ujjwalguptaofficial - I am not going to reopen the issue as I figure this is probably not a easy fix from your end. Just so you know that I am having the same issue again, even after reinstalled firefox. It will be nice if JsStore can work in firefox as well. After all, firefox is still a widely used browser. Thanks.
