### ISSUE TITLE
IAggregate type conversion issue in typescript

### ISSUE THREAD

**Issue by ujjwalguptaofficial** [ujjwalguptaofficial/JsStore#50]
```
private getDatabase() {
const tblKpi: ITable = {
  name: 'kpi',
  columns: [{
    name: 'id',
    primaryKey: true,
    autoIncrement: true
  },
  {
    name: 'productName',
    dataType: DATA_TYPE.String,
    notNull: true
  },
  {
    name: 'location',
    dataType: DATA_TYPE.String,
    notNull: true
  },
  {
    name: 'vendor',
    dataType: DATA_TYPE.String,
    notNull: true
  },
  {
    name: 'severity',
    dataType: DATA_TYPE.String,
    notNull: true
  },
  {
    name: 'total',
    dataType: DATA_TYPE.String,
    notNull: true
  }
  ]
}

const dataBase: IDataBase = {
  name: this.dbname,
  tables: [tblKpi]
};
return dataBase;
}
this.connection.select({
from: "kpi",
aggregate: {
sum: "total"
}
});
```

hello am trying to run the above aggregate query but am getting the below error. can anyone please help in this
Argument of type '{ from: string; aggregate: { sum: string; }; }' is not assignable to parameter of type 'ISelect'.
Types of property 'aggregate' are incompatible.
Type '{ sum: string; }' is not assignable to type 'IAggregate'.
Types of property 'sum' are incompatible.
Type 'string' is not assignable to type 'any[]'.

**Comment by ujjwalguptaofficial** [comment]
I confirm this is a small bug in typescript.

So for the time , you just need to provide array value to sum property.
e.g - 

```
this.connection.select({
    from: "kpi",
    aggregate: {
        sum: ["total"] // here is the change
    }
});
```

Hope this solves your problem and I will fix this asap.

Thanks

**Comment by ujjwalguptaofficial** [comment]
If you can fix it, feel free to send a pull request.

Thanks

**Comment by UmeshGowda** [comment]
@ujjwalguptaofficial hi am able to get some results but here am getting a list of results like bellow

0:{productName: "SMSE", location: "Bengaluru", vendor: "teleDNA", severity: "critical", total: 20, …}
1:{productName: "SMSE", location: "Bengaluru", vendor: "teleDNA", severity: "critical", total: 10, …}
2:{productName: "SMSE", location: "Bengaluru", vendor: "teleDNA", severity: "critical", total: 23, …}
3:{productName: "SMSE", location: "Bengaluru", vendor: "teleDNA", severity: "critical", total: 26, …}


what I wanted was the actual total sum of the column ["total"] i .e 79.
can you please let me know how can I achieve it.

**Comment by ujjwalguptaofficial** [comment]
The first value of the result will contains a property  with sum(total). Check out the below image
![image](https://user-images.githubusercontent.com/10938615/41149628-b3666e62-6b29-11e8-9893-15564a59bfd3.png)

**Comment by UmeshGowda** [comment]
hey, thank you so much I got it.

**Comment by ujjwalguptaofficial** [comment]
For better query execution, you can install  [IDBStudio](https://github.com/ujjwalguptaofficial/idbstudio) in your project and can run the different code like the way I am doing.

**Comment by UmeshGowda** [comment]
can I install IDBStudio it through npm.?

**Comment by ujjwalguptaofficial** [comment]
nope for now, I am working on this. Once it has become solid, I will add it to npm.

**Comment by ujjwalguptaofficial** [comment]
The issue is resolved in v - 2.1.2. Please check and let me know.

**Comment by ujjwalguptaofficial** [comment]
@UmeshGowda - you can install idbstudio using npm. Check out idbstudio page - https://github.com/ujjwalguptaofficial/idbstudio.

Btw - steps to use will be -
1. npm i idbstudio -g
2. idbstudio --start 

The above step will be start a development server.

**Comment by UmeshGowda** [comment]
@ujjwalguptaofficial  -  i really thank you so much, i will try it out installing idbstudio

**Comment by UmeshGowda** [comment]
@ujjwalguptaofficial  can you please tell me how to upgrade from 2.1.0 to 2.1.2.

**Comment by ujjwalguptaofficial** [comment]
yes sure. Check out our installation doc -
http://jsstore.net/tutorial/installation/.

Using npm it will be - npm i jsstore@latest --save

**Comment by ujjwalguptaofficial** [comment]
@UmeshGowda - Can we close this issue? If this is working for you . Let me know If the issue is not resolved yet.

**Comment by ujjwalguptaofficial** [comment]
closing the issue
