### ISSUE TITLE
raw sql?

### ISSUE THREAD

**Issue by wangzhe1995** [ujjwalguptaofficial/JsStore#52]
Can be used directly such as:
jsStore.exec('select * from table_name where name = "alice"');

?

**Comment by ujjwalguptaofficial** [comment]
Not for now but yes in the future. I am already working on a project which will execute raw sql.

**Comment by kakugiki** [comment]
That will be awesome!

**Comment by ujjwalguptaofficial** [comment]
@wangzhe1995 - First working & stable version of sqlweb is published. Check it out here - https://github.com/ujjwalguptaofficial/sqlweb. 

The docs are not completed for now, will let u know as soon as it is completed.

Hope you will like it.

**Comment by ujjwalguptaofficial** [comment]
Docs for sqlweb is here - http://jsstore.net/tutorial/sqlweb/.
