### ISSUE TITLE
Column with the data type object is not filled in the current Chrome browser.

### ISSUE THREAD

**Issue by theS3ns** [ujjwalguptaofficial/JsStore#53]
Table with the Data Type object is not created in the current Chrome Browser
`{
        name: 'column',
        notNull: false,
        dataType: DATA_TYPE.Object
}`

**Comment by ujjwalguptaofficial** [comment]
You mean whole table or single column ?

Please give me your db schema, so that I can generate the issue.

**Comment by theS3ns** [comment]
Hello,

thanks for your response. Exuse me for the wrong heading. I changed to:  "Column with the data type object is not filled in the current Chrome browser". Here ist this Schema:

`{"tables":[{"columns":[{"name":"uid","autoIncrement":true,"primaryKey":true,"unique":true,"notNull":false,"dataType":"number","multiEntry":false,"enableSearch":true},{"name":"username","autoIncrement":false,"primaryKey":false,"unique":false,"notNull":true,"dataType":"string","multiEntry":false,"enableSearch":true},{"name":"userdata","autoIncrement":false,"primaryKey":false,"unique":false,"notNull":false,"dataType":"object","multiEntry":false,"enableSearch":true}],"name":"User","version":1}],"name":"TestCache"}`

and here me code:

`  this._connection = new JsStore.Instance(new Worker(workerPath)); 
    const DatabaseName = 'TestCache';
    this._connection.isDbExist( DatabaseName ).then(isExist => {
      if (isExist) {
        this._connection.openDb(DatabaseName);
      } else {
        this._connection.createDb({
          name: DatabaseName,
          tables: [
            {
              name: 'User',
              columns: [{
                name: 'uid',
                primaryKey: true,
                autoIncrement: true,
                unique: true
              }, {
                name: 'username',
                notNull: true,
                dataType: DATA_TYPE.String
              }, {
                name: 'userdata',
                notNull: false,
                dataType: DATA_TYPE.Object
              }]
            },
          ]
        });
      }
    }).catch(err => {
      // this will be fired when indexedDB is not supported.
      console.error(err.Message);
    });

    public addQueryToDB( tableName: string, valObject: any ): Promise<Boolean> {
        return new Promise((resolve, reject) => {
            this._dbConnection.insert({
                into: tableName,
                values: [valObject],
            }).then((rowsInserted) => {
                if (rowsInserted > 0) {
                    console.log('successfully added');
                    resolve(true);
                }
            }).catch((err) => {
                console.log(tableName + ' => ' + JSON.stringify(valObject) , err );
                reject(false);
            });
        });
    }

   this.addQueryToDB( 'User',  { username: 'TestName', userdata: { test: 'testcity' } } );`

**Comment by ujjwalguptaofficial** [comment]
Ok. Have you tried to log the data using select api ? Browsers does not refresh or show actual datas always. Let me know if you are not getting the data. 

Anyway I will try to generate the issue.

**Comment by theS3ns** [comment]
I just heard. The current browser Chrome version 67.0.3396.99 (Official Build) (64-bit) does not display the object in the development tools. Thanks for your support. This ticket can closed.

**Comment by ujjwalguptaofficial** [comment]
That's why I have made - [IdbStudio](https://github.com/ujjwalguptaofficial/idbstudio). It provides many functionalities for running indexeddb query using jsstore.
