### ISSUE TITLE
Uncaught TypeError: value.toLowerCase is not a function

### ISSUE THREAD

**Issue by kakugiki** [ujjwalguptaofficial/JsStore#54]
This happens when converting a number to string:
connection.select({
  from: store,
  distinct: true,
  ignoreCase: true,
  where: { 
    Counsel: { like: String(counselId) || '' + '%' } 
  }
})

Error:
log_helper.ts:27 {message: "The transaction was aborted, so the request cannot be fulfilled.", type: "AbortError"}message: "The transaction was aborted, so the request cannot be fulfilled."type: "AbortError"__proto__: Object
LogHelper.logError @ log_helper.ts:27
Base.onErrorOccured @ base.ts:43
cursorOpenRequest.onerror @ where.ts:157
error (async)
Where.executeWhereLogic @ where.ts:155
(anonymous) @ base.ts:154
Base._this.goToWhereLogic @ base.ts:153
Instance.processWhere_ @ instance.ts:143
Instance.execute @ instance.ts:28
QueryExecutor.select_ @ query_executor.ts:236
QueryExecutor.executeLogic_ @ query_executor.ts:101
QueryExecutor.checkConnectionAndExecuteLogic @ query_executor.ts:50
self.onmessage @ start.ts:13
where_checker.ts:86 Uncaught TypeError: value.toLowerCase is not a function
    at WhereChecker.checkLike (where_checker.ts:86)
    at WhereChecker.check (where_checker.ts:29)
    at IDBRequest.cursorOpenRequest.onsuccess (where.ts:125)

![untitled](https://user-images.githubusercontent.com/21064307/42220596-6b007208-7e9d-11e8-8f35-f5af0d9aec3e.png)

**Comment by ujjwalguptaofficial** [comment]
it is because like expects a string value but it seems like you are supplying something else, not sure though. Please check the value you are supplying I mean log this value - `String(counselId) || '' + '%' `  in console and see what is the result.

**Comment by kakugiki** [comment]
I figured it expects a string, so I converted it to a string: String(counselId). The value is something like this: 40040690. So I guess it's still treated as a number?!

**Comment by ujjwalguptaofficial** [comment]
![image](https://user-images.githubusercontent.com/10938615/42224579-1260dbaa-7ef8-11e8-84cc-fba39a561a23.png)


see in the screenshot when value is number it has no quotes but when I am converting it to string it has quotes. I think it might be that - there is problem in converting the string. Let me know.

**Comment by kakugiki** [comment]
You are right, I have problem to convert it to a string, either String(number) or number.toString() return number without quotes.

**Comment by kakugiki** [comment]
Well, even though it's a string, the same error exists.

![untitled](https://user-images.githubusercontent.com/21064307/42226199-5817df14-7eac-11e8-8ef9-4df0d8cc7168.png)

**Comment by ujjwalguptaofficial** [comment]
you are executing like right ? Do one thing store the where object in a variable and then passed the where in where option. And also log the where query , if that helps good otherwise let me know the where query.

**Comment by kakugiki** [comment]
![image](https://user-images.githubusercontent.com/21064307/42227006-76086bcc-7eae-11e8-8f47-00de7574e319.png)

It's the same. And it works without CounselId, when all parameters are strings.

**Comment by kakugiki** [comment]
If you can fix this, it will great. Otherwise, using a variable for "where" is a workaround. I can use if/else to pass Counsel. When CounselId != null then Counsel: obj.counselId, otherwise, skip Counsel. So I don't have to use "like". This is also related to something like the following as we discussed before:

SELECT *
FROM [table]
WHERE [Provider] = ISNULL(NULLIF(@provider, ''), [Provider]). 

Although it's a bit annoy if there are many conditions to check.

**Comment by ujjwalguptaofficial** [comment]
Not sure but it might be that you are not supplying '%' in Counsel. Can you do that please and let me know ?

**Comment by kakugiki** [comment]
No, that's not it. I tried that before. Just did again, same thing.

**Comment by kakugiki** [comment]
var query = {};
          if (obj.counselId != null) {
            query = {
              Status: {
                like: obj.category == 'All' ? '' : obj.category + '%'
              },
              LastName: {
                like: obj.lastName || '' + '%'
              },
              FirstName: {
                like: obj.firstName || '' + '%'
              },
              Counsel: obj.counselId
            };
          }
          else {
            query = {
              Status: {
                like: obj.category == 'All' ? '' : obj.category + '%'
              },
              LastName: {
                like: obj.lastName || '' + '%'
              },
              FirstName: {
                like: obj.firstName || '' + '%'
              }
            };
          }

**Comment by kakugiki** [comment]
I ended up using above query to get it done.

**Comment by ujjwalguptaofficial** [comment]
So counselId is a number right ? and you are trying to execute like on a number field right ?

**Comment by kakugiki** [comment]
Yup, so I convert it to a string, as you can see, it's { like: "40040690" }

**Comment by kakugiki** [comment]
Actually, this is how I define the column:
    name: 'Counsel',
    notNull: true,
    dataType: JsStore.DATA_TYPE.String

**Comment by ujjwalguptaofficial** [comment]
I think value stored in db is not string and that's the reason it is throwing error. But you have type string for the field 'Counsel' which means either you are using skipdatacheck - false or bulkinsert to store those data. 

Let me know

**Comment by kakugiki** [comment]
You are probably right. I didn't use your way to insert data, as it only insert new data. I use "set" to upsert(update/insert) the table.

**Comment by ujjwalguptaofficial** [comment]
jsstore assumes that you are supplying the right type data as you have defined in the table structure and based on the type it does the operation. 

if issue is resolved. Please close the issue.
Thanks

**Comment by kakugiki** [comment]
So it makes more sense to define the column as number instead of string then: JsStore.DATA_TYPE.Number
by the way, I can't find details of JsStore.DATA_TYPE. There are just String and Number, right?

**Comment by ujjwalguptaofficial** [comment]
there are many types. See here - http://jsstore.net/tutorial/enums/.  But you are right - its not linked any where, I will add that.

Thanks.
