### ISSUE TITLE
enable_search_off produced when search is actually enabled

### ISSUE THREAD

**Issue by Mc128k** [ujjwalguptaofficial/JsStore#57]
Hi,
I am seeing this error after updating the library

<img width="2460" alt="screen shot 2018-07-08 at 12 41 44" src="https://user-images.githubusercontent.com/3678359/42419003-920eb694-82ac-11e8-8992-99d5d557a1d2.png">

It appears that the error is not correct, as the schema has search enabled. I'm still trying to figure it out, but I thought that it would be useful to report this, as the error seems inaccurate.

== EDIT 1
I might add that the error is mostly because I am not doing something properly, and I think it's because I change the schema when I reload data, still debugging. Also the indexeddb schema is wrong here, it must be because I'm loading with the `bulkInsert` operation
<img width="1590" alt="screen shot 2018-07-08 at 12 53 36" src="https://user-images.githubusercontent.com/3678359/42419073-1639f5a4-82ae-11e8-99a2-01e6b6293df2.png">

**Comment by ujjwalguptaofficial** [comment]
> I am seeing this error after updating the library


Can you tell me - what was your prev version ? Also please getDbSchema for getting db schema , it may be that you are viewing some other db. IndexedDb is case sensitive, so there might be problem with db name.

Let me know.

**Comment by ujjwalguptaofficial** [comment]
Do one thing - instead of seeing through chrome developer tool - use idbstudio. Install it and load it at the same port as your localhost is running. You will get a clear picture of everything.

**Comment by Mc128k** [comment]
Cool thing that I can use idbstudio for my own database, thanks for the tip. Anyway I rewrote entirely the code that changes the schema according to the documentation [here](http://jsstore.net/tutorial/change-table-design/) and now it works fine. Still I think the error is misleading.
