### ISSUE TITLE
Wrong query result

### ISSUE THREAD

**Issue by Mc128k** [ujjwalguptaofficial/JsStore#59]
Hi
I'm trying to troubleshoot this query:
```
    from: 'Job',
            where: {
              _getDateCreation: {'>=': unixTimestampFromDate(startDate)},
              or: {
                _getDateLastExitLab1: {'>': 0},
                _getDateLastExitLab2: {'>': 0},
              },
            },
```
The fields can be either a number or null, I expect from this to find a record which has at least one of the two DateLastExitLab defined, but it returns even those who don't have any value.
![screen shot 2018-07-16 at 18 12 17](https://user-images.githubusercontent.com/3678359/42769879-d0033bc8-8923-11e8-93c0-28b3e279c733.png)

What is should do is:
( (date creation > timestamp ) AND ( last exit date 1 > 0 OR last exit date 2 > 0 ) )

**Comment by ujjwalguptaofficial** [comment]
The equivalent of your query in sql is -  select * from job where getDateCreation>=startDate or getDateLastExitLab1>0 or getDateLastExitLab2>0

But you want - select * from job where getDateCreation>=startDate AND(getDateLastExitLab1>0 OR getDateLastExitLab2>0)
. For this the jsstore query will be -

```
select({
    from: 'Job',
    where: [{
            _getDateCreation: {
                '>=': unixTimestampFromDate(startDate)
            }
        },
        {
            _getDateLastExitLab1: {
                '>': 0
            },
            or: {
                _getDateLastExitLab2: {
                    '>': 0
                }
            }
        }
    ]
})
```

Take a look at  docs - http://jsstore.net/tutorial/adv-sql-example/ .

**Comment by ujjwalguptaofficial** [comment]
The concept is simple when you have query joined by 'and' , 'or' - In this case : where query should be an array of multiple queries. JsStore then joined those query internally.

Hope you are able to understand that.

**Comment by Mc128k** [comment]
The syntax threw me off track. Thanks for clarifying, it's correct now. For readability I put it like this:
```
from: 'Job',
            where: [
              { _getDateCreation: {'>=': unixTimestampFromDate(startDate)} },
              {
                _getDateLastExitLab1: {'>': 0},
                or: { _getDateLastExitLab2: {'>': 0} }
              },
            ]
```

i looked indeed in the manual, only that I was searching in the "or" section, maybe it could be extended with how 'and' works too.

Thanks for the help
