### ISSUE TITLE
not Working with chrome

### ISSUE THREAD

**Issue by aly-eldegwy** [ujjwalguptaofficial/JsStore#62]
i have been trying to test JSStore but i i'm not able to make it work i was following the get started and used the examples it is working in firefox but nothing working in chrome no response from promise nothing in then nor in catch 

i'm using chrome Version 67.0.3396.99 (Official Build) (64-bit) on ubuntu 18.04

**Comment by ujjwalguptaofficial** [comment]
Open this link - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20%20%20from%3A'Customers'%2C%0A%20%20%20%20%20%20limit%3A100%0A%7D) . if you are getting below screenshot - then its working in your browser and there is some coding problem.

![image](https://user-images.githubusercontent.com/10938615/43113687-fb90aee2-8f18-11e8-9709-985cbdee45bb.png)


Let me know.

**Comment by ujjwalguptaofficial** [comment]
Check this fiddle - https://jsfiddle.net/2ewpy6t4/6/

**Comment by ujjwalguptaofficial** [comment]
@aly-eldegwy - let's close the issue, if everything is ok otherwise let me know.
