### ISSUE TITLE
Taking time to fetch or insert records when there is lot of records.

### ISSUE THREAD

**Issue by paragpadsumbiya** [ujjwalguptaofficial/JsStore#64]
@ujjwalguptaofficial 
Thanks for this awesome plugin but I have below issue when there are lot of records.

I have around 50000 and 1 lakh records and I am using like query to search records on it takes and it taking 8 seconds in PC but on android browser on tablet it taking so much time like 20 seconds to fetch records.
Same happen with when I am trying to insert 1 Lakh records on PC it takes hardly 1.5 Minute but on Android tablet browser it taking around 8 minutes .

So is there any way to work around on this ?
And jsstore and indexdb are connected to configuration of Device

**Comment by paragpadsumbiya** [comment]
@ujjwalguptaofficial  Thanks for your valuable response . Currently I am using bulk insertion . Can you please show me how to use skipDataCheck  and batch insertion with example ? . Can we use skipDataCheck  ,batch insertion,bulk insertion at same time . If yes then please give me example as I am not able to find in your documents. We are trying for sqllite on android side . can you please share your thoughts on same ?

**Comment by ujjwalguptaofficial** [comment]
bulkInsert Api doc is here - http://jsstore.net/tutorial/bulk-insert/ . 

insert Api doc - http://jsstore.net/tutorial/insert/

example for using skipDataCheck in insert api - 

```
insert({
    into: 'table',
    values: [values],
    skipDataCheck: true
})
```

**Comment by ujjwalguptaofficial** [comment]
Batch insertion means - insert few records at a time rather than all records. e.g - let's say you have 10000 record, so we will insert 1000 record at a time i.e - 10000/1000 = 10 batches.

```
var values // contains all records
var counter = 0;
var noOfBatch = values.length / 1000;


var insertRecord = function() {
    // get value between counter and next 1000
    var newValue = values.slice(counter, counter + 1000);
    insert({
        into: 'table',
        values: newValue,
        skipDataCheck: true
    }).then(onRecordInserted)
}

var onRecordInserted = (rowsInserted) => {
    --noOfBatch;
    if (noOfBatch > 0) {
        counter += 1000;
        insertRecord();
    }
}

insertRecord();
```

This is just an example of how you can do batch operation, you can have different way to do it.

**Comment by paragpadsumbiya** [comment]
@ujjwalguptaofficial  Thanks a lot for your valuable time and plugin . I will try same on Monday when I am get back to office . If I need your help I will post more.

**Comment by ujjwalguptaofficial** [comment]
@paragpadsumbiya - Let me know if you have other questions, otherwise please close the issue.
