### ISSUE TITLE
InvalidAccessError in IE and Edge

### ISSUE THREAD

**Issue by fkalka** [ujjwalguptaofficial/JsStore#68]
Hi,
whenever i use a where clause, i get an invalid access error in function "executeWhereLogic" on this line:

`this.cursorOpenRequest = this.objectStore.index(column).openCursor(this.getKeyRange(value, op), dir);`

It is the 'openCursor' part that is causing the error.

Please go to "https://ujjwalguptaofficial.github.io/idbstudio/" and use a query like:
`select({
    from: 'Categories',
    where: {
        categoryId: 1
    }
})`
to reproduce the issue.

Without a where clause, it works.

(I saw the other issue with the same name, but after reading it, it seemed to be something else, sorry if it is the same issue)

**Comment by ujjwalguptaofficial** [comment]
@fkalka - seems like this is the same issue but they were not able to explain where the query was not working. I am glad you found it. I am able to reproduced the issue and will fix it very soon.

Fyi - I have asked SauceLabs for cross browser testing, hope they gave me the access.

**Comment by ujjwalguptaofficial** [comment]
@fkalka  - the issue is resolved in version 2.3.4 . Here is the idbstudio link - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20'Categories'%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20categoryId%3A%201%0A%20%20%20%20%7D%0A%7D)

**Comment by fkalka** [comment]
My application is working now, thank you very much!

**Comment by ujjwalguptaofficial** [comment]
@fkalka - there were some others issue, I have fixed all of them and now its working fine. Please update to version - 2.4.0. 
Fyi - I have also included Cross browser testing report. You can check that at jsstore GitHub home page.
