### ISSUE TITLE
issue with limit when combined with order by

### ISSUE THREAD

**Issue by kakugiki** [ujjwalguptaofficial/JsStore#69]
```
conn.select({
        from: 'PhotoInfo',
       limit: 1,
        where: {
          DocumentID: {
            '<': documentId
          }
        },
        order: {
          by: 'DocumentID',
          type: 'desc'
        }
      }).then(val => console.log(val));
```

this returns the same result no matter whether the sort_type is asc or desc.

**Comment by ujjwalguptaofficial** [comment]
For me it's working good. It might be some situation where its failing. Let me know.

Check out these two link - 

1. with sort type ('asc') - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20'Products'%2C%0A%20%20%20%20limit%3A%20100%2C%0A%20%20%20%20order%3A%20%7B%0A%20%20%20%20%20%20%20%20by%3A%20'price'%2C%0A%20%20%20%20%20%20%20%20type%3A'asc'%0A%20%20%20%20%7D%0A%7D)

2. with type (desc) - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20'Products'%2C%0A%20%20%20%20limit%3A%20100%2C%0A%20%20%20%20order%3A%20%7B%0A%20%20%20%20%20%20%20%20by%3A%20'price'%2C%0A%20%20%20%20%20%20%20%20type%3A'desc'%0A%20%20%20%20%7D%0A%7D)

**Comment by kakugiki** [comment]
Your sample doesn't have the where condition, that's the difference.

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%27Products%27%2C%0A%20%20%20%20limit%3A%20100%2C%0A%20%20%20%20order%3A%20%7B%0A%20%20%20%20%20%20%20%20by%3A%20%27price%27%2C%0A%20%20%20%20%20%20%20%20type%3A%27asc%27%0A%20%20%20%20%7D%0A%7D)

I tried your code with where condition and issue is there. You can try to change the sort_type and make the limit as 1

**Comment by kakugiki** [comment]
Okay, while limit may have it's limit, aggregate suits my need. So instead of using limit, the following code gets 2603135:

```
      conn.select({
        from: 'PhotoInfo',
        aggregate: {
          max: 'DocumentID'
        },
        where: {
          DocumentID: {
            '<': documentId
          }
        },
        order: {
          by: 'DocumentID',
          type: 'desc'
        }
      }).then(val => console.log(val[0].DocumentID));
```

**Comment by ujjwalguptaofficial** [comment]
> I tried your code with where condition and issue is there. You can try to change the sort_type and make the limit as 1

Can you generate the idbstudio link and paste here . 

Steps to generate link is - 
1.  Write the query
2. Click on get link button - this will open a modal
3. Click on copy button on modal - this will copy the link from the modal

The link can be shared to any one. That will open the exact query. 

Thanks

**Comment by kakugiki** [comment]
I have the link above, I marked with a 'laugh' emoji.

**Comment by kakugiki** [comment]
I modified the link above, marked with a laugh emoji, according to your suggestion. You can change the sort_type from there. Thanks.

**Comment by ujjwalguptaofficial** [comment]
ok got it. I will fix it asap.

**Comment by kakugiki** [comment]
Thanks, you might  want to check aggregate with sort_type as well.

**Comment by ujjwalguptaofficial** [comment]
yeah aggregate works, when you just want first sorted result. But for those who wants all datas in sorted it wont .

**Comment by kakugiki** [comment]
This is what I meant about the aggregate issue:
https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20'Products'%2C%0A%20%20%20%20aggregate%3A%20%7B%0A%20%20%20%20%20%20%20%20max%3A%20'supplierId'%0A%20%20%20%20%7D%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20supplierId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20'%3E'%3A%2018%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20order%3A%20%7B%0A%20%20%20%20%20%20%20%20by%3A%20'price'%2C%0A%20%20%20%20%20%20%20%20type%3A%20'asc'%0A%20%20%20%20%7D%0A%7D)
I guess we should get only one record using aggregate?! but the results is 24 records.

**Comment by ujjwalguptaofficial** [comment]
yeah aggregate results are somehow different. Could you add another issue for aggregate, so that we can talk in depth. 

Thanks

**Comment by ujjwalguptaofficial** [comment]
@kakugiki - issue is fixed in V 2.4.1. Please take a look and let me know.

Thanks

**Comment by kakugiki** [comment]
@ujjwalguptaofficial Thank you for spending time to fix this. Did you update your idbstudio yet? Tried the link above but didn't see any difference?!

**Comment by ujjwalguptaofficial** [comment]
No idbstudio is not udated. I am working on the update.
