### ISSUE TITLE
aggregate max return more than one record?

### ISSUE THREAD

**Issue by kakugiki** [ujjwalguptaofficial/JsStore#70]
A similar issue as "limit with order by" also happens when using the aggregate:
https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20'Products'%2C%0A%20%20%20%20aggregate%3A%20%7B%0A%20%20%20%20%20%20%20%20max%3A%20'supplierId'%0A%20%20%20%20%7D%2C%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20supplierId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20'%3E'%3A%2018%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20order%3A%20%7B%0A%20%20%20%20%20%20%20%20by%3A%20'price'%2C%0A%20%20%20%20%20%20%20%20type%3A%20'asc'%0A%20%20%20%20%7D%0A%7D)
I guess we should get only one record using aggregate?! but the results is 24 records.

**Comment by ujjwalguptaofficial** [comment]
solved in  v 3.0.0
