### ISSUE TITLE
Read boolean column

### ISSUE THREAD

**Issue by gujral87** [ujjwalguptaofficial/JsStore#72]
Hi Ujjwal, 

I'm facing another issue with column datatype boolean. If I try to read table with where **{colName : true}** I get query error " DOMException: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key.".  but the same query working fine for other datatypes. (e.g : {colname : "Test"}.

Any solution for this?

Thanks

**Comment by ujjwalguptaofficial** [comment]
Hi there

Check out this link -
https://stackoverflow.com/questions/48149851/failed-to-execute-only-on-idbkeyrange-the-parameter-is-not-a-valid-key

**Comment by gujral87** [comment]
Ah ok. But not sure why we have Boolean as datatype then. I can use string values instead.

Thanks,

**Comment by ujjwalguptaofficial** [comment]
That's a great question @gujral87 - By specifying jsstore just checks for data when you do insert but indexeddb does not provide indexing for boolean datatype, so thats the problem. 

I will update docs specifying what data type is supported for reading.
