### ISSUE TITLE
Error in simple example/ add.html

### ISSUE THREAD

**Issue by Kickassbadboy** [ujjwalguptaofficial/JsStore#74]
I was using add.html for reference 
i am facing same problem for my project

![screen shot 2018-09-12 at 12 46 25 pm](https://user-images.githubusercontent.com/7989070/45408680-b698a800-b68a-11e8-8c53-8d58295b9b1a.png)

**Comment by ujjwalguptaofficial** [comment]
Hi

worker is not supported in file protocol. Please run the folder under a
http server.

You can take a look at without worker example.

**Comment by Kickassbadboy** [comment]
Thank you i am able to do it without worker . 
Can i know why it doesn't work with worker. ?

**Comment by ujjwalguptaofficial** [comment]
some browsers like chrome does not allow worker to run with file protocol
as its not the web protocol. The http is the real protocol.

I think firefox support worker in file protocol too.

**Comment by Kickassbadboy** [comment]
i tried in safari for worker and without worker , it does not run any reason behind it or safari's error ?

**Comment by Kickassbadboy** [comment]
![screen shot 2018-09-12 at 1 36 19 pm](https://user-images.githubusercontent.com/7989070/45411117-0e3a1200-b691-11e8-9b86-7dd2bdbbc23c.png)

why is it stating "slow network detected"

**Comment by ujjwalguptaofficial** [comment]
console warning "slow network detected" is thrown by chrome for some reason. May be they are working on something. Its not part of jsstore.

If you are developing something, please create a http server and run the project inside that server. You can use the package - https://www.npmjs.com/package/http-server. This is what i use for my development purpose.
