### ISSUE TITLE
Object doesn't support property or method 'findIndex' in ie while using jsstore

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#75]
Hi,

Object doesn't support property or method 'findIndex' in ie while using jsstore. [https://github.com/ujjwalguptaofficial/JsStore/issues/45]
This issue is not yet fixed.pls help me to fix it.

Thanks and Regards
Kamalakkanni.V

**Comment by ujjwalguptaofficial** [comment]
Could you add below code globally ?

```
if (!Array.prototype.findIndex) {
    Object.defineProperty(Array.prototype, 'findIndex', {
      value: function(predicate) {
       // 1. Let O be ? ToObject(this value).
        if (this == null) {
          throw new TypeError('"this" is null or not defined');
        }
  
        var o = Object(this);
  
        // 2. Let len be ? ToLength(? Get(O, "length")).
        var len = o.length >>> 0;
  
        // 3. If IsCallable(predicate) is false, throw a TypeError exception.
        if (typeof predicate !== 'function') {
          throw new TypeError('predicate must be a function');
        }
  
        // 4. If thisArg was supplied, let T be thisArg; else let T be undefined.
        var thisArg = arguments[1];
  
        // 5. Let k be 0.
        var k = 0;
  
        // 6. Repeat, while k < len
        while (k < len) {
          // a. Let Pk be ! ToString(k).
          // b. Let kValue be ? Get(O, Pk).
          // c. Let testResult be ToBoolean(? Call(predicate, T, « kValue, k, O »)).
          // d. If testResult is true, return k.
          var kValue = o[k];
          if (predicate.call(thisArg, kValue, k, o)) {
            return k;
          }
          // e. Increase k by 1.
          k++;
        }
  
        // 7. Return -1.
        return -1;
      },
      configurable: true,
      writable: true
    });
  }
```


if you are getting confused about how to add it - just add it in index.html file under script section. Let me know what's the result.

**Comment by kamalakkanni** [comment]
Thanks,But I got same error

**Comment by ujjwalguptaofficial** [comment]
could you run this in console of ie where you are getting this error.

```
var array1 = [5, 12, 8, 130, 44];

function findFirstLargeNumber(element) {
  return element > 13;
}

console.log(array1.findIndex(findFirstLargeNumber));
```

**Comment by kamalakkanni** [comment]
I am getting  below output
undefined
3

**Comment by ujjwalguptaofficial** [comment]
it means that findIndex  is working. In this case - you are including the findIndex script after the jsstore. Please make sure that you are including the findIndex script before jsstore initialize.

**Comment by ujjwalguptaofficial** [comment]
Ok, I would create a demo which will support the ie. This will help you to see what's going wrong. I will upload the demo by tomorrow.

Thanks

**Comment by kamalakkanni** [comment]
not yet solved

**Comment by kamalakkanni** [comment]
Hi,any update on this

**Comment by ujjwalguptaofficial** [comment]
Hi

Yes I am working on this. I am creating separate build for ie support. This
may take some time, not sure  how much.

**Comment by ujjwalguptaofficial** [comment]
yep i m working on it.

**Comment by ujjwalguptaofficial** [comment]
Hi @kamalakkanni - I have created the build for ie. There is separate file for ie support which contains inbuilt polyfill. Here is the example - https://github.com/ujjwalguptaofficial/JsStore/tree/master/examples/webpack%20with%20ie%20support

So basically you need to use - jsstore.worker.ie.js instead of jsstore.worker.js . You can use minified version or dev version, its upto you.

Hope this will help you.

**Comment by ujjwalguptaofficial** [comment]
@kamalakkanni  - issue is resolved. Please install latest verson - 2.4.3. For supporting in ie - you need to use the file : jsstore.worker.ie.min.js . its a special build for working in ie through webworker.

Here is the example for more help - https://github.com/ujjwalguptaofficial/JsStore/tree/master/examples/webpack%20with%20ie%20support

Please let me know if everything is working for you.

**Comment by kamalakkanni** [comment]
Thank you so much.its working fine now
