### ISSUE TITLE
Outdated data

### ISSUE THREAD

**Issue by xhuberdeau** [ujjwalguptaofficial/JsStore#76]
Hello,

First thanks for your work!

I'm having an issue when I first update data and then fetch it later: sometimes it returns outdated data.
It is totally random, so sometimes I have what I want, but sometimes some information are missing.
This is how I use jsstore:
Update:
`return from(this.connection.update({
            in: 'MyTable',
            where: {
                id: myId,
            },
            set: updateValue,
        }));
`

Select:
`return from(this.connection.select<IMyTable>({
            from: 'MyTable',
            where: {
                id: myId,
            },
        }));`

If I look at the developer tools, the data are correctly updated. But once is it fetched later in my web app, the data returned don't reflect what I have in the developers tools. So further update delete some part of my data while new data are correctly updated, until the same happens later again..

Do you have any idea what's wrong?

Thanks.

**Comment by ujjwalguptaofficial** [comment]
Hi

There might be that db is being updated/deleted from somewhere before you call the select api. You can check whats being called by turning on log. Check out this doc - http://jsstore.net/tutorial/helpers/.

setLogStatus is the api through which you can turn on/off logs. 

Let me know what you found. Thanks.

**Comment by ujjwalguptaofficial** [comment]
Also make sure that - you are not initiating multiple instance of jsstore. It is recommended to use one db per instance.

If you have a case where you want to do multiple operation, then use transaction api. Check out the doc - http://jsstore.net/tutorial/transaction/.

Let me know if you need any help.

**Comment by xhuberdeau** [comment]
Hello,

In fact the problem was on my side. There were some concurrent update / select launched at almost the same time resulting in hazardous endings.

Sorry for this "issue" which is not and thanks for your help :).
