### ISSUE TITLE
`or` does not work on strings

### ISSUE THREAD

**Issue by SquawkWoof** [ujjwalguptaofficial/JsStore#77]
Given this database:

    [
        {
            name: 'Items',
            columns: [
                {
                    name: 'ItemID',
                    dataType: JsStore.DATA_TYPE.String,
                }
            ]
        }
    ]

Containing this data:

    "Shrimp", "Apples"

Run this query:

    JsStoreConnection.select({
        from: 'Items',
        where: {
            Item: 'Shrimp',
            or: {
                Item: 'Apples'
            }
        }
    }).then((results) => console.log(results.length, results) );

The result I get is:

`1` for length and `0: {Item: "Apples"}` for result data.

Shouldn't it be returning both rows in the results?

**Comment by ujjwalguptaofficial** [comment]
yes it should, but are you sure that shrimp and apples both exist in the items tables in column item. Please check your data and let me know.

Also you should use in when you want multiple values to check for single column. Your query is not wrong though, I am just suggesting for better approach.


Thanks

**Comment by SquawkWoof** [comment]
>yes it should, but are you sure that shrimp and apples both exist in the items tables in column item. 

Indeed, they do.  It works using `in`, but what if I need to use `or` on different columns?

**Comment by ujjwalguptaofficial** [comment]
fyi - you can install idbstudio in your app too. And then run the query for ur db.
