### ISSUE TITLE
 JsStore is not runing in web worker

### ISSUE THREAD

**Issue by shank410** [ujjwalguptaofficial/JsStore#8]
Hi Ujjwal,

Amazing job with JsStore.

I get this warning whenever i run my html page using JsStore.

Can you please let me know if this would be an area of concern when i run my applications

**Comment by ujjwalguptaofficial** [comment]
Thank you very much @shank410 . The warning is shown , when jsstore can not run the code in web worker.So when it can not run inside a web worker , it runs the code in main thread. Chrome does not allow to run the code inside a web worker for file system, so you may be seeing this issue. The same should work in firefox.

please let me know - if you have any other questions.

**Comment by ujjwalguptaofficial** [comment]
I suppose you are running the html page as a file, that's why this warning is showing. The issue will be gone, when you run the html pages inside a server.

**Comment by shank410** [comment]
yes i am running the html page as a file which is what my requirement is.
but as long as this warning is not a roadblock i am fine.

i am trying to run a select query.and from the results which i get,i am trying to execute a loop and again run a select query inside the loop using the information fetched from the 1st select statement,is this possible in jsstore?

**Comment by ujjwalguptaofficial** [comment]
you can use in option to get the data at a time for multiple values. But there is nothing which will takes loop and do something.

Any ways - it will be better if you can create a jsfiddle, or write an article explaining what you are doing. If there is any thing that can be improved, i will surely help.

Thanks.

**Comment by shank410** [comment]
why am i not able to create a db in firefox?

**Comment by ujjwalguptaofficial** [comment]
Are you using firefox in incognito?

**Comment by shank410** [comment]
no i am not, but i got that resolved anyway.

but while exporting a json file, i need to export data based on a certain values i.e i do not want to export the whole table data but a certain records based on the values that i might pass. is this possible?

**Comment by ujjwalguptaofficial** [comment]
ok good to know. You resolved it. 

You can use other options for filtering record like - where, in, or etc. 

Here is the example -

`var Connection = new JsStore.Instance('Demo');
Connection.exportJson({
    From: "Customers",
    Where:{
        Country:'Mexico'
    },
    OnSuccess:function (){
        log('Successfully exported');
    },
    OnError:function (error) {
        log(error);
    }
});`

**Comment by shank410** [comment]
hi Ujjwal,

Thank you for all your responses,they have been really helpful and so has been JsStore.

However there are few things which i need to address and i seem to get stuck with them at some point.

while running a query using the in operator, if i pass parameters manually the query executes properly, but while passing the parameters through javascript, JsStore returns an empty array.

Could you please help me with this small issue as well?

**Comment by ujjwalguptaofficial** [comment]
I think you are passing 'ids' instead of 'id' for In query. Make sure you are passing a array for in query.

Hope this will help you.

**Comment by ujjwalguptaofficial** [comment]
@shank410 - In case you have any problems, please ask questions at different forums like - stackoverflow etc. We are also on Gitter - https://gitter.im/JsStore. Feel free to reach us.

Thanks.
