### ISSUE TITLE
DOMException: "A request was placed against a transaction which is currently not active, or which is finished.

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [ujjwalguptaofficial/JsStore#83]
Getting error : 

> in ./node_modules/jsstore/dist/jsstore.worker.commonjs2.js/module.exports</OpenDb.prototype.execute/dbRequest_1.onsuccess
> jsstore.worker.commonjs2.js:1884

DOMException: "A request was placed against a transaction which is currently not active, or which is finished.

Using it in React

Complete Log : 

`DOMException: "A request was placed against a transaction which is currently not active, or which is finished." index.js:2178
__stack_frame_overlay_proxy_console__
index.js:2178
./node_modules/jsstore/dist/jsstore.worker.commonjs2.js/module.exports</Base.prototype.onExceptionOccured
jsstore.worker.commonjs2.js:3876
./node_modules/jsstore/dist/jsstore.worker.commonjs2.js/module.exports</Instance.prototype.execute
jsstore.worker.commonjs2.js:2310
./node_modules/jsstore/dist/jsstore.worker.commonjs2.js/module.exports</QueryExecutor.prototype.select_
jsstore.worker.commonjs2.js:406
./node_modules/jsstore/dist/jsstore.worker.commonjs2.js/module.exports</QueryExecutor.prototype.executeLogic_
jsstore.worker.commonjs2.js:233
./node_modules/jsstore/dist/jsstore.worker.commonjs2.js/module.exports</QueryExecutor.prototype.checkConnectionAndExecuteLogic
jsstore.worker.commonjs2.js:183
./node_modules/jsstore/dist/jsstore.commonjs2.js/module.exports</InstanceHelper.prototype.sendRequestToWorker_
jsstore.commonjs2.js:637
./node_modules/jsstore/dist/jsstore.commonjs2.js/module.exports</InstanceHelper.prototype.executeQry_
jsstore.commonjs2.js:605
./node_modules/jsstore/dist/jsstore.commonjs2.js/module.exports</InstanceHelper.prototype.processFinishedQuery_
jsstore.commonjs2.js:581
./node_modules/jsstore/dist/jsstore.worker.commonjs2.js/module.exports</QueryExecutor.prototype.returnResult_
jsstore.worker.commonjs2.js:215
onSuccess
jsstore.worker.commonjs2.js:221
./node_modules/jsstore/dist/jsstore.worker.commonjs2.js/module.exports</OpenDb.prototype.execute/dbRequest_1.onsuccess
jsstore.worker.commonjs2.js:1884
` 

Need an immediate help... Thanks a lot

**Comment by shoubhik001** [comment]
No I have opened the db and then running the query... And moreover the error diesnot comes all the time... It comes sometimes and after reloading the page it goes away again..


My structure is like that :  I am hitting an update query with a promise and if the promise faikes to update... I am hitting insert query on the callback 


Moreover I have opened the db several times and also initiated the jsstore instance and jsstore worker several times.

**Comment by ShoubhikBanerjee** [comment]
No I have opened the db and then running the query... And moreover the error diesnot comes all the time... It comes sometimes and after reloading the page it goes away again..


My structure is like that :  I am hitting an update query with a promise and if the promise faikes to update... I am hitting insert query on the callback 


Moreover I have opened the db several times and also initiated the jsstore instance and jsstore worker several times.

**Comment by ShoubhikBanerjee** [comment]
My Sample React Code For DB Operations : 

`import * as JsStore from "jsstore";
import * as JsStoreWorker from "jsstore/dist/jsstore.worker.commonjs2";
import DbStructure from "./DbStructure";
import ConsoleLogger from "../Utils/ConsoleLogger";
import InsertIntoDb from "./InsertIntoDb";
let config = require('../Config/appConfig.json');
const DB_NAME = config.INDEXED_DB_NAME;
const CUSTOM_DB_ERROR_CODE = config.CUSTOM_DB_ERROR_CODE;
const CUSTOM_DB_SUCESS_CODE = config.CUSTOM_DB_SUCESS_CODE;
const TABLE_NAME = config.INDEXED_DB_TABE_NAME_FOR_JOSN_STORAGE;
const TABLE_PRIMARY_COL_NAME = config.INDEXED_DB_COL_PRIMARY_FOR_JOSN_STORAGE;
const TABLE_COL_JSON_NAME = config.INDEXED_DB_COL_JSON_NAME_FOR_JOSN_STORAGE;
const TABLE_COL_JSON_DATA = config.INDEXED_DB_COL_JSON_DATA_FOR_JOSN_STORAGE;

const col_1 = "asdas";
window['JsStoreWorker'] = JsStoreWorker;

const context = "UpdateDataDb.js";
var connection = new JsStore.Instance();

var UpdateDataDb = (function () {

    async function updateItem(jsonName, jsonData, note) {
        return new Promise(function (resolve, reject) {
            ConsoleLogger.log(context, "Note => " + note + " JSON NAME => " + jsonName + "JOSN Data => " + JSON.stringify(jsonData));
            window['JsStoreWorker'] = JsStoreWorker;
            var connection = new JsStore.Instance();
            connection.isDbExist(DB_NAME).then(function (isExist) {
                if (isExist) {
                    ConsoleLogger.log(context, "Note => " + note + " DB EXISTS");
                    connection.openDb(DB_NAME);
                    updateDataIntoDb(jsonName, jsonData, note)
                        .then(function (responseJson) {
                            resolve(responseJson)
                        })
                        .catch(function (error) {
                            var exceptionResponse = {
                                "status": CUSTOM_DB_ERROR_CODE,
                                "message": error.message
                            }
                            reject(exceptionResponse)
                        })
                    // })



                } else {
                    var exceptionResponse = {
                        "status": CUSTOM_DB_ERROR_CODE,
                        "message": "DB Doesnot Exists"
                    }
                    reject(exceptionResponse)

                }
            }).catch(function (err) {
                var exceptionResponse = {
                    "status": CUSTOM_DB_ERROR_CODE,
                    "message": err.message
                }
                reject(exceptionResponse)
            });
        });
    }

    async function updateDataIntoDb(jsonName, jsonData, note) {

        return new Promise((resolve, reject) => {

            ConsoleLogger.log(context, "Note => " + note + " IN update FUNCTION => JSON NAME => " + jsonName + "JOSN Data => " + JSON.stringify(jsonData));

            var value = {}

            value[TABLE_COL_JSON_NAME] = jsonName,
                // datatype is number
                value[TABLE_COL_JSON_DATA] = jsonData


            var whereClause = {};

            whereClause[TABLE_COL_JSON_NAME] = jsonName

            ConsoleLogger.log(context, "Note => " + note + " VALUES TO BE updateED = > " + JSON.stringify(value));
            ConsoleLogger.log(context, "Note => " + note + " TABLE NAME => " + TABLE_NAME);

            ConsoleLogger.log(context, "Note => " + note + " CONNECTION DETAILS IN update => " + JSON.stringify(connection));
            window['JsStoreWorker'] = JsStoreWorker;
            var connection = new JsStore.Instance();
            connection.openDb(DB_NAME);
            connection.update({
                in: TABLE_NAME,
                where: whereClause,
                set: value
            }).then(function (rowsUpdated) {
                ConsoleLogger.log(context, "Note => " + note + " updateED VALUE  => " + JSON.stringify(rowsUpdated));
                if (rowsUpdated > 0) {
                    ConsoleLogger.log(context, "Note => " + note + " updateed rowsUpdated Length => " + rowsUpdated);
                    var successResponse = {
                        "status": CUSTOM_DB_SUCESS_CODE,
                        "message": "success"
                    }
                    resolve(successResponse);

                } else {
                    var status = InsertIntoDb.addItem(jsonName, jsonData, note)
                        .then(function (responseJson) {
                            resolve(responseJson)
                        }).catch(function (error) {
                            var exceptionResponse = {
                                "status": CUSTOM_DB_ERROR_CODE,
                                "message": error.message
                            }
                            ConsoleLogger.log(context, "Note => " + note + " ERROR IN updateING VALUES TO DB => " + error.message);
                            console.log(error);
                            //alert(err.message);
                            reject(exceptionResponse);
                        })
                }
            }).catch(function (err) {
                var exceptionResponse = {
                    "status": CUSTOM_DB_ERROR_CODE,
                    "message": err.message
                }
                ConsoleLogger.log(context, "Note => " + note + " ERROR IN updateING VALUES TO DB => " + err.message);
                console.log(err);
                //alert(err.message);
                reject(exceptionResponse);

            });
        });


    }




    return {
        updateItem: updateItem
    }

})();

export default UpdateDataDb;`

**Comment by ShoubhikBanerjee** [comment]
Please sir, I need your Help

**Comment by ujjwalguptaofficial** [comment]
Have you checked react example provided by jsstore ?

**Comment by ShoubhikBanerjee** [comment]
Yes Sir, I have gone through it previously 

> you dont need to defined the jsstoreworker multiple times.

I have defined it once previously.. but the problem is the same, So just in order to chcek... I defined it multiple times

**Comment by ujjwalguptaofficial** [comment]
do one thing, change ur code based on the example, then run the codes and let me know.

**Comment by ShoubhikBanerjee** [comment]
Ok sir... But colud you tell me that my JsWorker declaration is correct or not? 

i.e 

> import * as JsStoreWorker from "jsstore/dist/jsstore.worker.commonjs2";

> window['JsStoreWorker'] = JsStoreWorker;

Or I would declare it as per the example : i.e

> const Worker = require("worker-loader?publicPath=/&name=jsstore.worker.js!jsstore/dist/jsstore.worker.min");

**Comment by ujjwalguptaofficial** [comment]
part of the example would be good as it is using web worker unless you have some problem using worker . Executing in web worker will be more faster.

**Comment by ShoubhikBanerjee** [comment]
actualy sir, I am not able to find :  `const Worker = require("worker-loader?publicPath=/&name=jsstore.worker.js!jsstore/dist/jsstore.worker.min");`

It gives me error

> Unexpected '!' in 'worker-loader?publicPath=/&name=jsstore.worker.js!jsstore/dist/jsstore.worker.min'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax

**Comment by ujjwalguptaofficial** [comment]
You need to install the worker-loader.

```
npm i worker-loader -D
```

**Comment by ShoubhikBanerjee** [comment]
I have tried what you said , but end up with another error  : 


`TypeError: "this.queryExecutor_ is undefined"`

**Comment by ujjwalguptaofficial** [comment]
Compile error or run time error ?

**Comment by ShoubhikBanerjee** [comment]
Runtime error

in " isDbExist "  method

**Comment by ujjwalguptaofficial** [comment]
Let's talk here - https://gitter.im/JsStore/Lobby

**Comment by ShoubhikBanerjee** [comment]
OK

**Comment by ujjwalguptaofficial** [comment]
Issue was solved . Problem was not in jsstore but with the way user was using it. Problems were -

* multiple connection being created
* Jsstore not being initiated properly
