### ISSUE TITLE
How to update where column = null

### ISSUE THREAD

**Issue by yuval-hazaz** [ujjwalguptaofficial/JsStore#88]
How can I update all records where a specific field is null.
I tried this code
`this.connection.update({
      in: "Messages",
      set: {
        DateArrived: dateArrived
      },
      where: {
        DateArrived: null
      }
    })`

and I got this error
TypeError: Cannot convert undefined or null to object

Thank you very much for this great library

**Comment by ujjwalguptaofficial** [comment]
Hi ,

Please check this page - https://stackoverflow.com/questions/52749199/jsstore-search-for-a-null-value
