### ISSUE TITLE
Order by  date column

### ISSUE THREAD

**Issue by yuval-hazaz** [ujjwalguptaofficial/JsStore#89]
From the source code is looks like you are only supporting order by for columns of type string or number.
Are there any plans to support order by for dates?

`if (column == null) {
                this.errorOccured = true;
                this.error = new _log_helper__WEBPACK_IMPORTED_MODULE_2__["LogHelper"](_enums__WEBPACK_IMPORTED_MODULE_1__["ERROR_TYPE"].InvalidColumn, { column: orderColumn_1 });
            }
            else if (column.dataType === _enums__WEBPACK_IMPORTED_MODULE_1__["DATA_TYPE"].String) {
                if (order.type === 'asc') {
                    sortAlphabetInAsc();
                }
                else {
                    sortAlphabetInDesc();
                }
            }
            else if (column.dataType === _enums__WEBPACK_IMPORTED_MODULE_1__["DATA_TYPE"].Number) {
                if (order.type === 'asc') {
                    sortNumberInAsc();
                }
                else {
                    sortNumberInDesc();
                }
            }`

**Comment by ujjwalguptaofficial** [comment]
Yes sure, I will add this feature.

**Comment by ujjwalguptaofficial** [comment]
Hi

The feature is added to v 2.9.3. Please download latest version and check from ur side and let me know.

An example for reference - 

```
 con.select({
            from: 'Employees',
            order: {
                by: 'birthDate',
                type: 'desc',
                idbSorting: false
            }
        })
```
