### ISSUE TITLE
Transaction logic generate by dynamic businuess'logic

### ISSUE THREAD

**Issue by f5cs** [ujjwalguptaofficial/JsStore#90]
**can u put the some feature to native api ? for example:**

	function hcdb_transation_txlogic(data) {
    var txScope = this;
    var fns = function(txLogic_){
        var txLogic = txLogic_;
        if(txLogic.operation==='select'){
            if(txLogic.rpn){
                select(txLogic.params).then(function(rs){
                    setResult(txLogic.rpn,rs);
                });
            }else{
                select(txLogic.params);
            }
        }else if(txLogic.operation==='count'){
            if(txLogic.rpn){
                count(txLogic.params).then(function(rs){
                    setResult(txLogic.rpn,rs);
                });
            }else{
                count(txLogic.params);
            }
        }else if(txLogic.operation==='update'){
            if(txLogic.rpn){
                update(txLogic.params).then(function(rs){
                    setResult(txLogic.rpn,rs);
                });
            }else{
                update(data.initLogics[o].params);
            }
        }else if(txLogic.operation==='remove'){
            if(txLogic.rpn){
                remove(txLogic.params).then(function(rs){
                    setResult(txLogic.rpn,rs);
                });
            }else{
                remove(txLogic.params);
            }
        }else if(txLogic.operation==='insert'){
            if(txLogic.rpn){
                insert(txLogic.params).then(function(rs){
                    setResult(txLogic.rpn,rs);
                });
            }else{
                insert(txLogic.params);
            }
        }
    }
    for(var o=0;o<data.txLogixs.length;o++){
        fns(data.txLogixs[o]);
    }
	}

	var transaction = {
		tables:null,//@TODO change to hashMap obj
		dynParam:null, //dynamic paprams
		txLogixs:null,
		addTable:function(tblName){
			this.tables[tblName]=true;
		},
		begin:function(){
			this.tables={};
			this.dynParam={};
			this.txLogixs=[];
		},
		commit:function(cbk){
			var tables = [];
			Object.keys(this.tables).forEach(function(key){
				tables.push(this.tables[key]);
			});
			if(tables.length === 0 || this.txLogixs.length === 0){
				return;
			}
        		connection.transaction({
            			tables: tables,
            			data:{txLogixs:this.txLogixs,dynParam:this.dynParam},
            			logic: hcdb_transation_txlogic
       			}).then(function(result){
				//callback
				if(cbk)cbk(result);
			}).catch(function(err){
				if(cbk)cbk(err);
			});
		}
	};

	function serviceXxx(txLogixs){
		//... some logic
		//... some logic
		txLogixs.push({
			operation:'count', params:{from:'Trans_act_cons', where:{aid:aid,cons:{'>':0}},return: true},
			rpn:'cnt_gl'
		});
		//... some logic
	}

       **//start anywhere**
	transaction.begin();
	transaction.addTable('Trans_act');
	transaction.txLogixs.push({
            operation: 'select', params: {from: 'Trans_act', where: {tid: tid, aid: aid, owner: getMyUserName()},return: true},
            rpn:'trans_acts'
    });
	
	...
	
	if(v1 > 1){
            transaction.addTable('Trans_act_cons');
		transaction.txLogixs.push({
            operation:'count', params:{from:'Trans_act_cons', where:{aid:aid,rs:{'!=':null}},return: true},
            rpn:'cnt_cp'
        });
	}
	
	...
	
	serviceXxx(transaction.txLogixs);
	
	...
	
       **//commit anywhere**
	transaction.commit(function(result){
		console.log('my result is' + JSON.stringify(result))
	});

**Comment by ujjwalguptaofficial** [comment]
seems interesting ,  I will look into this.

**Comment by ujjwalguptaofficial** [comment]
@f5cs - I have updated the transaction api. Now in order to start the tx - you need to call `start` And now you can call an api when a tx has started( after completion of api ).

Please see the docs - http://jsstore.net/tutorial/transaction/

**Comment by ujjwalguptaofficial** [comment]
Also your code sounds ok, but I cant implement it due to several reasons.

**Comment by f5cs** [comment]
hi ujjwalguptaofficial, my idea is not change stand transaction.only to extend a function.
I want to decouple business logic from data operations, but I also want data storage of complex logic to have the transaction feature.

async function dynamicLogicFunction(data){
	var txScope = this;
	var fns = function(txLogic_){
		...
	}
	start();
	for(var o=0;o<data.txLogixs.length;o++){
		fns(data.txLogixs[o]);
	}
	....
}

var dynamicTrans=function(config){
	return {
		begin:function(){
			this.tables={};
			this.dynParam={};
			this.txLogixs=[];
			console.log("=====");
		},
		addTable:function(tblName){
			this.tables[tblName]=true;
		},
		tables:null,
		dynParam:null,
		txLogixs:null,
		commit:function(cbk){
			var tables = [];
			Object.keys(this.tables).forEach(function(key){
				tables.push(this.tables[key]);
			});
			if(tables.length === 0 || this.txLogixs.length === 0){
				return;
			}
			connection.transaction({
				tables: tables,
				data:{txLogixs:this.txLogixs,dynParam:this.dynParam},
				logic:dynamicLogicFunction
			}).then(function(result){
				if(cbk)cbk(result);
			}).catch(function(err){
				if(cbk)cbk(err);
			});
		}
	}
};

use eg.
function myService(){
	...
	this.init();
}
myService.prototype.init = function(){
	this.dynTrans = dynamicTrans();

}
myService.prototype.start = function(){
	 //will init tables,param,logic
	 thisdynTrans.begin();
}

myService.prototype.sayHello = function(){
	...
	...
	dynTrans.addTable('Trans_msg');
	dynTrans.txLogixs.push({
			operation: 'insert', params: {values: [{msgContent:'hello!'}]},
			rpn:'trans_msg'
	});
}

myService.prototype.toOrding = function(){
	...
	...
	dynTrans.addTable('Trans_Order');
	dynTrans.txLogixs.push({
			operation: 'insert', params: {values: [{amount:100,time:new Date()}]},
			rpn:'trans_order'
	});
}

myService.prototype.toPay = function(){
	......
}

myService.prototype.toClose = function(){
	...
	...
	//send msg to other person
	mysock.sendMsg({order:'aaa',.....})
	this.end();
}

myService.prototype.end = function(){
	 //will call connection.transaction({}) save data to indexdDB
	 thisdynTrans.commit();
}
	
//Non jsstore code
.....
.....
var service1 =new myService();
service1.start();

if(case1){
	service1.sayHello();
}

//Non jsstore code
.....
.....

if(cases2){
	service1.toOrding();
}

if(cases3){
	service1.toPay();
}

service1.close();
	
	
//Non jsstore code can execute any function,any where, any time
//until execte function dynTrans.commit then call jsstore code connection.transaction({}) to exe jsstore transaction

**Comment by ujjwalguptaofficial** [comment]
so you want to call non jsstore code within the transaction right ?

like - if I call the select of transaction, just after that I should be able to call some other function not within jsstore .

**Comment by f5cs** [comment]
No，be just reversed。
 I want the logics of a tranaction  can be dispersed into different functions. When these function are completed, then generate the final SQL logic of the transaction to be executed,and then to exe connection.transaction to save data into indexeddb.
Use the current API，i need to write many business Logic Judgment inside the connection.transaction.
I want to strip these business logic out of connection.transaction,  distribute these logics into any function,only sql in connection.transaction.
The advantage of doing this is to increase the reusability of business functions, write and maintain one place, and reuse many times.

**Comment by ujjwalguptaofficial** [comment]
Hi

I have changed transaction API codes, now you can use closures and all variables inside the transaction api too. But this functionality will be only available when you are executing the jsstore without web worker.

Also there are some minor changes in API uses too. Check out the latest doc at - https://jsstore.net/tutorial/transaction/
