### ISSUE TITLE
can support update set columnA = columnB ?

### ISSUE THREAD

**Issue by f5cs** [ujjwalguptaofficial/JsStore#91]
connection.update({ 
      in: "Table_Name",
    set: {
        ### Column1: Column3,
        Column2: value2
    },where: {
        Column3: some_value,
        Column4: some_another_value
    }
})

**Comment by ujjwalguptaofficial** [comment]
Hi, That can be done by keeping the value in a variable like this - 

```
var column3Val = some_value  // keeping the value in a variable
connection.update({
    in: "Table_Name",
    set: {
        Column1: column3Val,
        Column2: value2
    },
    where: {
        Column3: column3Val,
        Column4: some_another_value
    }
})
```

But if you don't know the value then , you can select the value and then update it.  You can use transaction for performing the two operation (select and update) in a single query.

Hope this answers , what you are looking for.
