### ISSUE TITLE
Transaction : Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.

### ISSUE THREAD

**Issue by mccoysc** [ujjwalguptaofficial/JsStore#92]
Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.

get an error as the above when

conn.transaction({
                tables: [tblName],
                logic: execToDb,
                data: data
            })
and data[0] is like this:
{key:{sub-key1:value1}}

**Comment by mccoysc** [comment]
work in web worker mode

**Comment by ujjwalguptaofficial** [comment]
so you are saying that - its working in webworker  but not without webworker ?

**Comment by mccoysc** [comment]
No……i mean my code envirement is the worker version

**Comment by ujjwalguptaofficial** [comment]
I am sorry but I am not able to understand. You said in first comment that its not working but again in  second comment that its working in web worker. Could you please explain when its working and when not ?

**Comment by ujjwalguptaofficial** [comment]
This error "Evaluating the object store's key path did not yield a value " means - you are not supplying value for a column which is required field.

**Comment by mccoysc** [comment]
I mean my code is like this:
conn=new jsstore(new webwork)

**Comment by ujjwalguptaofficial** [comment]
could you provide me your codebase if possible ? So that I can reproduce the issue and fix.

**Comment by mccoysc** [comment]
[jsStoreDisk.js.txt](https://github.com/ujjwalguptaofficial/JsStore/files/2775180/jsStoreDisk.js.txt)

**Comment by mccoysc** [comment]
the issue is caused by function 'flush(true)';

**Comment by ujjwalguptaofficial** [comment]
The issue is in jsstore, while using transaction - autoincrement column is not being incremented and that's why the issue.

I will fix it asap and let you know.

**Comment by mccoysc** [comment]
not ok...see gitter

**Comment by mccoysc** [comment]
@ujjwalguptaofficial
