### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#93]
Hi,

Sometimes my site gives "Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found." after clearing cache it is fine.

Can you give me any solution for this.

I am using 1.6.3 in my website.(jsstore 2 doesn't work in ipad safari.So Iam using 1.6.3 which is good in ipad)

Thanks and Regards,
Kamala

**Comment by ujjwalguptaofficial** [comment]
Hi -This means table does not exist. 

But since jsstore has been upgrade to v2. I will request you to use v2. You can file - what issue you are getting while using in safari ipad and I will fix those issue.

Thanks

**Comment by kamalakkanni** [comment]
Do you have any sample site using jsstore v2.I will check and reproduce the issue in ipad safari.since,I was reverted my code to v1.It is in live.I can't change now

**Comment by kamalakkanni** [comment]
content not downloaded in ipad safari.That's y I reverted my code.

**Comment by ujjwalguptaofficial** [comment]
yes - you can use : https://ujjwalguptaofficial.github.io/idbstudio/.

**Comment by kamalakkanni** [comment]
I used this link and inserted some data to customers table it is fine.

**Comment by ujjwalguptaofficial** [comment]
It has latest version - 2.10.1

**Comment by kamalakkanni** [comment]
ok.I will try and let you know.Thanks

**Comment by kamalakkanni** [comment]
I changed my code to 2.10.1 .I got "Expected an identifier but found 'k' instead in jsstore.worker.min.js" in safari 5.1.4.Promise not defined " in ie11

**Comment by ujjwalguptaofficial** [comment]
use jsstore.worker.ie.min.js for support in ie.

**Comment by kamalakkanni** [comment]
I am using jsstore.worker.ie.min.js only.

**Comment by ujjwalguptaofficial** [comment]
Hi as you said - idbstudio is working great on the same device, which
clearly means there is some problem in ur code. Please try to figure it out.

And please add ur screenshot. That will give me an idea what could be wrong.

**Comment by kamalakkanni** [comment]
idbstudio also not working in ie.I told that idbstudio is working on ipad

**Comment by kamalakkanni** [comment]
I didn't check my site in ipad.I will check and let you know

**Comment by kamalakkanni** [comment]
Its working fine in ipad.Thanks.

**Comment by ujjwalguptaofficial** [comment]
what issue you were getting in ie ?

**Comment by kamalakkanni** [comment]
![Uploading image.png…]()

**Comment by ujjwalguptaofficial** [comment]
try now - https://ujjwalguptaofficial.github.io/idbstudio/

there was small issue regarding the ie build due to project structure being changed. This has been resolved in v 2.10.2.
