### ISSUE TITLE
Join should accept "as"

### ISSUE THREAD

**Issue by ditiem** [ujjwalguptaofficial/JsStore#94]
When performing a query with a "join", and object with the names of the tables is returned. Problem is when performing 2 joins on 2 columns that join the same table. Example:

```
SELECT *
FROM Activity
JOIN place on activity.from_place = place.place_id 
JOIN place on activity.to_place = place.place_id 
```

this would return something like a list of { 'activity': ..., 'place': ... } which create a name clash. Adding "AS" would fix it:

```
SELECT *
FROM Activity
JOIN place on activity.from_place = place.place_id AS t1
JOIN place on activity.to_place = place.place_id AS t2
```

This should return something like a list of { activity: ..., t1: ..., t2: ... } and potentially a where could be performed on t1 and t2.

**Comment by ujjwalguptaofficial** [comment]
Its been solved in new version - 3.0.0. Please read the doc - http://jsstore.net/tutorial/join/

**Comment by ujjwalguptaofficial** [comment]
Here is an example - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0A%20%20%20%20from%3A%20%22Customers%22%2C%0A%20%20%20%20join%3A%20%7B%0A%20%20%20%20%20%20%20%20with%3A%20%22Customers%22%2C%0A%20%20%20%20%20%20%20%20type%3A%20%22inner%22%2C%0A%20%20%20%20%20%20%20%20on%3A%20%22Customers.city%3DCustomers.city%22%2C%0A%20%20%20%20%20%20%20%20as%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20customerName%3A%20%22name%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20contactName%3A%20%22cName%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20customerID%3A%20%22cId%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20address%3A%20%22address%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20postalCode%3A%20%22postalCode%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20country%3A%20%22country%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20email%3A%20%22email%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20customerId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'%3C'%3A%2090%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D)
