### ISSUE TITLE
Promise undefined in IE11

### ISSUE THREAD

**Issue by sharathic** [ujjwalguptaofficial/JsStore#97]
Promise undefined issue in IE11 even after updating to the latest version

**Comment by ujjwalguptaofficial** [comment]
make sure you are using - worker file built for ie. You can take reference of this example - https://github.com/ujjwalguptaofficial/JsStore/tree/master/examples/webpack%20with%20ie%20support

**Comment by sharathic** [comment]
I have already added the latest version of jsstore(2.10.2) to the project.. am i supposed to add the worker for ie manually?

**Comment by ujjwalguptaofficial** [comment]
generally the file - jsstore.worker.min.js but for ie it is jsstore.worker.ie.min.js .

I needed to built separate file for ie which includes some polyfill like promise etc. 

for checking whether your browser is supporting jsstore , you can view this url and  click on execute button -  http://jsstore.net/example/select/  . You should see the result.

**Comment by ujjwalguptaofficial** [comment]
just for clarity : 

without i.e support -     
`var connection = new JsStore.Instance(new Worker('jsstore.worker.min.js'));`

 with i.e support - 
`var connection = new JsStore.Instance(new Worker('jsstore.worker.ie.min.js'));`

**Comment by ujjwalguptaofficial** [comment]
@sharathic - join examples ae

**Comment by sharathic** [comment]
thank u :)

**Comment by sharathic** [comment]
in future release are you planning to include the IE support within the jsstore.worker.min.js or will it be in seperate file jsstore.worker.ie.min.js? i am asking this inorder to avoid problems in the project in future .. thank you :)

**Comment by ujjwalguptaofficial** [comment]
it will be like this.

Most if the people - don't care about ie support and Including the
polyfills increases the size of file, that's why i cant include those
polyfills code for all.
