### ISSUE TITLE
Unable to execute JOIN logic

### ISSUE THREAD

**Issue by yuval-hazaz** [ujjwalguptaofficial/JsStore#98]
I am trying to write a query with a JOIN statement and can't find the right way to do it.
The following links taken from for the examples on the website are broken
http://jsstore.net/example/simple_join
http://jsstore.net/example/multiple_table_join

I crated this query for example but I can't get it to return any data.

https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0D%0A%20%20%20%20from%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20table1%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20table%3A%20%22Products%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20column%3A%20%22categorId%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20where%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20productId%3A%201%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20join%3A%20'inner'%2C%0D%0A%20%20%20%20%20%20%20%20table2%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20table%3A%20%22Categories%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20column%3A%20%22categorId%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20where%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20categorId%3A%201%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B

**Comment by ujjwalguptaofficial** [comment]
@yuval-hazaz - if you will open the console, you will see some error.

I have corrected ur code and here is the link - https://ujjwalguptaofficial.github.io/idbstudio/?db=Demo&query=select(%7B%0D%0A%20%20%20%20from%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20table1%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20table%3A%20%22Products%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20column%3A%20%22categoryId%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20where%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20productId%3A%201%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20join%3A%20'inner'%2C%0D%0A%20%20%20%20%20%20%20%20table2%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20table%3A%20%22Categories%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20column%3A%20%22categoryId%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20where%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20categoryId%3A%201%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B

**Comment by ujjwalguptaofficial** [comment]
@yuval-hazaz - join examples are also fixed. Please check and let me know.

**Comment by yuval-hazaz** [comment]
I can confirm that the links to the examples are working fine now.
Thank you very much
Please also note that "table1" and "table2" objects in the snippets on the
page are missing comms

var joinLogic = { table1: { table: table1_name column: table1.common_field
where: { Column1: some_value } }, join: 'inner', table2: { table:
table2_name column: table2.common_field where: { Column1:
some_another_value } } }

**Comment by ujjwalguptaofficial** [comment]
@yuval-hazaz - could you fork the repo and fixed the " ", issue ?

**Comment by yuval-hazaz** [comment]
I would love to do so but the issue I reported is in the tutorial in
http://jsstore.net/tutorial/join/ and not in the package itself

**Comment by ujjwalguptaofficial** [comment]
@yuval-hazaz - our docs are also maintained using GitHub & travis, so completely open source.  The docs project is on another repo - https://github.com/ujjwalguptaofficial/jsstore.docs/ . You can change the content and send the PR.

Hope this helps. Looking forward to see the contribution. Thanks.
