### ISSUE TITLE
Like is not working when the column value has / character

### ISSUE THREAD

**Issue by Manivannan372** [ujjwalguptaofficial/JsStore#99]
Lets say i have a column value  as 'a.b.abc/abcdef'

the like expression is : 'a%.abc/adbcdef'

i  getting mulitple values even if i have only one value for my expression.

**Comment by ujjwalguptaofficial** [comment]
Could you tell me what are you trying to do ? I mean - "Finds any values that contains / at any position" or something else.

**Comment by ujjwalguptaofficial** [comment]
Please give me the db schema & some samples to generate the issue. 

Closing due to inacitivity
